#!/usr/bin/env python3
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.

# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.

# --------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# --------------------------------------------------------------------------------
"""Generate VfSimParamsGenerated.h from CSV parameter files."""

from __future__ import annotations

import csv
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PARAM_DIR = SCRIPT_DIR / "params"
OUT_PATH = SCRIPT_DIR / "VfSimParamsGenerated.h"


def _read_csv(name: str, expected_header: list[str]) -> list[dict[str, str]]:
    path = PARAM_DIR / name
    with path.open("r", encoding="utf-8", newline="") as file_obj:
        reader = csv.DictReader(file_obj)
        if reader.fieldnames != expected_header:
            raise ValueError(f"Invalid header in {path}: {reader.fieldnames}, expected {expected_header}")
        return [{key: value.strip() for key, value in row.items()} for row in reader]


def _escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def _int(text: str) -> str:
    return str(int(text))


def _render_array(name: str, row_type: str, rows: list[str]) -> list[str]:
    return [f"inline constexpr std::array<{row_type}, {len(rows)}> {name} = {{{{", *rows, "}};", ""]


def _load_params() -> dict[str, list[dict[str, str]]]:
    return {
        "defaults": _read_csv("isa_defaults.csv", ["key", "value"]),
        "isa": _read_csv(
            "isa.csv",
            [
                "op",
                "form",
                "pipeline_startup_cost",
                "latency",
                "throughput",
                "pipeline_drain_cost",
                "data_load_cost",
                "data_store_cost",
                "EXU",
                "dispatch_exu",
                "op_class",
            ],
        ),
        "uarch": _read_csv("uarch.csv", ["key", "type", "value"]),
        "forwarding": _read_csv("forwarding.csv", ["producer", "consumer", "cycles"]),
        "initiation_interval": _read_csv("initiation_interval.csv", ["previous", "current", "cycles"]),
    }


def _render_prelude() -> list[str]:
    return [
        "// Copyright (c) 2026 Huawei Technologies Co., Ltd.",
        "// SPDX-License-Identifier: CANN-1.0",
        "",
        "// Auto-generated by include/pto/costmodel/a5/VfSim/gen_vfsim_params_header.py from",
        "// include/pto/costmodel/a5/VfSim/params/*.csv.",
        "// Do not edit this file manually.",
        "",
        "#ifndef VFSIM_NATIVE_PARAMS_GENERATED_H",
        "#define VFSIM_NATIVE_PARAMS_GENERATED_H",
        "",
        "#include <array>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace vfsim::generated {",
        "",
        "struct IsaDefaultParam {",
        "  std::string_view key;",
        "  int64_t value;",
        "};",
        "",
        "struct IsaInstParam {",
        "  std::string_view op;",
        "  std::string_view form;",
        "  int64_t pipelineStartupCost;",
        "  int64_t latency;",
        "  int64_t throughput;",
        "  int64_t pipelineDrainCost;",
        "  int64_t dataLoadCost;",
        "  int64_t dataStoreCost;",
        "  std::string_view exu;",
        "  std::string_view dispatchExu;",
        "  std::string_view opClass;",
        "};",
        "",
        "struct UarchParam {",
        "  std::string_view key;",
        "  std::string_view type;",
        "  std::string_view value;",
        "};",
        "",
        "struct BinaryRelationParam {",
        "  std::string_view lhs;",
        "  std::string_view rhs;",
        "  int64_t cycles;",
        "};",
        "",
    ]


def _render_defaults(rows: list[dict[str, str]]) -> list[str]:
    return _render_array(
        "kIsaDefaultParams",
        "IsaDefaultParam",
        [f'  {{"{_escape(row["key"])}", {_int(row["value"])}}},' for row in rows],
    )


def _render_isa(rows: list[dict[str, str]]) -> list[str]:
    return _render_array(
        "kIsaInstParams",
        "IsaInstParam",
        [
            (
                f'  {{"{_escape(row["op"])}", "{_escape(row["form"])}", '
                f"{_int(row['pipeline_startup_cost'])}, {_int(row['latency'])}, {_int(row['throughput'])}, "
                f"{_int(row['pipeline_drain_cost'])}, {_int(row['data_load_cost'])}, "
                f'{_int(row["data_store_cost"])}, "{_escape(row["EXU"])}", '
                f'"{_escape(row["dispatch_exu"])}", "{_escape(row["op_class"])}"}},'
            )
            for row in rows
        ],
    )


def _render_uarch(rows: list[dict[str, str]]) -> list[str]:
    return _render_array(
        "kUarchParams",
        "UarchParam",
        [f'  {{"{_escape(row["key"])}", "{_escape(row["type"])}", "{_escape(row["value"])}"}},' for row in rows],
    )


def _render_forwarding(rows: list[dict[str, str]]) -> list[str]:
    return _render_array(
        "kForwardingParams",
        "BinaryRelationParam",
        [f'  {{"{_escape(row["producer"])}", "{_escape(row["consumer"])}", {_int(row["cycles"])}}},' for row in rows],
    )


def _render_initiation_interval(rows: list[dict[str, str]]) -> list[str]:
    return _render_array(
        "kInitiationIntervalParams",
        "BinaryRelationParam",
        [f'  {{"{_escape(row["previous"])}", "{_escape(row["current"])}", {_int(row["cycles"])}}},' for row in rows],
    )


def _render() -> str:
    params = _load_params()
    lines = _render_prelude()
    lines.extend(_render_defaults(params["defaults"]))
    lines.extend(_render_isa(params["isa"]))
    lines.extend(_render_uarch(params["uarch"]))
    lines.extend(_render_forwarding(params["forwarding"]))
    lines.extend(_render_initiation_interval(params["initiation_interval"]))
    lines.extend(["} // namespace vfsim::generated", "", "#endif // VFSIM_NATIVE_PARAMS_GENERATED_H", ""])
    return "\n".join(lines)


def main() -> None:
    OUT_PATH.write_text(_render(), encoding="utf-8")


if __name__ == "__main__":
    main()
