#!/usr/bin/env python3
# coding=utf-8

import argparse
import json
from pathlib import Path

DEFAULT_CASE = {
    "t": 256,
    "e": 16,
    "k": 4,
}


def parse_case(raw: str) -> dict:
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    if len(parts) != 3:
        raise ValueError(f"Expected T,E,K, got '{raw}'")
    t, e, k = map(int, parts)
    if min(t, e, k) <= 0:
        raise ValueError("All router_topk_small case values must be positive")
    if k > e:
        raise ValueError("K cannot exceed E")
    if k > 10:
        raise ValueError("router_topk_small supports K <= 10")
    return {"t": t, "e": e, "k": k}


def case_name(case: dict) -> str:
    return f"case_T{case['t']}_E{case['e']}_K{case['k']}"


def render_header(case: dict) -> str:
    return f"""#pragma once
// Auto-generated by scripts/generate_cases.py. Do not edit manually.
// clang-format off

static constexpr int kRouterTopkSmallT = {case["t"]};
static constexpr int kRouterTopkSmallE = {case["e"]};
static constexpr int kRouterTopkSmallK = {case["k"]};
static constexpr const char *kRouterTopkSmallCaseName = "{case_name(case)}";

// clang-format on
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate router_topk_small case header/JSON")
    parser.add_argument("--cases", default=None, help="Single case: T,E,K")
    parser.add_argument(
        "--output-header",
        default=str(Path(__file__).resolve().parent.parent / "build" / "generated_cases.h"),
    )
    parser.add_argument(
        "--output-json",
        default=str(Path(__file__).resolve().parent.parent / "build" / "generated_cases.json"),
    )
    args = parser.parse_args()

    case = parse_case(args.cases) if args.cases else dict(DEFAULT_CASE)
    payload = {"name": case_name(case), **case}

    header_path = Path(args.output_header)
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(render_header(case))

    json_path = Path(args.output_json)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps([payload], indent=2))

    print(f"[INFO] Wrote {header_path}")
    print(f"[INFO] Wrote {json_path}")
    print(f"[INFO] Case: {payload}")


if __name__ == "__main__":
    main()
