/**
Copyright (c) 2026 Huawei Technologies Co., Ltd.
This program is free software, you can redistribute it and/or modify it under the terms and conditions of
CANN Open Software License Agreement Version 2.0 (the "License").
Please refer to the License for details. You may not use this file except in compliance with the License.
THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
See LICENSE in the root of the software repository for the full text of the License.
*/

#ifndef DISPATCH_FFN_COMBINE_V8_PROFILE_DEBUG_CONFIG_H
#define DISPATCH_FFN_COMBINE_V8_PROFILE_DEBUG_CONFIG_H

#ifndef DISPATCH_FFN_COMBINE_V8_ENABLE_INNER_PROFILE
#define DISPATCH_FFN_COMBINE_V8_ENABLE_INNER_PROFILE 0
#endif

#ifndef DISPATCH_FFN_COMBINE_V8_ENABLE_DETAIL_PROFILE
#define DISPATCH_FFN_COMBINE_V8_ENABLE_DETAIL_PROFILE DISPATCH_FFN_COMBINE_V8_ENABLE_INNER_PROFILE
#endif

#ifndef DISPATCH_FFN_COMBINE_V8_ENABLE_DEVICE_DEBUG
#define DISPATCH_FFN_COMBINE_V8_ENABLE_DEVICE_DEBUG 0
#endif

#ifndef DISPATCH_FFN_COMBINE_V8_GMM1_V2C_WAIT_PROBE_EXTRA
#define DISPATCH_FFN_COMBINE_V8_GMM1_V2C_WAIT_PROBE_EXTRA 0
#endif

#endif // DISPATCH_FFN_COMBINE_V8_PROFILE_DEBUG_CONFIG_H
