#!/bin/bash
# full_moe_combined - end-to-end MoE; one host wrapper launcher, six kernels on
# the same stream with only one final sync.
# Single-case-per-binary; shape is generated by the local wrapper.

SHORT=r:,v:,C:,n:,a:
LONG=run-mode:,soc-version:,compiler:,npu:,cases:,msopprof
OPTS=$(getopt -a --options $SHORT --longoptions $LONG -- "$@")
eval set -- "$OPTS"
while :
do
    case "$1" in
        (-r | --run-mode )   RUN_MODE="$2"; shift 2;;
        (-v | --soc-version )SOC_VERSION="$2"; shift 2;;
        (-C | --compiler )
            CMAKE_COMPILER="$2"
            shift 2;;

        (-n | --npu )        NPU_ID="$2"; shift 2;;
        (-a | --cases )      CASES_RAW="$2"; shift 2;;
        (--msopprof )
            MSOPPROF=1
            shift 1;;
        (--) shift; break;;
        (*) echo "[ERROR] Unexpected option: $1"; break;;
    esac
done

run_msopprof() {
    if [[ "${MSOPPROF:-0}" == "1" ]]; then
        mkdir -p msopprof_data
        msopprof --output=msopprof_data "$@"
    else
        "$@"
    fi
}

: "${CMAKE_COMPILER:=bisheng}"

if [[ ! "${SOC_VERSION}" =~ ^Ascend ]]; then
    echo "[ERROR] Unsupported SocVersion: ${SOC_VERSION}"
    exit 1
fi

if [[ "${SOC_VERSION}" =~ ^Ascend910B4-1 ]] && [ "${RUN_MODE}" == "sim" ]; then
    echo "[ERROR] SocVersion: ${SOC_VERSION} can not support sim mode, please use Ascend910B4."
    exit 1
fi

: "${NPU_ID:=0}"

GEN_CASE_ARGS=()
if [[ -n "${CASES_RAW:-}" ]]; then
    GEN_CASE_ARGS+=(--cases "${CASES_RAW}")
fi
python3 ../scripts/generate_cases.py "${GEN_CASE_ARGS[@]}" || exit 1

python ./scripts/gen_data.py || exit 1

rm -rf build
mkdir build
cd build

export LD_LIBRARY_PATH=${ASCEND_HOME_PATH}/tools/simulator/${SOC_VERSION}/lib:$LD_LIBRARY_PATH
set -euo pipefail

cmake  -DRUN_MODE=${RUN_MODE} -DSOC_VERSION=${SOC_VERSION} -DCMAKE_COMPILER=${CMAKE_COMPILER} ..
make -j16

run_msopprof ./full_moe_combined
