#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# --------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software; redistribute / modify under CANN Open Software
# License Agreement Version 2.0 (the "License"). See LICENSE for the full text.
# --------------------------------------------------------------------------------

"""
Generate HC (Hyper-Connections) family case configuration. Mirrors the CSA /
Compressor family generators:
    kernels/automode/a2a3/deepseekv4/CSA/scripts/generate_cases.py
    kernels/automode/a2a3/deepseekv4/HCA/Compressor/scripts/generate_cases.py

Case format: B, S, DIM, HC_MULT, SINKHORN_ITERS
  B               batch size (default 1)
  S               sequence length (tokens per sample)
  DIM             hidden dimension (ModelArgs.dim default 4096)
  HC_MULT         number of HC copies (ModelArgs.hc_mult default 4 — fixed in
                  the model; do not vary without code changes downstream)
  SINKHORN_ITERS  Sinkhorn normalization iteration count
                  (ModelArgs.hc_sinkhorn_iters default 20)

Derived:
  MIX_HC = (2 + HC_MULT) * HC_MULT          (= 24 for hc_mult=4)
  HC_EPS = 1e-6                              (ModelArgs.hc_eps)

Defaults:
  Realistic: B=1, S=128, DIM=4096, HC_MULT=4, SINKHORN_ITERS=20
  Tiny      (DEFAULT): B=1, S=16, DIM=64, HC_MULT=4, SINKHORN_ITERS=4

Output: <HC>/build/generated_cases.{h,json}
"""
import argparse
import json
from pathlib import Path
from typing import List, Dict

# Tiny default keeps the per-binary prototype small. Use --cases to opt in to
# the realistic shape.
DEFAULT_CASES = [
    (1, 16, 64, 4, 4),
]


def _parse_case_entry(raw: str) -> Dict[str, int]:
    parts = [p.strip() for p in raw.split(',') if p.strip()]
    if len(parts) != 5:
        raise ValueError(
            f"Expected 5 comma-separated values (B,S,DIM,HC_MULT,SINKHORN_ITERS), got '{raw}'"
        )
    b, s, dim, hc_mult, iters = map(int, parts)
    if min(b, s, dim, hc_mult, iters) <= 0:
        raise ValueError("All HC case values must be positive")
    if hc_mult != 4:
        # Model.py:651 / Block.__init__ assumes hc_mult fixes the parameter
        # shapes; downstream code (hc_split_sinkhorn_kernel, hc_pre, hc_post)
        # treats `comb` as [hc_mult, hc_mult]. Warn but allow for future use.
        print(f"[WARN] HC_MULT={hc_mult} != 4 (model default); verify downstream code")
    return {"b": b, "s": s, "dim": dim, "hc_mult": hc_mult, "iters": iters}


def _default_cases() -> List[Dict[str, int]]:
    return [
        {"b": b, "s": s, "dim": dim, "hc_mult": hc_mult, "iters": iters}
        for (b, s, dim, hc_mult, iters) in DEFAULT_CASES
    ]


def _mix_hc(c: Dict[str, int]) -> int:
    # kernel.py:374 — mix_hc = (2 + hc) * hc
    return (2 + c["hc_mult"]) * c["hc_mult"]


def _case_name(c: Dict[str, int]) -> str:
    return (
        f"case_B{c['b']}_S{c['s']}_D{c['dim']}_HC{c['hc_mult']}_I{c['iters']}"
    )


def _render_macro(cases: List[Dict[str, int]]) -> str:
    lines = ["#define HC_FOR_EACH_CASE(MACRO) \\"]
    for idx, c in enumerate(cases):
        suffix = " \\" if idx + 1 != len(cases) else ""
        line = (
            f"    MACRO({c['b']}, {c['s']}, {c['dim']}, {c['hc_mult']}, "
            f"{_mix_hc(c)}, {c['iters']}){suffix}"
        )
        lines.append(line)
    return "\n".join(lines)


def _render_header(cases: List[Dict[str, int]]) -> str:
    macro_block = _render_macro(cases)
    array_entries = []
    for c in cases:
        array_entries.append(
            "    {" + ", ".join([
                str(c["b"]),
                str(c["s"]),
                str(c["dim"]),
                str(c["hc_mult"]),
                str(_mix_hc(c)),
                str(c["iters"]),
                f'"{_case_name(c)}"',
            ]) + "}"
        )
    array_block = ",\n".join(array_entries)

    return f"""#pragma once
// Auto-generated by scripts/generate_cases.py. Do not edit manually.
// clang-format off
#include <cstddef>

{macro_block}

struct GeneratedHcCase {{
    int b;
    int s;
    int dim;
    int hc_mult;
    int mix_hc;
    int sinkhorn_iters;
    const char *name;
}};

static constexpr GeneratedHcCase kGeneratedHcCases[] = {{
{array_block}
}};
static constexpr std::size_t kGeneratedHcCasesCount =
    sizeof(kGeneratedHcCases) / sizeof(kGeneratedHcCases[0]);

// Convenience aliases — leaf binaries compile against the first case.
static constexpr int kHcB             = kGeneratedHcCases[0].b;
static constexpr int kHcS             = kGeneratedHcCases[0].s;
static constexpr int kHcDim           = kGeneratedHcCases[0].dim;
static constexpr int kHcMult          = kGeneratedHcCases[0].hc_mult;
static constexpr int kHcMixHc         = kGeneratedHcCases[0].mix_hc;
static constexpr int kHcSinkhornIters = kGeneratedHcCases[0].sinkhorn_iters;
static constexpr const char *kHcCaseName = kGeneratedHcCases[0].name;

// Eps: emitted as a constexpr float (header-friendly; constexpr-float #define
// is platform-fragile, so keep it as a static constexpr value).
static constexpr float kHcEps = 1e-6f;

// clang-format on
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate HC family case header/JSON")
    parser.add_argument(
        "--cases", action="append", default=None,
        help="Case entry: B,S,DIM,HC_MULT,SINKHORN_ITERS (repeat for multiple)",
    )
    parser.add_argument(
        "--output-header",
        default=str((Path(__file__).resolve().parent.parent / "build" / "generated_cases.h")),
    )
    parser.add_argument(
        "--output-json",
        default=str((Path(__file__).resolve().parent.parent / "build" / "generated_cases.json")),
    )
    args = parser.parse_args()

    if args.cases:
        cases = [_parse_case_entry(entry) for entry in args.cases]
    else:
        cases = _default_cases()

    header_path = Path(args.output_header)
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(_render_header(cases))

    json_payload = [
        {"name": _case_name(c), **c, "mix_hc": _mix_hc(c), "eps": 1e-6}
        for c in cases
    ]
    json_path = Path(args.output_json)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(json_payload, indent=2))

    print(f"[INFO] Wrote {header_path}")
    print(f"[INFO] Wrote {json_path}")
    for c in json_payload:
        print(
            f"  - {c['name']} (B={c['b']}, S={c['s']}, DIM={c['dim']}, "
            f"HC_MULT={c['hc_mult']}, MIX_HC={c['mix_hc']}, "
            f"SINKHORN_ITERS={c['iters']})"
        )


if __name__ == "__main__":
    main()
