
#ifndef CONST_ARGS_HPP
#define CONST_ARGS_HPP

#include <cstdint>

#include "pto/common/buffer_limits.hpp"

constexpr static uint64_t MB_SIZE = 1024 * 1024UL;
constexpr static int32_t NUMS_PER_FLAG = 16;
constexpr static int32_t CACHE_LINE = 512;
constexpr static int32_t RESET_VAL = 0xffff;
constexpr static int32_t FLAGSTRIDE = 16;
constexpr static int32_t UB_ALIGN = 32;
constexpr uint16_t CROSS_CORE_FLAG_MAX_SET_COUNT = 15;
constexpr uint16_t V5_MAX_BUSINESS_HARD_FLAG_ID = 4;
constexpr uint16_t V5_DISPATCH_V2C_HARD_FLAG_BASE = 0;
constexpr uint16_t V5_DISPATCH_V2C_HARD_FLAG_COUNT = 3;
constexpr uint16_t V5_DISPATCH_V2C_HARD_FLAG_LAST =
    V5_DISPATCH_V2C_HARD_FLAG_BASE + V5_DISPATCH_V2C_HARD_FLAG_COUNT - 1;
constexpr uint16_t V5_C2V_HARD_FLAG_BASE = 3;
constexpr uint16_t V5_V2C_HARD_FLAG_BASE = 4;
constexpr uint16_t V8_GMM2_COMBINE_CV_HARD_FLAG_BASE = 5;
constexpr uint16_t V8_GMM2_COMBINE_CV_READY_HARD_FLAG = V8_GMM2_COMBINE_CV_HARD_FLAG_BASE;
constexpr uint16_t V8_GMM2_COMBINE_CV_FREE_HARD_FLAG = V8_GMM2_COMBINE_CV_HARD_FLAG_BASE + 1;
constexpr uint16_t V8_GMM2_COMBINE_CV_HARD_FLAG_COUNT = 2;
constexpr uint16_t V8_MAX_BUSINESS_HARD_FLAG_ID = V8_GMM2_COMBINE_CV_FREE_HARD_FLAG;
constexpr uint8_t V8_GMM2_COMBINE_CV_DEFAULT_AIV_PER_AIC = 1;
constexpr uint8_t V8_GMM2_COMBINE_CV_MAX_AIV_PER_AIC = 2;
constexpr uint8_t V8_GMM2_COMBINE_CV_DEFAULT_FIFO_DEPTH = 1;
constexpr uint8_t V8_GMM2_COMBINE_CV_MAX_FIFO_DEPTH = 2;
constexpr uint32_t V8_GMM2_COMBINE_CV_TILE_M = 128;
constexpr uint32_t V8_GMM2_COMBINE_CV_TILE_N = 256;
constexpr uint32_t V8_GMM2_COMBINE_CV_ELEMENT_BYTES = 2;
constexpr uint32_t V8_GMM2_COMBINE_CV_SLOT_BYTES =
    V8_GMM2_COMBINE_CV_TILE_M * V8_GMM2_COMBINE_CV_TILE_N * V8_GMM2_COMBINE_CV_ELEMENT_BYTES;
constexpr uint32_t V8_GMM2_COMBINE_CV_SMALL_MAX_ELEMS = 8192;
constexpr uint32_t V8_GMM2_COMBINE_CV_SMALL_SCALE_ELEMS = 32;
constexpr uint32_t V8_GMM2_COMBINE_CV_SMALL_BUFFER_BYTES =
    V8_GMM2_COMBINE_CV_SMALL_MAX_ELEMS * V8_GMM2_COMBINE_CV_ELEMENT_BYTES +
    V8_GMM2_COMBINE_CV_SMALL_MAX_ELEMS * V8_GMM2_COMBINE_CV_ELEMENT_BYTES +
    V8_GMM2_COMBINE_CV_SMALL_MAX_ELEMS * sizeof(float) +
    V8_GMM2_COMBINE_CV_SMALL_SCALE_ELEMS * sizeof(float);
constexpr uint32_t V8_GMM2_COMBINE_CV_SLOT_OFFSET = 2 * V8_GMM2_COMBINE_CV_SMALL_BUFFER_BYTES;
constexpr uint32_t V8_GMM2_COMBINE_CV_TILE_SCALE_OFFSET =
    V8_GMM2_COMBINE_CV_SLOT_OFFSET + V8_GMM2_COMBINE_CV_SLOT_BYTES;
constexpr uint32_t V8_GMM2_COMBINE_CV_SCALE_CACHE_ELEMS = 4096;
constexpr uint32_t V8_GMM2_COMBINE_CV_TILE_SCALE_BYTES = V8_GMM2_COMBINE_CV_SCALE_CACHE_ELEMS * sizeof(float);
constexpr uint32_t V8_GMM2_COMBINE_CV_REQUIRED_UB_BYTES =
    V8_GMM2_COMBINE_CV_TILE_SCALE_OFFSET + V8_GMM2_COMBINE_CV_TILE_SCALE_BYTES;
constexpr uint16_t V5_GMM2_TO_COMBINE_HARD_FLAG_BASE = 0;
constexpr uint32_t V5_DISPATCH_V2C_MAX_LOGICAL_GROUP_EVENTS =
    V5_DISPATCH_V2C_HARD_FLAG_COUNT * CROSS_CORE_FLAG_MAX_SET_COUNT;
constexpr uint32_t V5_GMM2_TO_COMBINE_MAX_LOGICAL_GROUP_EVENTS =
    V5_DISPATCH_V2C_HARD_FLAG_COUNT * CROSS_CORE_FLAG_MAX_SET_COUNT;
static_assert(V5_DISPATCH_V2C_HARD_FLAG_BASE == 0U);
static_assert(V5_DISPATCH_V2C_HARD_FLAG_COUNT == 3U);
static_assert(V5_DISPATCH_V2C_HARD_FLAG_LAST == 2U);
static_assert(V5_C2V_HARD_FLAG_BASE == 3U);
static_assert(V5_V2C_HARD_FLAG_BASE == 4U);
static_assert(V5_DISPATCH_V2C_HARD_FLAG_LAST < V5_C2V_HARD_FLAG_BASE);
static_assert(V5_C2V_HARD_FLAG_BASE < V5_V2C_HARD_FLAG_BASE);
static_assert(V5_V2C_HARD_FLAG_BASE <= V5_MAX_BUSINESS_HARD_FLAG_ID);
static_assert(V8_GMM2_COMBINE_CV_READY_HARD_FLAG == 5U);
static_assert(V8_GMM2_COMBINE_CV_FREE_HARD_FLAG == 6U);
static_assert(V5_V2C_HARD_FLAG_BASE < V8_GMM2_COMBINE_CV_READY_HARD_FLAG);
static_assert(V8_GMM2_COMBINE_CV_READY_HARD_FLAG + 1U == V8_GMM2_COMBINE_CV_FREE_HARD_FLAG);
static_assert(V8_MAX_BUSINESS_HARD_FLAG_ID < 11U);
static_assert(V8_MAX_BUSINESS_HARD_FLAG_ID <= 15U);
static_assert(V8_GMM2_COMBINE_CV_DEFAULT_AIV_PER_AIC == 1U);
static_assert(V8_GMM2_COMBINE_CV_MAX_AIV_PER_AIC == 2U);
static_assert(V8_GMM2_COMBINE_CV_DEFAULT_FIFO_DEPTH == 1U);
static_assert(V8_GMM2_COMBINE_CV_MAX_FIFO_DEPTH == 2U);
static_assert(V8_GMM2_COMBINE_CV_SLOT_BYTES == 65536U);
static_assert(V8_GMM2_COMBINE_CV_SLOT_OFFSET == 131328U);

struct AtlasA5 {
    static constexpr uint32_t BIAS_SIZE = PTO_BIAS_SIZE_BYTES;
    static constexpr uint32_t FIXBUF_SIZE = PTO_FBUF_SIZE_BYTES;
    static constexpr uint32_t UB_SIZE = PTO_UBUF_SIZE_BYTES;
    static constexpr uint32_t L1_SIZE = PTO_CBUF_SIZE_BYTES;
    static constexpr uint32_t L0A_SIZE = PTO_L0A_SIZE_BYTES;
    static constexpr uint32_t L0B_SIZE = PTO_L0B_SIZE_BYTES;
    static constexpr uint32_t L0C_SIZE = PTO_L0C_SIZE_BYTES;
};
static_assert(V8_GMM2_COMBINE_CV_REQUIRED_UB_BYTES <= AtlasA5::UB_SIZE);

#endif // CONST_ARGS_HPP
