/**
Copyright (c) 2025 Huawei Technologies Co., Ltd.
This program is free software, you can redistribute it and/or modify it under the terms and conditions of
CANN Open Software License Agreement Version 2.0 (the "License").
Please refer to the License for details. You may not use this file except in compliance with the License.
THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
See LICENSE in the root of the software repository for the full text of the License.
*/
/**
 * Tile Performance Benchmark — Auto-generated by generate_code.py
 * Re-generate: python3 generate_code.py
 */
#include "test_common.h"
#include "acl/acl.h"
#include <gtest/gtest.h>
#include <cstring>

using namespace std;
using namespace PtoTestCommon;

class TilePerfTest : public testing::Test {};

// ===== Launcher forward declarations =====

template <typename T, int tileH, int tileW, int vRows, int vCols>
void launchTADD(void *out, void *src0, void *src1, aclrtStream stream);

template <typename T, int tileH, int tileW, int vRows, int vCols>
void launchTEXP(void *out, void *src, aclrtStream stream);

template <typename T, int tileH, int tileW, int vRows, int vCols>
void launchTADDS(void *out, void *src, float scalar, aclrtStream stream);

template <typename T, int tileH, int tileW, int vRows, int vCols>
void launchTROWSUM(void *out, void *src, aclrtStream stream);

template <typename T, int tileH, int tileW, int vRows, int vCols>
void launchTCOLSUM(void *out, void *src, aclrtStream stream);

template <typename T, int tileH, int tileW, int vRows, int vCols>
void launchTEXPANDS(void *out, float scalar, aclrtStream stream);

template <typename T, int tileH, int tileW, int vRows, int vCols>
void launchTROWEXPAND(void *out, void *src, aclrtStream stream);

template <typename T, int tileH, int tileW, int vRows, int vCols>
void launchTCOLEXPAND(void *out, void *src, aclrtStream stream);

// ========== Test macros ==========

#define BINARY_TEST(OP, DTYPE, NAME, H, W, ELEM, ACL_T) \
TEST_F(TilePerfTest, OP##_##DTYPE##_##NAME) { \
    size_t bytes = (ELEM) * sizeof(ACL_T); \
    aclInit(nullptr); aclrtSetDevice(0); \
    void *devOut, *devSrc0, *devSrc1; \
    aclrtMalloc(&devOut, bytes, ACL_MEM_MALLOC_HUGE_FIRST); \
    aclrtMalloc(&devSrc0, bytes, ACL_MEM_MALLOC_HUGE_FIRST); \
    aclrtMalloc(&devSrc1, bytes, ACL_MEM_MALLOC_HUGE_FIRST); \
    aclrtStream stream = nullptr; aclrtCreateStream(&stream); \
    launch##OP<ACL_T, H, W, H, W>(devOut, devSrc0, devSrc1, stream); \
    aclrtSynchronizeStream(stream); aclrtDestroyStream(stream); \
    aclrtFree(devOut); aclrtFree(devSrc0); aclrtFree(devSrc1); \
    aclrtResetDevice(0); aclFinalize(); \
}

#define UNARY_TEST(OP, DTYPE, NAME, H, W, ELEM, ACL_T) \
TEST_F(TilePerfTest, OP##_##DTYPE##_##NAME) { \
    size_t bytes = (ELEM) * sizeof(ACL_T); \
    aclInit(nullptr); aclrtSetDevice(0); \
    void *devOut, *devSrc; \
    aclrtMalloc(&devOut, bytes, ACL_MEM_MALLOC_HUGE_FIRST); \
    aclrtMalloc(&devSrc, bytes, ACL_MEM_MALLOC_HUGE_FIRST); \
    aclrtStream stream = nullptr; aclrtCreateStream(&stream); \
    launch##OP<ACL_T, H, W, H, W>(devOut, devSrc, stream); \
    aclrtSynchronizeStream(stream); aclrtDestroyStream(stream); \
    aclrtFree(devOut); aclrtFree(devSrc); \
    aclrtResetDevice(0); aclFinalize(); \
}

#define SCALAR_TEST(OP, DTYPE, NAME, H, W, ELEM, ACL_T, SCALAR) \
TEST_F(TilePerfTest, OP##_##DTYPE##_##NAME) { \
    size_t bytes = (ELEM) * sizeof(ACL_T); \
    aclInit(nullptr); aclrtSetDevice(0); \
    void *devOut, *devSrc; \
    aclrtMalloc(&devOut, bytes, ACL_MEM_MALLOC_HUGE_FIRST); \
    aclrtMalloc(&devSrc, bytes, ACL_MEM_MALLOC_HUGE_FIRST); \
    aclrtStream stream = nullptr; aclrtCreateStream(&stream); \
    launch##OP<ACL_T, H, W, H, W>(devOut, devSrc, SCALAR, stream); \
    aclrtSynchronizeStream(stream); aclrtDestroyStream(stream); \
    aclrtFree(devOut); aclrtFree(devSrc); \
    aclrtResetDevice(0); aclFinalize(); \
}

#define BROADCAST_SCALAR_TEST(OP, DTYPE, NAME, H, W, ELEM, ACL_T, SCALAR) \
TEST_F(TilePerfTest, OP##_##DTYPE##_##NAME) { \
    size_t bytes = (ELEM) * sizeof(ACL_T); \
    aclInit(nullptr); aclrtSetDevice(0); \
    void *devOut; \
    aclrtMalloc(&devOut, bytes, ACL_MEM_MALLOC_HUGE_FIRST); \
    aclrtStream stream = nullptr; aclrtCreateStream(&stream); \
    launch##OP<ACL_T, H, W, H, W>(devOut, SCALAR, stream); \
    aclrtSynchronizeStream(stream); aclrtDestroyStream(stream); \
    aclrtFree(devOut); \
    aclrtResetDevice(0); aclFinalize(); \
}

// ========== Test cases (auto-generated from input.csv) ==========

BINARY_TEST(TADD, float, 1x4096, 1, 4096, 4096, float)
BINARY_TEST(TADD, float, 16x256, 16, 256, 4096, float)
BINARY_TEST(TADD, float, 8x512, 8, 512, 4096, float)
BINARY_TEST(TADD, float, 1x8192, 1, 8192, 8192, float)
BINARY_TEST(TADD, float, 32x256, 32, 256, 8192, float)
BINARY_TEST(TADD, float, 16x512, 16, 512, 8192, float)
BINARY_TEST(TADD, float, 1x16384, 1, 16384, 16384, float)
BINARY_TEST(TADD, float, 64x256, 64, 256, 16384, float)
BINARY_TEST(TADD, float, 32x512, 32, 512, 16384, float)
BINARY_TEST(TADD, half, 1x8192, 1, 8192, 8192, aclFloat16)
BINARY_TEST(TADD, half, 32x256, 32, 256, 8192, aclFloat16)
BINARY_TEST(TADD, half, 16x512, 16, 512, 8192, aclFloat16)
BINARY_TEST(TADD, half, 1x16384, 1, 16384, 16384, aclFloat16)
BINARY_TEST(TADD, half, 64x256, 64, 256, 16384, aclFloat16)
BINARY_TEST(TADD, half, 32x512, 32, 512, 16384, aclFloat16)
BINARY_TEST(TADD, half, 1x32768, 1, 32768, 32768, aclFloat16)
BINARY_TEST(TADD, half, 128x256, 128, 256, 32768, aclFloat16)
BINARY_TEST(TADD, half, 64x512, 64, 512, 32768, aclFloat16)
UNARY_TEST(TEXP, float, 1x4096, 1, 4096, 4096, float)
UNARY_TEST(TEXP, float, 16x256, 16, 256, 4096, float)
UNARY_TEST(TEXP, float, 8x512, 8, 512, 4096, float)
UNARY_TEST(TEXP, float, 1x8192, 1, 8192, 8192, float)
UNARY_TEST(TEXP, float, 32x256, 32, 256, 8192, float)
UNARY_TEST(TEXP, float, 16x512, 16, 512, 8192, float)
UNARY_TEST(TEXP, float, 1x16384, 1, 16384, 16384, float)
UNARY_TEST(TEXP, float, 64x256, 64, 256, 16384, float)
UNARY_TEST(TEXP, float, 32x512, 32, 512, 16384, float)
UNARY_TEST(TEXP, half, 1x8192, 1, 8192, 8192, aclFloat16)
UNARY_TEST(TEXP, half, 32x256, 32, 256, 8192, aclFloat16)
UNARY_TEST(TEXP, half, 16x512, 16, 512, 8192, aclFloat16)
UNARY_TEST(TEXP, half, 1x16384, 1, 16384, 16384, aclFloat16)
UNARY_TEST(TEXP, half, 64x256, 64, 256, 16384, aclFloat16)
UNARY_TEST(TEXP, half, 32x512, 32, 512, 16384, aclFloat16)
UNARY_TEST(TEXP, half, 1x32768, 1, 32768, 32768, aclFloat16)
UNARY_TEST(TEXP, half, 128x256, 128, 256, 32768, aclFloat16)
UNARY_TEST(TEXP, half, 64x512, 64, 512, 32768, aclFloat16)
SCALAR_TEST(TADDS, float, 1x4096, 1, 4096, 4096, float, 1.5f)
SCALAR_TEST(TADDS, float, 16x256, 16, 256, 4096, float, 1.5f)
SCALAR_TEST(TADDS, float, 8x512, 8, 512, 4096, float, 1.5f)
SCALAR_TEST(TADDS, float, 1x8192, 1, 8192, 8192, float, 1.5f)
SCALAR_TEST(TADDS, float, 32x256, 32, 256, 8192, float, 1.5f)
SCALAR_TEST(TADDS, float, 16x512, 16, 512, 8192, float, 1.5f)
SCALAR_TEST(TADDS, float, 1x16384, 1, 16384, 16384, float, 1.5f)
SCALAR_TEST(TADDS, float, 64x256, 64, 256, 16384, float, 1.5f)
SCALAR_TEST(TADDS, float, 32x512, 32, 512, 16384, float, 1.5f)
SCALAR_TEST(TADDS, half, 1x8192, 1, 8192, 8192, aclFloat16, 1.5f)
SCALAR_TEST(TADDS, half, 32x256, 32, 256, 8192, aclFloat16, 1.5f)
SCALAR_TEST(TADDS, half, 16x512, 16, 512, 8192, aclFloat16, 1.5f)
SCALAR_TEST(TADDS, half, 1x16384, 1, 16384, 16384, aclFloat16, 1.5f)
SCALAR_TEST(TADDS, half, 64x256, 64, 256, 16384, aclFloat16, 1.5f)
SCALAR_TEST(TADDS, half, 32x512, 32, 512, 16384, aclFloat16, 1.5f)
SCALAR_TEST(TADDS, half, 1x32768, 1, 32768, 32768, aclFloat16, 1.5f)
SCALAR_TEST(TADDS, half, 128x256, 128, 256, 32768, aclFloat16, 1.5f)
SCALAR_TEST(TADDS, half, 64x512, 64, 512, 32768, aclFloat16, 1.5f)
UNARY_TEST(TROWSUM, float, 16x256, 16, 256, 4096, float)
UNARY_TEST(TROWSUM, float, 32x256, 32, 256, 8192, float)
UNARY_TEST(TROWSUM, float, 8x512, 8, 512, 4096, float)
UNARY_TEST(TROWSUM, float, 16x512, 16, 512, 8192, float)
UNARY_TEST(TROWSUM, float, 32x512, 32, 512, 16384, float)
UNARY_TEST(TROWSUM, float, 64x256, 64, 256, 16384, float)
UNARY_TEST(TROWSUM, half, 32x256, 32, 256, 8192, aclFloat16)
UNARY_TEST(TROWSUM, half, 64x256, 64, 256, 16384, aclFloat16)
UNARY_TEST(TROWSUM, half, 16x512, 16, 512, 8192, aclFloat16)
UNARY_TEST(TROWSUM, half, 32x512, 32, 512, 16384, aclFloat16)
UNARY_TEST(TROWSUM, half, 64x512, 64, 512, 32768, aclFloat16)
UNARY_TEST(TROWSUM, half, 128x256, 128, 256, 32768, aclFloat16)
UNARY_TEST(TCOLSUM, float, 16x256, 16, 256, 4096, float)
UNARY_TEST(TCOLSUM, float, 32x256, 32, 256, 8192, float)
UNARY_TEST(TCOLSUM, float, 8x512, 8, 512, 4096, float)
UNARY_TEST(TCOLSUM, float, 16x512, 16, 512, 8192, float)
UNARY_TEST(TCOLSUM, float, 32x512, 32, 512, 16384, float)
UNARY_TEST(TCOLSUM, float, 64x256, 64, 256, 16384, float)
UNARY_TEST(TCOLSUM, half, 32x256, 32, 256, 8192, aclFloat16)
UNARY_TEST(TCOLSUM, half, 64x256, 64, 256, 16384, aclFloat16)
UNARY_TEST(TCOLSUM, half, 16x512, 16, 512, 8192, aclFloat16)
UNARY_TEST(TCOLSUM, half, 32x512, 32, 512, 16384, aclFloat16)
UNARY_TEST(TCOLSUM, half, 64x512, 64, 512, 32768, aclFloat16)
UNARY_TEST(TCOLSUM, half, 128x256, 128, 256, 32768, aclFloat16)
BROADCAST_SCALAR_TEST(TEXPANDS, float, 1x4096, 1, 4096, 4096, float, 2.0f)
BROADCAST_SCALAR_TEST(TEXPANDS, float, 16x256, 16, 256, 4096, float, 2.0f)
BROADCAST_SCALAR_TEST(TEXPANDS, float, 32x256, 32, 256, 8192, float, 2.0f)
BROADCAST_SCALAR_TEST(TEXPANDS, float, 8x512, 8, 512, 4096, float, 2.0f)
BROADCAST_SCALAR_TEST(TEXPANDS, float, 16x512, 16, 512, 8192, float, 2.0f)
BROADCAST_SCALAR_TEST(TEXPANDS, float, 64x256, 64, 256, 16384, float, 2.0f)
BROADCAST_SCALAR_TEST(TEXPANDS, half, 1x8192, 1, 8192, 8192, aclFloat16, 2.0f)
BROADCAST_SCALAR_TEST(TEXPANDS, half, 32x256, 32, 256, 8192, aclFloat16, 2.0f)
BROADCAST_SCALAR_TEST(TEXPANDS, half, 64x256, 64, 256, 16384, aclFloat16, 2.0f)
BROADCAST_SCALAR_TEST(TEXPANDS, half, 16x512, 16, 512, 8192, aclFloat16, 2.0f)
BROADCAST_SCALAR_TEST(TEXPANDS, half, 32x512, 32, 512, 16384, aclFloat16, 2.0f)
BROADCAST_SCALAR_TEST(TEXPANDS, half, 128x256, 128, 256, 32768, aclFloat16, 2.0f)
UNARY_TEST(TROWEXPAND, float, 16x256, 16, 256, 4096, float)
UNARY_TEST(TROWEXPAND, float, 32x256, 32, 256, 8192, float)
UNARY_TEST(TROWEXPAND, float, 8x512, 8, 512, 4096, float)
UNARY_TEST(TROWEXPAND, float, 16x512, 16, 512, 8192, float)
UNARY_TEST(TROWEXPAND, float, 32x512, 32, 512, 16384, float)
UNARY_TEST(TROWEXPAND, float, 64x256, 64, 256, 16384, float)
UNARY_TEST(TROWEXPAND, half, 32x256, 32, 256, 8192, aclFloat16)
UNARY_TEST(TROWEXPAND, half, 64x256, 64, 256, 16384, aclFloat16)
UNARY_TEST(TROWEXPAND, half, 16x512, 16, 512, 8192, aclFloat16)
UNARY_TEST(TROWEXPAND, half, 32x512, 32, 512, 16384, aclFloat16)
UNARY_TEST(TROWEXPAND, half, 64x512, 64, 512, 32768, aclFloat16)
UNARY_TEST(TROWEXPAND, half, 128x256, 128, 256, 32768, aclFloat16)
UNARY_TEST(TCOLEXPAND, float, 16x256, 16, 256, 4096, float)
UNARY_TEST(TCOLEXPAND, float, 32x256, 32, 256, 8192, float)
UNARY_TEST(TCOLEXPAND, float, 8x512, 8, 512, 4096, float)
UNARY_TEST(TCOLEXPAND, float, 16x512, 16, 512, 8192, float)
UNARY_TEST(TCOLEXPAND, float, 32x512, 32, 512, 16384, float)
UNARY_TEST(TCOLEXPAND, float, 64x256, 64, 256, 16384, float)
UNARY_TEST(TCOLEXPAND, half, 32x256, 32, 256, 8192, aclFloat16)
UNARY_TEST(TCOLEXPAND, half, 64x256, 64, 256, 16384, aclFloat16)
UNARY_TEST(TCOLEXPAND, half, 16x512, 16, 512, 8192, aclFloat16)
UNARY_TEST(TCOLEXPAND, half, 32x512, 32, 512, 16384, aclFloat16)
UNARY_TEST(TCOLEXPAND, half, 64x512, 64, 512, 32768, aclFloat16)
UNARY_TEST(TCOLEXPAND, half, 128x256, 128, 256, 32768, aclFloat16)
