/**
Copyright (c) 2025 Huawei Technologies Co., Ltd.
This program is free software, you can redistribute it and/or modify it under the terms and conditions of
CANN Open Software License Agreement Version 2.0 (the "License").
Please refer to the License for details. You may not use this file except in compliance with the License.
THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
See LICENSE in the root of the software repository for the full text of the License.
*/
/**
 * Tile Performance Benchmark Kernel — Auto-generated by generate_code.py
 * Re-generate: python3 generate_code.py
 */
#include <pto/pto-inst.hpp>
#include <pto/common/constants.hpp>
#include <acl/acl.h>

using namespace pto;

// ===== Kernel forward declarations =====

template <typename T, int tileH, int tileW, int vRows, int vCols>
__global__ AICORE void runTROWSUM(__gm__ T *out, __gm__ T *src);

template <typename T, int tileH, int tileW, int vRows, int vCols>
__global__ AICORE void runTCOLSUM(__gm__ T *out, __gm__ T *src);

template <typename T, int tileH, int tileW, int vRows, int vCols>
__global__ AICORE void runTROWEXPAND(__gm__ T *out, __gm__ T *src);

template <typename T, int tileH, int tileW, int vRows, int vCols>
__global__ AICORE void runTCOLEXPAND(__gm__ T *out, __gm__ T *src);

// ===== Kernel specialisations =====

template <>
__global__ AICORE void runTROWSUM<float, 16, 256, 16, 256>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Source: full (H, W) — ND layout
    using SrcTileData = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1>;
    // Destination: (H, 1) — DN (ColMajor) layout to satisfy alignment
    using DstTileData = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1>;
    // Tmp: same shape as src (scratch buffer)
    using TmpTileData = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<float, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<float, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(16, 256), DynStride(16, 256));
    DstGlobal dstGlobal(out, DynShape(16, 1), DynStride(16, 1));
    SrcTileData srcTile(16, 256);
    DstTileData dstTile(16, 1);
    TmpTileData tmpTile(16, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWSUM(dstTile, srcTile, tmpTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWSUM<float, 8, 512, 8, 512>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Source: full (H, W) — ND layout
    using SrcTileData = Tile<TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1>;
    // Destination: (H, 1) — DN (ColMajor) layout to satisfy alignment
    using DstTileData = Tile<TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1>;
    // Tmp: same shape as src (scratch buffer)
    using TmpTileData = Tile<TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<float, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<float, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(8, 512), DynStride(8, 512));
    DstGlobal dstGlobal(out, DynShape(8, 1), DynStride(8, 1));
    SrcTileData srcTile(8, 512);
    DstTileData dstTile(8, 1);
    TmpTileData tmpTile(8, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWSUM(dstTile, srcTile, tmpTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWSUM<float, 32, 256, 32, 256>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Source: full (H, W) — ND layout
    using SrcTileData = Tile<TileType::Vec, float, 32, 256, BLayout::RowMajor, -1, -1>;
    // Destination: (H, 1) — DN (ColMajor) layout to satisfy alignment
    using DstTileData = Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, -1, -1>;
    // Tmp: same shape as src (scratch buffer)
    using TmpTileData = Tile<TileType::Vec, float, 32, 256, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<float, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<float, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(32, 256), DynStride(32, 256));
    DstGlobal dstGlobal(out, DynShape(32, 1), DynStride(32, 1));
    SrcTileData srcTile(32, 256);
    DstTileData dstTile(32, 1);
    TmpTileData tmpTile(32, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWSUM(dstTile, srcTile, tmpTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWSUM<float, 16, 512, 16, 512>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Source: full (H, W) — ND layout
    using SrcTileData = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1>;
    // Destination: (H, 1) — DN (ColMajor) layout to satisfy alignment
    using DstTileData = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1>;
    // Tmp: same shape as src (scratch buffer)
    using TmpTileData = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<float, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<float, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(16, 512), DynStride(16, 512));
    DstGlobal dstGlobal(out, DynShape(16, 1), DynStride(16, 1));
    SrcTileData srcTile(16, 512);
    DstTileData dstTile(16, 1);
    TmpTileData tmpTile(16, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWSUM(dstTile, srcTile, tmpTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWSUM<float, 8, 1024, 8, 1024>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Source: full (H, W) — ND layout
    using SrcTileData = Tile<TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1>;
    // Destination: (H, 1) — DN (ColMajor) layout to satisfy alignment
    using DstTileData = Tile<TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1>;
    // Tmp: same shape as src (scratch buffer)
    using TmpTileData = Tile<TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<float, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<float, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(8, 1024), DynStride(8, 1024));
    DstGlobal dstGlobal(out, DynShape(8, 1), DynStride(8, 1));
    SrcTileData srcTile(8, 1024);
    DstTileData dstTile(8, 1);
    TmpTileData tmpTile(8, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWSUM(dstTile, srcTile, tmpTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWSUM<float, 64, 256, 64, 256>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Source: full (H, W) — ND layout
    using SrcTileData = Tile<TileType::Vec, float, 64, 256, BLayout::RowMajor, -1, -1>;
    // Destination: (H, 1) — DN (ColMajor) layout to satisfy alignment
    using DstTileData = Tile<TileType::Vec, float, 64, 1, BLayout::ColMajor, -1, -1>;
    // Tmp: same shape as src (scratch buffer)
    using TmpTileData = Tile<TileType::Vec, float, 64, 256, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<float, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<float, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(64, 256), DynStride(64, 256));
    DstGlobal dstGlobal(out, DynShape(64, 1), DynStride(64, 1));
    SrcTileData srcTile(64, 256);
    DstTileData dstTile(64, 1);
    TmpTileData tmpTile(64, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWSUM(dstTile, srcTile, tmpTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWSUM<float, 32, 512, 32, 512>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Source: full (H, W) — ND layout
    using SrcTileData = Tile<TileType::Vec, float, 32, 512, BLayout::RowMajor, -1, -1>;
    // Destination: (H, 1) — DN (ColMajor) layout to satisfy alignment
    using DstTileData = Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, -1, -1>;
    // Tmp: same shape as src (scratch buffer)
    using TmpTileData = Tile<TileType::Vec, float, 32, 512, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<float, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<float, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(32, 512), DynStride(32, 512));
    DstGlobal dstGlobal(out, DynShape(32, 1), DynStride(32, 1));
    SrcTileData srcTile(32, 512);
    DstTileData dstTile(32, 1);
    TmpTileData tmpTile(32, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWSUM(dstTile, srcTile, tmpTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWSUM<float, 16, 1024, 16, 1024>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Source: full (H, W) — ND layout
    using SrcTileData = Tile<TileType::Vec, float, 16, 1024, BLayout::RowMajor, -1, -1>;
    // Destination: (H, 1) — DN (ColMajor) layout to satisfy alignment
    using DstTileData = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1>;
    // Tmp: same shape as src (scratch buffer)
    using TmpTileData = Tile<TileType::Vec, float, 16, 1024, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<float, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<float, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(16, 1024), DynStride(16, 1024));
    DstGlobal dstGlobal(out, DynShape(16, 1), DynStride(16, 1));
    SrcTileData srcTile(16, 1024);
    DstTileData dstTile(16, 1);
    TmpTileData tmpTile(16, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWSUM(dstTile, srcTile, tmpTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWSUM<half, 32, 256, 32, 256>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Source: full (H, W) — ND layout
    using SrcTileData = Tile<TileType::Vec, half, 32, 256, BLayout::RowMajor, -1, -1>;
    // Destination: (H, 1) — DN (ColMajor) layout to satisfy alignment
    using DstTileData = Tile<TileType::Vec, half, 32, 1, BLayout::ColMajor, -1, -1>;
    // Tmp: same shape as src (scratch buffer)
    using TmpTileData = Tile<TileType::Vec, half, 32, 256, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<half, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<half, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(32, 256), DynStride(32, 256));
    DstGlobal dstGlobal(out, DynShape(32, 1), DynStride(32, 1));
    SrcTileData srcTile(32, 256);
    DstTileData dstTile(32, 1);
    TmpTileData tmpTile(32, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWSUM(dstTile, srcTile, tmpTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWSUM<half, 16, 512, 16, 512>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Source: full (H, W) — ND layout
    using SrcTileData = Tile<TileType::Vec, half, 16, 512, BLayout::RowMajor, -1, -1>;
    // Destination: (H, 1) — DN (ColMajor) layout to satisfy alignment
    using DstTileData = Tile<TileType::Vec, half, 16, 1, BLayout::ColMajor, -1, -1>;
    // Tmp: same shape as src (scratch buffer)
    using TmpTileData = Tile<TileType::Vec, half, 16, 512, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<half, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<half, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(16, 512), DynStride(16, 512));
    DstGlobal dstGlobal(out, DynShape(16, 1), DynStride(16, 1));
    SrcTileData srcTile(16, 512);
    DstTileData dstTile(16, 1);
    TmpTileData tmpTile(16, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWSUM(dstTile, srcTile, tmpTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWSUM<half, 64, 256, 64, 256>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Source: full (H, W) — ND layout
    using SrcTileData = Tile<TileType::Vec, half, 64, 256, BLayout::RowMajor, -1, -1>;
    // Destination: (H, 1) — DN (ColMajor) layout to satisfy alignment
    using DstTileData = Tile<TileType::Vec, half, 64, 1, BLayout::ColMajor, -1, -1>;
    // Tmp: same shape as src (scratch buffer)
    using TmpTileData = Tile<TileType::Vec, half, 64, 256, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<half, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<half, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(64, 256), DynStride(64, 256));
    DstGlobal dstGlobal(out, DynShape(64, 1), DynStride(64, 1));
    SrcTileData srcTile(64, 256);
    DstTileData dstTile(64, 1);
    TmpTileData tmpTile(64, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWSUM(dstTile, srcTile, tmpTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWSUM<half, 32, 512, 32, 512>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Source: full (H, W) — ND layout
    using SrcTileData = Tile<TileType::Vec, half, 32, 512, BLayout::RowMajor, -1, -1>;
    // Destination: (H, 1) — DN (ColMajor) layout to satisfy alignment
    using DstTileData = Tile<TileType::Vec, half, 32, 1, BLayout::ColMajor, -1, -1>;
    // Tmp: same shape as src (scratch buffer)
    using TmpTileData = Tile<TileType::Vec, half, 32, 512, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<half, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<half, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(32, 512), DynStride(32, 512));
    DstGlobal dstGlobal(out, DynShape(32, 1), DynStride(32, 1));
    SrcTileData srcTile(32, 512);
    DstTileData dstTile(32, 1);
    TmpTileData tmpTile(32, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWSUM(dstTile, srcTile, tmpTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWSUM<half, 16, 1024, 16, 1024>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Source: full (H, W) — ND layout
    using SrcTileData = Tile<TileType::Vec, half, 16, 1024, BLayout::RowMajor, -1, -1>;
    // Destination: (H, 1) — DN (ColMajor) layout to satisfy alignment
    using DstTileData = Tile<TileType::Vec, half, 16, 1, BLayout::ColMajor, -1, -1>;
    // Tmp: same shape as src (scratch buffer)
    using TmpTileData = Tile<TileType::Vec, half, 16, 1024, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<half, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<half, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(16, 1024), DynStride(16, 1024));
    DstGlobal dstGlobal(out, DynShape(16, 1), DynStride(16, 1));
    SrcTileData srcTile(16, 1024);
    DstTileData dstTile(16, 1);
    TmpTileData tmpTile(16, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWSUM(dstTile, srcTile, tmpTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWSUM<half, 128, 256, 128, 256>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Source: full (H, W) — ND layout
    using SrcTileData = Tile<TileType::Vec, half, 128, 256, BLayout::RowMajor, -1, -1>;
    // Destination: (H, 1) — DN (ColMajor) layout to satisfy alignment
    using DstTileData = Tile<TileType::Vec, half, 128, 1, BLayout::ColMajor, -1, -1>;
    // Tmp: same shape as src (scratch buffer)
    using TmpTileData = Tile<TileType::Vec, half, 128, 256, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<half, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<half, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(128, 256), DynStride(128, 256));
    DstGlobal dstGlobal(out, DynShape(128, 1), DynStride(128, 1));
    SrcTileData srcTile(128, 256);
    DstTileData dstTile(128, 1);
    TmpTileData tmpTile(128, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWSUM(dstTile, srcTile, tmpTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWSUM<half, 64, 512, 64, 512>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Source: full (H, W) — ND layout
    using SrcTileData = Tile<TileType::Vec, half, 64, 512, BLayout::RowMajor, -1, -1>;
    // Destination: (H, 1) — DN (ColMajor) layout to satisfy alignment
    using DstTileData = Tile<TileType::Vec, half, 64, 1, BLayout::ColMajor, -1, -1>;
    // Tmp: same shape as src (scratch buffer)
    using TmpTileData = Tile<TileType::Vec, half, 64, 512, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<half, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<half, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(64, 512), DynStride(64, 512));
    DstGlobal dstGlobal(out, DynShape(64, 1), DynStride(64, 1));
    SrcTileData srcTile(64, 512);
    DstTileData dstTile(64, 1);
    TmpTileData tmpTile(64, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWSUM(dstTile, srcTile, tmpTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWSUM<half, 32, 1024, 32, 1024>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Source: full (H, W) — ND layout
    using SrcTileData = Tile<TileType::Vec, half, 32, 1024, BLayout::RowMajor, -1, -1>;
    // Destination: (H, 1) — DN (ColMajor) layout to satisfy alignment
    using DstTileData = Tile<TileType::Vec, half, 32, 1, BLayout::ColMajor, -1, -1>;
    // Tmp: same shape as src (scratch buffer)
    using TmpTileData = Tile<TileType::Vec, half, 32, 1024, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<half, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<half, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(32, 1024), DynStride(32, 1024));
    DstGlobal dstGlobal(out, DynShape(32, 1), DynStride(32, 1));
    SrcTileData srcTile(32, 1024);
    DstTileData dstTile(32, 1);
    TmpTileData tmpTile(32, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWSUM(dstTile, srcTile, tmpTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<float, 16, 256, 16, 256>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<float, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<float, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(16, 256), DynStride(16, 256));
    DstGlobal dstGlobal(out, DynShape(1, 256), DynStride(1, 256));
    SrcTileData srcTile(16, 256);
    DstTileData dstTile(1, 256);
    TmpTileData tmpTile(16, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<float, 8, 512, 8, 512>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<float, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<float, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(8, 512), DynStride(8, 512));
    DstGlobal dstGlobal(out, DynShape(1, 512), DynStride(1, 512));
    SrcTileData srcTile(8, 512);
    DstTileData dstTile(1, 512);
    TmpTileData tmpTile(8, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<float, 4, 1024, 4, 1024>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, float, 4, 1024, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, float, 1, 1024, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, float, 4, 1024, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<float, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<float, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(4, 1024), DynStride(4, 1024));
    DstGlobal dstGlobal(out, DynShape(1, 1024), DynStride(1, 1024));
    SrcTileData srcTile(4, 1024);
    DstTileData dstTile(1, 1024);
    TmpTileData tmpTile(4, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<float, 32, 256, 32, 256>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, float, 32, 256, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, float, 32, 256, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<float, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<float, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(32, 256), DynStride(32, 256));
    DstGlobal dstGlobal(out, DynShape(1, 256), DynStride(1, 256));
    SrcTileData srcTile(32, 256);
    DstTileData dstTile(1, 256);
    TmpTileData tmpTile(32, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<float, 16, 512, 16, 512>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<float, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<float, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(16, 512), DynStride(16, 512));
    DstGlobal dstGlobal(out, DynShape(1, 512), DynStride(1, 512));
    SrcTileData srcTile(16, 512);
    DstTileData dstTile(1, 512);
    TmpTileData tmpTile(16, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<float, 8, 1024, 8, 1024>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, float, 1, 1024, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<float, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<float, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(8, 1024), DynStride(8, 1024));
    DstGlobal dstGlobal(out, DynShape(1, 1024), DynStride(1, 1024));
    SrcTileData srcTile(8, 1024);
    DstTileData dstTile(1, 1024);
    TmpTileData tmpTile(8, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<float, 64, 256, 64, 256>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, float, 64, 256, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, float, 64, 256, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<float, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<float, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(64, 256), DynStride(64, 256));
    DstGlobal dstGlobal(out, DynShape(1, 256), DynStride(1, 256));
    SrcTileData srcTile(64, 256);
    DstTileData dstTile(1, 256);
    TmpTileData tmpTile(64, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<float, 32, 512, 32, 512>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, float, 32, 512, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, float, 32, 512, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<float, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<float, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(32, 512), DynStride(32, 512));
    DstGlobal dstGlobal(out, DynShape(1, 512), DynStride(1, 512));
    SrcTileData srcTile(32, 512);
    DstTileData dstTile(1, 512);
    TmpTileData tmpTile(32, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<float, 16, 1024, 16, 1024>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, float, 16, 1024, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, float, 1, 1024, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, float, 16, 1024, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<float, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<float, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(16, 1024), DynStride(16, 1024));
    DstGlobal dstGlobal(out, DynShape(1, 1024), DynStride(1, 1024));
    SrcTileData srcTile(16, 1024);
    DstTileData dstTile(1, 1024);
    TmpTileData tmpTile(16, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<half, 32, 256, 32, 256>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, half, 32, 256, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, half, 1, 256, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, half, 32, 256, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<half, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<half, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(32, 256), DynStride(32, 256));
    DstGlobal dstGlobal(out, DynShape(1, 256), DynStride(1, 256));
    SrcTileData srcTile(32, 256);
    DstTileData dstTile(1, 256);
    TmpTileData tmpTile(32, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<half, 16, 512, 16, 512>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, half, 16, 512, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, half, 1, 512, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, half, 16, 512, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<half, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<half, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(16, 512), DynStride(16, 512));
    DstGlobal dstGlobal(out, DynShape(1, 512), DynStride(1, 512));
    SrcTileData srcTile(16, 512);
    DstTileData dstTile(1, 512);
    TmpTileData tmpTile(16, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<half, 8, 1024, 8, 1024>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, half, 8, 1024, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, half, 1, 1024, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, half, 8, 1024, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<half, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<half, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(8, 1024), DynStride(8, 1024));
    DstGlobal dstGlobal(out, DynShape(1, 1024), DynStride(1, 1024));
    SrcTileData srcTile(8, 1024);
    DstTileData dstTile(1, 1024);
    TmpTileData tmpTile(8, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<half, 64, 256, 64, 256>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, half, 64, 256, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, half, 1, 256, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, half, 64, 256, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<half, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<half, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(64, 256), DynStride(64, 256));
    DstGlobal dstGlobal(out, DynShape(1, 256), DynStride(1, 256));
    SrcTileData srcTile(64, 256);
    DstTileData dstTile(1, 256);
    TmpTileData tmpTile(64, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<half, 32, 512, 32, 512>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, half, 32, 512, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, half, 1, 512, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, half, 32, 512, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<half, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<half, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(32, 512), DynStride(32, 512));
    DstGlobal dstGlobal(out, DynShape(1, 512), DynStride(1, 512));
    SrcTileData srcTile(32, 512);
    DstTileData dstTile(1, 512);
    TmpTileData tmpTile(32, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<half, 16, 1024, 16, 1024>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, half, 16, 1024, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, half, 1, 1024, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, half, 16, 1024, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<half, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<half, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(16, 1024), DynStride(16, 1024));
    DstGlobal dstGlobal(out, DynShape(1, 1024), DynStride(1, 1024));
    SrcTileData srcTile(16, 1024);
    DstTileData dstTile(1, 1024);
    TmpTileData tmpTile(16, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<half, 128, 256, 128, 256>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, half, 128, 256, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, half, 1, 256, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, half, 128, 256, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<half, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<half, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(128, 256), DynStride(128, 256));
    DstGlobal dstGlobal(out, DynShape(1, 256), DynStride(1, 256));
    SrcTileData srcTile(128, 256);
    DstTileData dstTile(1, 256);
    TmpTileData tmpTile(128, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<half, 64, 512, 64, 512>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, half, 64, 512, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, half, 1, 512, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, half, 64, 512, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<half, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<half, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(64, 512), DynStride(64, 512));
    DstGlobal dstGlobal(out, DynShape(1, 512), DynStride(1, 512));
    SrcTileData srcTile(64, 512);
    DstTileData dstTile(1, 512);
    TmpTileData tmpTile(64, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLSUM<half, 32, 1024, 32, 1024>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    using SrcTileData = Tile<TileType::Vec, half, 32, 1024, BLayout::RowMajor, -1, -1>;
    using DstTileData = Tile<TileType::Vec, half, 1, 1024, BLayout::RowMajor, -1, -1>;
    using TmpTileData = Tile<TileType::Vec, half, 32, 1024, BLayout::RowMajor, -1, -1>;

    using SrcGlobal = GlobalTensor<half, DynShape, DynStride>;
    using DstGlobal = GlobalTensor<half, DynShape, DynStride>;

    SrcGlobal srcGlobal(src, DynShape(32, 1024), DynStride(32, 1024));
    DstGlobal dstGlobal(out, DynShape(1, 1024), DynStride(1, 1024));
    SrcTileData srcTile(32, 1024);
    DstTileData dstTile(1, 1024);
    TmpTileData tmpTile(32, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(tmpTile, 0x100);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLSUM(dstTile, srcTile, tmpTile, false);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<float, 16, 256, 16, 256>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(16, 256), DynStride(16, 256));
    GlobalData dstGlobal(out, DynShape(16, 256), DynStride(16, 256));
    TileData srcTile(16, 256);
    TileData dstTile(16, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<float, 8, 512, 8, 512>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(8, 512), DynStride(8, 512));
    GlobalData dstGlobal(out, DynShape(8, 512), DynStride(8, 512));
    TileData srcTile(8, 512);
    TileData dstTile(8, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<float, 4, 1024, 4, 1024>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, float, 4, 1024, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(4, 1024), DynStride(4, 1024));
    GlobalData dstGlobal(out, DynShape(4, 1024), DynStride(4, 1024));
    TileData srcTile(4, 1024);
    TileData dstTile(4, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<float, 32, 256, 32, 256>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, float, 32, 256, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(32, 256), DynStride(32, 256));
    GlobalData dstGlobal(out, DynShape(32, 256), DynStride(32, 256));
    TileData srcTile(32, 256);
    TileData dstTile(32, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<float, 16, 512, 16, 512>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(16, 512), DynStride(16, 512));
    GlobalData dstGlobal(out, DynShape(16, 512), DynStride(16, 512));
    TileData srcTile(16, 512);
    TileData dstTile(16, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<float, 8, 1024, 8, 1024>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(8, 1024), DynStride(8, 1024));
    GlobalData dstGlobal(out, DynShape(8, 1024), DynStride(8, 1024));
    TileData srcTile(8, 1024);
    TileData dstTile(8, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<float, 64, 256, 64, 256>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, float, 64, 256, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(64, 256), DynStride(64, 256));
    GlobalData dstGlobal(out, DynShape(64, 256), DynStride(64, 256));
    TileData srcTile(64, 256);
    TileData dstTile(64, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<float, 32, 512, 32, 512>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, float, 32, 512, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(32, 512), DynStride(32, 512));
    GlobalData dstGlobal(out, DynShape(32, 512), DynStride(32, 512));
    TileData srcTile(32, 512);
    TileData dstTile(32, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<float, 16, 1024, 16, 1024>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, float, 16, 1024, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(16, 1024), DynStride(16, 1024));
    GlobalData dstGlobal(out, DynShape(16, 1024), DynStride(16, 1024));
    TileData srcTile(16, 1024);
    TileData dstTile(16, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<half, 32, 256, 32, 256>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, half, 32, 256, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(32, 256), DynStride(32, 256));
    GlobalData dstGlobal(out, DynShape(32, 256), DynStride(32, 256));
    TileData srcTile(32, 256);
    TileData dstTile(32, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<half, 16, 512, 16, 512>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, half, 16, 512, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(16, 512), DynStride(16, 512));
    GlobalData dstGlobal(out, DynShape(16, 512), DynStride(16, 512));
    TileData srcTile(16, 512);
    TileData dstTile(16, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<half, 8, 1024, 8, 1024>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, half, 8, 1024, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(8, 1024), DynStride(8, 1024));
    GlobalData dstGlobal(out, DynShape(8, 1024), DynStride(8, 1024));
    TileData srcTile(8, 1024);
    TileData dstTile(8, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<half, 64, 256, 64, 256>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, half, 64, 256, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(64, 256), DynStride(64, 256));
    GlobalData dstGlobal(out, DynShape(64, 256), DynStride(64, 256));
    TileData srcTile(64, 256);
    TileData dstTile(64, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<half, 32, 512, 32, 512>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, half, 32, 512, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(32, 512), DynStride(32, 512));
    GlobalData dstGlobal(out, DynShape(32, 512), DynStride(32, 512));
    TileData srcTile(32, 512);
    TileData dstTile(32, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<half, 16, 1024, 16, 1024>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, half, 16, 1024, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(16, 1024), DynStride(16, 1024));
    GlobalData dstGlobal(out, DynShape(16, 1024), DynStride(16, 1024));
    TileData srcTile(16, 1024);
    TileData dstTile(16, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<half, 128, 256, 128, 256>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, half, 128, 256, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(128, 256), DynStride(128, 256));
    GlobalData dstGlobal(out, DynShape(128, 256), DynStride(128, 256));
    TileData srcTile(128, 256);
    TileData dstTile(128, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<half, 64, 512, 64, 512>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, half, 64, 512, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(64, 512), DynStride(64, 512));
    GlobalData dstGlobal(out, DynShape(64, 512), DynStride(64, 512));
    TileData srcTile(64, 512);
    TileData dstTile(64, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTROWEXPAND<half, 32, 1024, 32, 1024>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads col0 from src, writes all cols of dst
    using TileData = Tile<TileType::Vec, half, 32, 1024, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(32, 1024), DynStride(32, 1024));
    GlobalData dstGlobal(out, DynShape(32, 1024), DynStride(32, 1024));
    TileData srcTile(32, 1024);
    TileData dstTile(32, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TROWEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<float, 16, 256, 16, 256>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(16, 256), DynStride(16, 256));
    GlobalData dstGlobal(out, DynShape(16, 256), DynStride(16, 256));
    TileData srcTile(16, 256);
    TileData dstTile(16, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<float, 8, 512, 8, 512>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(8, 512), DynStride(8, 512));
    GlobalData dstGlobal(out, DynShape(8, 512), DynStride(8, 512));
    TileData srcTile(8, 512);
    TileData dstTile(8, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<float, 4, 1024, 4, 1024>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, float, 4, 1024, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(4, 1024), DynStride(4, 1024));
    GlobalData dstGlobal(out, DynShape(4, 1024), DynStride(4, 1024));
    TileData srcTile(4, 1024);
    TileData dstTile(4, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<float, 32, 256, 32, 256>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, float, 32, 256, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(32, 256), DynStride(32, 256));
    GlobalData dstGlobal(out, DynShape(32, 256), DynStride(32, 256));
    TileData srcTile(32, 256);
    TileData dstTile(32, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<float, 16, 512, 16, 512>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(16, 512), DynStride(16, 512));
    GlobalData dstGlobal(out, DynShape(16, 512), DynStride(16, 512));
    TileData srcTile(16, 512);
    TileData dstTile(16, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<float, 8, 1024, 8, 1024>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(8, 1024), DynStride(8, 1024));
    GlobalData dstGlobal(out, DynShape(8, 1024), DynStride(8, 1024));
    TileData srcTile(8, 1024);
    TileData dstTile(8, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<float, 64, 256, 64, 256>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, float, 64, 256, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(64, 256), DynStride(64, 256));
    GlobalData dstGlobal(out, DynShape(64, 256), DynStride(64, 256));
    TileData srcTile(64, 256);
    TileData dstTile(64, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<float, 32, 512, 32, 512>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, float, 32, 512, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(32, 512), DynStride(32, 512));
    GlobalData dstGlobal(out, DynShape(32, 512), DynStride(32, 512));
    TileData srcTile(32, 512);
    TileData dstTile(32, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<float, 16, 1024, 16, 1024>(__gm__ float *out, __gm__ float *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, float, 16, 1024, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<float, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(16, 1024), DynStride(16, 1024));
    GlobalData dstGlobal(out, DynShape(16, 1024), DynStride(16, 1024));
    TileData srcTile(16, 1024);
    TileData dstTile(16, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<half, 32, 256, 32, 256>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, half, 32, 256, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(32, 256), DynStride(32, 256));
    GlobalData dstGlobal(out, DynShape(32, 256), DynStride(32, 256));
    TileData srcTile(32, 256);
    TileData dstTile(32, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<half, 16, 512, 16, 512>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, half, 16, 512, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(16, 512), DynStride(16, 512));
    GlobalData dstGlobal(out, DynShape(16, 512), DynStride(16, 512));
    TileData srcTile(16, 512);
    TileData dstTile(16, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<half, 8, 1024, 8, 1024>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, half, 8, 1024, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(8, 1024), DynStride(8, 1024));
    GlobalData dstGlobal(out, DynShape(8, 1024), DynStride(8, 1024));
    TileData srcTile(8, 1024);
    TileData dstTile(8, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<half, 64, 256, 64, 256>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, half, 64, 256, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(64, 256), DynStride(64, 256));
    GlobalData dstGlobal(out, DynShape(64, 256), DynStride(64, 256));
    TileData srcTile(64, 256);
    TileData dstTile(64, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<half, 32, 512, 32, 512>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, half, 32, 512, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(32, 512), DynStride(32, 512));
    GlobalData dstGlobal(out, DynShape(32, 512), DynStride(32, 512));
    TileData srcTile(32, 512);
    TileData dstTile(32, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<half, 16, 1024, 16, 1024>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, half, 16, 1024, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(16, 1024), DynStride(16, 1024));
    GlobalData dstGlobal(out, DynShape(16, 1024), DynStride(16, 1024));
    TileData srcTile(16, 1024);
    TileData dstTile(16, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<half, 128, 256, 128, 256>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, half, 128, 256, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(128, 256), DynStride(128, 256));
    GlobalData dstGlobal(out, DynShape(128, 256), DynStride(128, 256));
    TileData srcTile(128, 256);
    TileData dstTile(128, 256);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<half, 64, 512, 64, 512>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, half, 64, 512, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(64, 512), DynStride(64, 512));
    GlobalData dstGlobal(out, DynShape(64, 512), DynStride(64, 512));
    TileData srcTile(64, 512);
    TileData dstTile(64, 512);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

template <>
__global__ AICORE void runTCOLEXPAND<half, 32, 1024, 32, 1024>(__gm__ half *out, __gm__ half *src)
{
    using DynShape = Shape<1, 1, 1, -1, -1>;
    using DynStride = pto::Stride<1, 1, -1, -1, 1>;
    // Both src and dst are full (H, W) — op reads row0 from src, writes all rows of dst
    using TileData = Tile<TileType::Vec, half, 32, 1024, BLayout::RowMajor, -1, -1>;
    using GlobalData = GlobalTensor<half, DynShape, DynStride>;

    GlobalData srcGlobal(src, DynShape(32, 1024), DynStride(32, 1024));
    GlobalData dstGlobal(out, DynShape(32, 1024), DynStride(32, 1024));
    TileData srcTile(32, 1024);
    TileData dstTile(32, 1024);

    TASSIGN(srcTile, 0x0);
    TASSIGN(dstTile, 0x10000);

    for (int i = 0; i < 10; i++) {
        TLOAD(srcTile, srcGlobal);
        TCOLEXPAND(dstTile, srcTile);
        TSTORE(dstGlobal, dstTile);
        pipe_barrier(PIPE_ALL);
    }
}

// ===== Launcher wrappers =====

template <typename T, int tileH, int tileW, int vRows, int vCols>
void launchTROWSUM(void *out, void *src, aclrtStream stream)
{
    if constexpr (std::is_same_v<T, aclFloat16>)
        runTROWSUM<half, tileH, tileW, vRows, vCols><<<1, nullptr, stream>>>((half*)out, (half*)src);
    else
        runTROWSUM<T, tileH, tileW, vRows, vCols><<<1, nullptr, stream>>>((T*)out, (T*)src);
}

template <typename T, int tileH, int tileW, int vRows, int vCols>
void launchTCOLSUM(void *out, void *src, aclrtStream stream)
{
    if constexpr (std::is_same_v<T, aclFloat16>)
        runTCOLSUM<half, tileH, tileW, vRows, vCols><<<1, nullptr, stream>>>((half*)out, (half*)src);
    else
        runTCOLSUM<T, tileH, tileW, vRows, vCols><<<1, nullptr, stream>>>((T*)out, (T*)src);
}

template <typename T, int tileH, int tileW, int vRows, int vCols>
void launchTROWEXPAND(void *out, void *src, aclrtStream stream)
{
    if constexpr (std::is_same_v<T, aclFloat16>)
        runTROWEXPAND<half, tileH, tileW, vRows, vCols><<<1, nullptr, stream>>>((half*)out, (half*)src);
    else
        runTROWEXPAND<T, tileH, tileW, vRows, vCols><<<1, nullptr, stream>>>((T*)out, (T*)src);
}

template <typename T, int tileH, int tileW, int vRows, int vCols>
void launchTCOLEXPAND(void *out, void *src, aclrtStream stream)
{
    if constexpr (std::is_same_v<T, aclFloat16>)
        runTCOLEXPAND<half, tileH, tileW, vRows, vCols><<<1, nullptr, stream>>>((half*)out, (half*)src);
    else
        runTCOLEXPAND<T, tileH, tileW, vRows, vCols><<<1, nullptr, stream>>>((T*)out, (T*)src);
}

// ===== Explicit template instantiations =====

template void launchTROWSUM<float, 16, 256, 16, 256>(void*, void*, aclrtStream);
template void launchTROWSUM<float, 8, 512, 8, 512>(void*, void*, aclrtStream);
template void launchTROWSUM<float, 32, 256, 32, 256>(void*, void*, aclrtStream);
template void launchTROWSUM<float, 16, 512, 16, 512>(void*, void*, aclrtStream);
template void launchTROWSUM<float, 8, 1024, 8, 1024>(void*, void*, aclrtStream);
template void launchTROWSUM<float, 64, 256, 64, 256>(void*, void*, aclrtStream);
template void launchTROWSUM<float, 32, 512, 32, 512>(void*, void*, aclrtStream);
template void launchTROWSUM<float, 16, 1024, 16, 1024>(void*, void*, aclrtStream);
template void launchTROWSUM<aclFloat16, 32, 256, 32, 256>(void*, void*, aclrtStream);
template void launchTROWSUM<aclFloat16, 16, 512, 16, 512>(void*, void*, aclrtStream);
template void launchTROWSUM<aclFloat16, 64, 256, 64, 256>(void*, void*, aclrtStream);
template void launchTROWSUM<aclFloat16, 32, 512, 32, 512>(void*, void*, aclrtStream);
template void launchTROWSUM<aclFloat16, 16, 1024, 16, 1024>(void*, void*, aclrtStream);
template void launchTROWSUM<aclFloat16, 128, 256, 128, 256>(void*, void*, aclrtStream);
template void launchTROWSUM<aclFloat16, 64, 512, 64, 512>(void*, void*, aclrtStream);
template void launchTROWSUM<aclFloat16, 32, 1024, 32, 1024>(void*, void*, aclrtStream);
template void launchTCOLSUM<float, 16, 256, 16, 256>(void*, void*, aclrtStream);
template void launchTCOLSUM<float, 8, 512, 8, 512>(void*, void*, aclrtStream);
template void launchTCOLSUM<float, 4, 1024, 4, 1024>(void*, void*, aclrtStream);
template void launchTCOLSUM<float, 32, 256, 32, 256>(void*, void*, aclrtStream);
template void launchTCOLSUM<float, 16, 512, 16, 512>(void*, void*, aclrtStream);
template void launchTCOLSUM<float, 8, 1024, 8, 1024>(void*, void*, aclrtStream);
template void launchTCOLSUM<float, 64, 256, 64, 256>(void*, void*, aclrtStream);
template void launchTCOLSUM<float, 32, 512, 32, 512>(void*, void*, aclrtStream);
template void launchTCOLSUM<float, 16, 1024, 16, 1024>(void*, void*, aclrtStream);
template void launchTCOLSUM<aclFloat16, 32, 256, 32, 256>(void*, void*, aclrtStream);
template void launchTCOLSUM<aclFloat16, 16, 512, 16, 512>(void*, void*, aclrtStream);
template void launchTCOLSUM<aclFloat16, 8, 1024, 8, 1024>(void*, void*, aclrtStream);
template void launchTCOLSUM<aclFloat16, 64, 256, 64, 256>(void*, void*, aclrtStream);
template void launchTCOLSUM<aclFloat16, 32, 512, 32, 512>(void*, void*, aclrtStream);
template void launchTCOLSUM<aclFloat16, 16, 1024, 16, 1024>(void*, void*, aclrtStream);
template void launchTCOLSUM<aclFloat16, 128, 256, 128, 256>(void*, void*, aclrtStream);
template void launchTCOLSUM<aclFloat16, 64, 512, 64, 512>(void*, void*, aclrtStream);
template void launchTCOLSUM<aclFloat16, 32, 1024, 32, 1024>(void*, void*, aclrtStream);
template void launchTROWEXPAND<float, 16, 256, 16, 256>(void*, void*, aclrtStream);
template void launchTROWEXPAND<float, 8, 512, 8, 512>(void*, void*, aclrtStream);
template void launchTROWEXPAND<float, 4, 1024, 4, 1024>(void*, void*, aclrtStream);
template void launchTROWEXPAND<float, 32, 256, 32, 256>(void*, void*, aclrtStream);
template void launchTROWEXPAND<float, 16, 512, 16, 512>(void*, void*, aclrtStream);
template void launchTROWEXPAND<float, 8, 1024, 8, 1024>(void*, void*, aclrtStream);
template void launchTROWEXPAND<float, 64, 256, 64, 256>(void*, void*, aclrtStream);
template void launchTROWEXPAND<float, 32, 512, 32, 512>(void*, void*, aclrtStream);
template void launchTROWEXPAND<float, 16, 1024, 16, 1024>(void*, void*, aclrtStream);
template void launchTROWEXPAND<aclFloat16, 32, 256, 32, 256>(void*, void*, aclrtStream);
template void launchTROWEXPAND<aclFloat16, 16, 512, 16, 512>(void*, void*, aclrtStream);
template void launchTROWEXPAND<aclFloat16, 8, 1024, 8, 1024>(void*, void*, aclrtStream);
template void launchTROWEXPAND<aclFloat16, 64, 256, 64, 256>(void*, void*, aclrtStream);
template void launchTROWEXPAND<aclFloat16, 32, 512, 32, 512>(void*, void*, aclrtStream);
template void launchTROWEXPAND<aclFloat16, 16, 1024, 16, 1024>(void*, void*, aclrtStream);
template void launchTROWEXPAND<aclFloat16, 128, 256, 128, 256>(void*, void*, aclrtStream);
template void launchTROWEXPAND<aclFloat16, 64, 512, 64, 512>(void*, void*, aclrtStream);
template void launchTROWEXPAND<aclFloat16, 32, 1024, 32, 1024>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<float, 16, 256, 16, 256>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<float, 8, 512, 8, 512>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<float, 4, 1024, 4, 1024>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<float, 32, 256, 32, 256>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<float, 16, 512, 16, 512>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<float, 8, 1024, 8, 1024>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<float, 64, 256, 64, 256>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<float, 32, 512, 32, 512>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<float, 16, 1024, 16, 1024>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<aclFloat16, 32, 256, 32, 256>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<aclFloat16, 16, 512, 16, 512>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<aclFloat16, 8, 1024, 8, 1024>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<aclFloat16, 64, 256, 64, 256>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<aclFloat16, 32, 512, 32, 512>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<aclFloat16, 16, 1024, 16, 1024>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<aclFloat16, 128, 256, 128, 256>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<aclFloat16, 64, 512, 64, 512>(void*, void*, aclrtStream);
template void launchTCOLEXPAND<aclFloat16, 32, 1024, 32, 1024>(void*, void*, aclrtStream);
