/**
Copyright (c) 2025 Huawei Technologies Co., Ltd.
This program is free software, you can redistribute it and/or modify it under the terms and conditions of
CANN Open Software License Agreement Version 2.0 (the "License").
Please refer to the License for details. You may not use this file except in compliance with the License.
THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
See LICENSE in the root of the software repository for the full text of the License.
*/

#ifndef PTO_INSTR_IMPL_HPP
#define PTO_INSTR_IMPL_HPP

#include <pto/common/pto_tile.hpp>
#include <pto/common/type.hpp>
#include <pto/common/event.hpp>

#ifdef MEMORY_BASE
#include "pto/npu/a2a3/TAssign.hpp"
#include "pto/npu/a2a3/TSync.hpp"
#include "pto/npu/a2a3/TAdd.hpp"
#include "pto/npu/a2a3/TAnd.hpp"
#include "pto/npu/a2a3/TOr.hpp"
#include "pto/npu/a2a3/TXor.hpp"
#include "pto/npu/a2a3/TMins.hpp"
#include "pto/npu/a2a3/TAddS.hpp"
#include "pto/npu/a2a3/TSubS.hpp"
#include "pto/npu/a2a3/TRemS.hpp"
#include "pto/npu/a2a3/TDivS.hpp"
#include "pto/npu/a2a3/TMulS.hpp"
#include "pto/npu/a2a3/TSub.hpp"
#include "pto/npu/a2a3/TSels.hpp"
#include "pto/npu/a2a3/TMin.hpp"
#include "pto/npu/a2a3/TCmp.hpp"
#include "pto/npu/a2a3/TExpandS.hpp"
#include "pto/npu/a2a3/TMax.hpp"
#include "pto/npu/a2a3/TLoad.hpp"
#include "pto/npu/a2a3/TCvt.hpp"
#include "pto/npu/a2a3/TStore.hpp"
#include "pto/npu/a2a3/TTrans.hpp"
#include "pto/npu/a2a3/TReshape.hpp"
#include "pto/npu/a2a3/TRowSum.hpp"
#include "pto/npu/a2a3/TRowMax.hpp"
#include "pto/npu/a2a3/TRowMin.hpp"
#include "pto/npu/a2a3/TFillPad.hpp"
#include "pto/npu/a2a3/TColMax.hpp"
#include "pto/npu/a2a3/TMatmul.hpp"
#include "pto/npu/a2a3/TMrgSort.hpp"
#include "pto/npu/a2a3/TCmps.hpp"
#include "pto/npu/a2a3/TExtract.hpp"
#include "pto/npu/a2a3/TMov.hpp"
#include "pto/npu/a2a3/TMul.hpp"
#include "pto/npu/a2a3/TSort32.hpp"
#include "pto/npu/a2a3/TSel.hpp"
#include "pto/npu/a2a3/TGather.hpp"
#include "pto/npu/a2a3/TCvt.hpp"
#include "pto/npu/a2a3/TDiv.hpp"
#include "pto/npu/a2a3/TPartAdd.hpp"
#include "pto/npu/a2a3/TPartMax.hpp"
#include "pto/npu/a2a3/TPartMin.hpp"
#ifdef _DEBUG
#include "pto/npu/a2a3/TPrint.hpp"
#endif
#include "pto/npu/a2a3/TRowExpand.hpp"
#include "pto/npu/a2a3/TRowExpandAdd.hpp"
#include "pto/npu/a2a3/TRowExpandDiv.hpp"
#include "pto/npu/a2a3/TRowExpandMax.hpp"
#include "pto/npu/a2a3/TRowExpandMin.hpp"
#include "pto/npu/a2a3/TRowExpandMul.hpp"
#include "pto/npu/a2a3/TRowExpandSub.hpp"
#include "pto/npu/a2a3/TCI.hpp"
#include "pto/npu/a2a3/TMaxS.hpp"
#include "pto/npu/a2a3/TColSum.hpp"
#include "pto/npu/a2a3/TUnaryOp.hpp"
#include "pto/npu/a2a3/TBitwiseSOp.hpp"
#include "pto/npu/a2a3/TGatherB.hpp"
#include "pto/npu/a2a3/TColMin.hpp"
#include "pto/npu/a2a3/TScatter.hpp"
#include "pto/npu/a2a3/TColExpand.hpp"
#include "pto/npu/a2a3/TTri.hpp"
#include "pto/npu/a2a3/TLRelu.hpp"
#include "pto/npu/a2a3/TPrefetch.hpp"
#include "pto/npu/a2a3/TRem.hpp"
#include "pto/npu/a2a3/TInsert.hpp"
#endif

#ifdef REGISTER_BASE
#include "pto/npu/a5/TAssign.hpp"
#include "pto/npu/a5/TSync.hpp"
#include "pto/npu/a5/TAdd.hpp"
#include "pto/npu/a5/TAnd.hpp"
#include "pto/npu/a5/TAndS.hpp"
#include "pto/npu/a5/TOr.hpp"
#include "pto/npu/a5/TOrS.hpp"
#include "pto/npu/a5/TXor.hpp"
#include "pto/npu/a5/TXorS.hpp"
#include "pto/npu/a5/TShlS.hpp"
#include "pto/npu/a5/TShrS.hpp"
#include "pto/npu/a5/TAddS.hpp"
#include "pto/npu/a5/TSubS.hpp"
#include "pto/npu/a5/TDivS.hpp"
#include "pto/npu/a5/TMulS.hpp"
#include "pto/npu/a5/TSub.hpp"
#include "pto/npu/a5/TMin.hpp"
#include "pto/npu/a5/TMax.hpp"
#include "pto/npu/a5/TLoad.hpp"
#ifdef __DAV_VEC__
#include "pto/npu/a5/TCvt.hpp"
#endif
#include "pto/npu/a5/TStore.hpp"
#include "pto/npu/a5/TMrgSort.hpp"
#include "pto/npu/a5/TMatmul.hpp"
#include "pto/npu/a5/TCmps.hpp"
#include "pto/npu/a5/TCmp.hpp"
#include "pto/npu/a5/TColSum.hpp"
#include "pto/npu/a5/TColMax.hpp"
#include "pto/npu/a5/TColMin.hpp"
#include "pto/npu/a5/TColExpand.hpp"
#include "pto/npu/a5/TReshape.hpp"
#include "pto/npu/a5/TRowReduce.hpp"
#include "pto/npu/a5/TFillPad.hpp"
#include "pto/npu/a5/TTrans.hpp"
#include "pto/npu/a5/TLRelu.hpp"
#include "pto/npu/a5/Tci.hpp"
#include "pto/npu/a5/TSels.hpp"
#include "pto/npu/a5/TSel.hpp"
#include "pto/npu/a5/TExpandS.hpp"
#include "pto/npu/a5/TSort32.hpp"
#include "pto/npu/a5/TExtract.hpp"
#include "pto/npu/a5/TMins.hpp"
#include "pto/npu/a5/TMaxs.hpp"
#include "pto/npu/a5/TMov.hpp"
#include "pto/npu/a5/TRowExpand.hpp"
#include "pto/npu/a5/TRowExpandAdd.hpp"
#include "pto/npu/a5/TRowExpandDiv.hpp"
#include "pto/npu/a5/TRowExpandMax.hpp"
#include "pto/npu/a5/TRowExpandMin.hpp"
#include "pto/npu/a5/TRowExpandMul.hpp"
#include "pto/npu/a5/TRowExpandSub.hpp"
#include "pto/npu/a5/TRowExpandExpdif.hpp"
#include "pto/npu/a5/TPartAdd.hpp"
#include "pto/npu/a5/TPartMax.hpp"
#include "pto/npu/a5/TPartMin.hpp"
#ifdef _DEBUG
#include "pto/npu/a5/TPrint.hpp"
#endif
#include "pto/npu/a5/TGather.hpp"
#include "pto/npu/a5/TUnaryOp.hpp"
#include "pto/npu/a5/TGatherB.hpp"
#include "pto/npu/a5/TBinSOp.hpp"
#include "pto/npu/a5/TDiv.hpp"
#include "pto/npu/a5/TMul.hpp"
#include "pto/npu/a5/TScatter.hpp"
#include "pto/npu/a5/TColExpandDiv.hpp"
#include "pto/npu/a5/TColExpandMul.hpp"
#include "pto/npu/a5/TColExpandSub.hpp"
#include "pto/npu/a5/TColExpandExpdif.hpp"
#include "pto/npu/a5/TTri.hpp"
#include "pto/npu/a5/TPrefetch.hpp"
#include "pto/npu/a5/TInsert.hpp"
#endif

#ifdef __CPU_SIM
    #include "pto/cpu/ElementTileOp.h"
    #include "pto/cpu/ElementTileScalarOp.h"
    #include "pto/cpu/TBinSOps.hpp"
    #include "pto/cpu/TSub.hpp"
    #include "pto/cpu/TMul.hpp"
    #include "pto/cpu/TDiv.hpp"
    #include "pto/cpu/TCI.hpp"
    #include "pto/cpu/TMatmul.hpp"
    #include "pto/cpu/TAssign.hpp"
    #include "pto/cpu/TAdd.hpp"
    #include "pto/cpu/TAbs.hpp"
    #include "pto/cpu/TLoad.hpp"
    #include "pto/cpu/TStore.hpp"
    #include "pto/cpu/TExpands.hpp"
    #include "pto/cpu/TExp.hpp"
    #include "pto/cpu/TGather.hpp"
    #include "pto/cpu/TGatherB.hpp"
    #include "pto/cpu/TRowMax.hpp"
    #include "pto/cpu/TRowMin.hpp"
    #include "pto/cpu/TMrgSort.hpp"
    #include "pto/cpu/TMov.hpp"
    #include "pto/cpu/TExtract.hpp"
    #include "pto/cpu/TSqrt.hpp"
    #include "pto/cpu/TReshape.hpp"
    #include "pto/cpu/TRowSum.hpp"
    #include "pto/cpu/TMax.hpp"
    #include "pto/cpu/TExtract.hpp"
    #include "pto/cpu/TFillPad.hpp"
    #include "pto/cpu/TTrans.hpp"
    #include "pto/cpu/TSelS.hpp"
    #include "pto/cpu/TColSum.hpp"
    #include "pto/cpu/TColMax.hpp"
    #include "pto/cpu/TSel.hpp"
    #include "pto/cpu/TCmps.hpp"
    #include "pto/cpu/TGatherB.hpp"
    #include "pto/cpu/TSort32.hpp"
    #include "pto/cpu/TPartAdd.hpp"
    #include "pto/cpu/TPartMax.hpp"
    #include "pto/cpu/TPartMin.hpp"
    #include "pto/cpu/TRowExpand.hpp"
    #include "pto/cpu/TRSqrt.hpp"
    #include "pto/cpu/TCvt.hpp"
    #include "pto/cpu/TColMin.hpp"
    #include "pto/cpu/TColExpand.hpp"
    #include "pto/cpu/TScatter.hpp"
    #include "pto/cpu/TSort32.hpp"
    #include "pto/cpu/MGatherScatter.hpp"
#endif

#endif
