#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate DeepSeek-V4 MoE family case configuration. Emits a header
(`build/generated_cases.h`) and JSON manifest (`build/generated_cases.json`)
consumed by every leaf under `deepseekv4/MoE/`.

Case format: T,DIM,INTER_DIM,N_ROUTED,N_ACTIVATED,VOCAB

  T            token batch (sequence length flattened)
  DIM          model hidden dim          (ModelArgs.dim, default 4096)
  INTER_DIM    expert FFN intermediate   (ModelArgs.moe_inter_dim, default 4096)
  N_ROUTED     routed experts            (ModelArgs.n_routed_experts, default 8)
  N_ACTIVATED  experts per token         (ModelArgs.n_activated_experts, default 2)
  VOCAB        vocabulary size           (ModelArgs.vocab_size, default 129280;
                                          used by gate_hash_routing only)

Defaults:
  Realistic:        T=256, DIM=4096, INTER_DIM=4096, N_ROUTED=8,
                    N_ACTIVATED=2, VOCAB=129280
  Tiny prototype:   T=64,  DIM=128,  INTER_DIM=256,  N_ROUTED=8,
                    N_ACTIVATED=2, VOCAB=1024  (DEFAULT — keep fast)

Aliases emitted (prefixed `Dsmoe` to avoid clashing with the top-level
`MoE/` `kMoeT/H/F/E/TopK`):
  kDsmoeT, kDsmoeDim, kDsmoeInterDim, kDsmoeNRouted, kDsmoeNActivated, kDsmoeVocab

Macro emitted (forward-compat with multi-case binaries):
  DSMOE_FOR_EACH_CASE(MACRO)

Mirrors:
  - kernels/automode/a2a3/MoE/scripts/generate_cases.py (top-level MoE)
  - kernels/automode/a2a3/deepseekv4/CSA/scripts/generate_cases.py (same-depth)
"""
import argparse
import json
from pathlib import Path
from typing import List, Dict

# Tiny default — keeps the per-binary prototype small. Pass --cases for the
# realistic ModelArgs shape.
DEFAULT_CASES = [
    (64, 128, 256, 8, 2, 1024),
]


def _parse_case_entry(raw: str) -> Dict[str, int]:
    parts = [p.strip() for p in raw.split(',') if p.strip()]
    if len(parts) != 6:
        raise ValueError(
            f"Expected 6 comma-separated values "
            f"(T,DIM,INTER_DIM,N_ROUTED,N_ACTIVATED,VOCAB), got '{raw}'")
    t, dim, inter, n_routed, n_act, vocab = map(int, parts)
    if min(t, dim, inter, n_routed, n_act, vocab) <= 0:
        raise ValueError("All DSMoE case values must be positive")
    if n_act > n_routed:
        raise ValueError("N_ACTIVATED cannot exceed N_ROUTED")
    return {
        "t": t, "dim": dim, "inter_dim": inter,
        "n_routed": n_routed, "n_activated": n_act, "vocab": vocab,
    }


def _default_cases() -> List[Dict[str, int]]:
    return [
        {"t": t, "dim": d, "inter_dim": fi,
         "n_routed": nr, "n_activated": na, "vocab": v}
        for (t, d, fi, nr, na, v) in DEFAULT_CASES
    ]


def _case_name(c: Dict[str, int]) -> str:
    return (f"case_T{c['t']}_D{c['dim']}_I{c['inter_dim']}"
            f"_E{c['n_routed']}_K{c['n_activated']}_V{c['vocab']}")


def _render_macro(cases: List[Dict[str, int]]) -> str:
    lines = ["#define DSMOE_FOR_EACH_CASE(MACRO) \\"]
    for idx, c in enumerate(cases):
        suffix = " \\" if idx + 1 != len(cases) else ""
        line = (f"    MACRO({c['t']}, {c['dim']}, {c['inter_dim']}, "
                f"{c['n_routed']}, {c['n_activated']}, {c['vocab']}){suffix}")
        lines.append(line)
    return "\n".join(lines)


def _render_header(cases: List[Dict[str, int]]) -> str:
    macro_block = _render_macro(cases)
    array_entries = []
    for c in cases:
        array_entries.append("    {" + ", ".join([
            str(c["t"]), str(c["dim"]), str(c["inter_dim"]),
            str(c["n_routed"]), str(c["n_activated"]), str(c["vocab"]),
            f'"{_case_name(c)}"',
        ]) + "}")
    array_block = ",\n".join(array_entries)

    return f"""#pragma once
// Auto-generated by scripts/generate_cases.py. Do not edit manually.
// clang-format off
#include <cstddef>

{macro_block}

struct GeneratedDsmoeCase {{
    int t;
    int dim;
    int inter_dim;
    int n_routed;
    int n_activated;
    int vocab;
    const char *name;
}};

static constexpr GeneratedDsmoeCase kGeneratedDsmoeCases[] = {{
{array_block}
}};
static constexpr std::size_t kGeneratedDsmoeCasesCount =
    sizeof(kGeneratedDsmoeCases) / sizeof(kGeneratedDsmoeCases[0]);

// Convenience aliases — leaf binaries compile against the first case.
// Prefix `Dsmoe` keeps these distinct from the top-level MoE/'s `kMoeT/H/F/E/TopK`.
static constexpr int kDsmoeT           = kGeneratedDsmoeCases[0].t;
static constexpr int kDsmoeDim         = kGeneratedDsmoeCases[0].dim;
static constexpr int kDsmoeInterDim    = kGeneratedDsmoeCases[0].inter_dim;
static constexpr int kDsmoeNRouted     = kGeneratedDsmoeCases[0].n_routed;
static constexpr int kDsmoeNActivated  = kGeneratedDsmoeCases[0].n_activated;
static constexpr int kDsmoeVocab       = kGeneratedDsmoeCases[0].vocab;
static constexpr const char *kDsmoeCaseName = kGeneratedDsmoeCases[0].name;

// clang-format on
"""


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate DeepSeek-V4 MoE family case header/JSON")
    parser.add_argument(
        "--cases", action="append", default=None,
        help="Case entry: T,DIM,INTER_DIM,N_ROUTED,N_ACTIVATED,VOCAB")
    parser.add_argument(
        "--output-header",
        default=str((Path(__file__).resolve().parent.parent / "build" / "generated_cases.h")))
    parser.add_argument(
        "--output-json",
        default=str((Path(__file__).resolve().parent.parent / "build" / "generated_cases.json")))
    args = parser.parse_args()

    if args.cases:
        cases = [_parse_case_entry(entry) for entry in args.cases]
    else:
        cases = _default_cases()

    header_path = Path(args.output_header)
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(_render_header(cases))

    json_payload = [{"name": _case_name(c), **c} for c in cases]
    json_path = Path(args.output_json)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(json_payload, indent=2))

    print(f"[INFO] Wrote {header_path}")
    print(f"[INFO] Wrote {json_path}")
    for c in json_payload:
        print(f"  - {c['name']}")


if __name__ == "__main__":
    main()
