#!/usr/bin/env python3
# --------------------------------------------------------------------------------
# Author: ywangmu from HKUST
# Phase analysis: P (softmax) vs GU (global update) Vec workload estimation.
#
# Due to the deeply pipelined Vec core architecture (instructions are issued
# far ahead of execution, WAITs resolve asynchronously), we CANNOT use time
# windows to separate P and GU phases. Instead, we use OPCODE CLASSIFICATION
# based on the known macro structures:
#
# P (softmax_not_init) on [S0/2, S1] tile:
#   TROWMAX       -> VCMAX/VCGMAX   (P-unique)
#   TMAX          -> VMAX            (on [S0/2, 1], small)
#   TSUB          -> VSUB            (on [S0/2, 1], small)
#   TMULS x2      -> VMULS           (on [S0/2, 1], small)
#   TEXP x2       -> VEXP            (on [S0/2, 1] + [S0/2, S1])
#   TROWEXPANDSUB -> VDUP + VSUB     (on [S0/2, S1], large)
#   TMULS         -> VMULS           (on [S0/2, S1], large)
#   TROWSUM       -> VCADD/VCGADD   (P-unique)
#   TCVT          -> VCVT_F2F        (P-unique)
#   TMUL          -> VMUL            (on [S0/2, 1], small)
#   TADD          -> VADD            (on [S0/2, 1], small)
#   NZ scatter    -> VSSTB           (P-unique, for L1 insert)
#
# GU (pto_macro_fa_gu) on [S0/2, HEAD_SIZE] tile:
#   TROWEXPANDMUL -> VDUP + VMULS    (on [S0/2, HEAD_SIZE], large)
#   TADD          -> VADD            (on [S0/2, HEAD_SIZE], large)
#   (last tile additionally: TROWEXPANDDIV -> VDUP + VDIV, GU-unique)
#
# Classification:
#   P-unique (strict): VCMAX, VCGMAX, VCADD, VCGADD, VCVT_F2F, VSSTB, VSUB, VEXP, VMAX
#   GU-unique:         VDIV
#   Shared-heavy:      VDUP, VMULS, VADD, VMUL
#   Overhead:          VLD*, VST*, PLT, VMOV, scalar/control
#
# Notes:
# - VSUB/VEXP/VMAX are generated by softmax macros and are treated as P-side in
#   macro-strict accounting.
# - VMUL can come from softmax TMUL and/or GU row-expand lowering depending on
#   backend codegen; we keep it in shared-heavy for conservative splitting.
#
# For shared ops, we estimate the P:GU split using per-tile macro op counts.
# Per tile (P has 8 tiles, GU has 7 non-last + 1 last):
#   P shared [32,128] ops:  TROWEXPANDSUB (VDUP+VSUB) + TMULS + TEXP = 3 heavy ops
#   GU shared [32,128] ops: TROWEXPANDMUL (VDUP+VMULS) + TADD = 2 heavy ops
# Ratio for heavy shared: P:GU ≈ 3:2
#
# Usage:
#   python3 phase_analysis.py --csv timeline.csv
# --------------------------------------------------------------------------------

import argparse
import csv
from collections import Counter


def load_timeline(csv_path):
    rows = []
    with open(csv_path) as f:
        reader = csv.DictReader(f)
        for r in reader:
            r["ts_start"] = int(r["ts_start"])
            r["ts_end"] = int(r["ts_end"])
            r["duration"] = r["ts_end"] - r["ts_start"]
            rows.append(r)
    return rows


def main():
    parser = argparse.ArgumentParser(description="P vs GU phase analysis")
    parser.add_argument("--csv", required=True, help="timeline.csv path")
    parser.add_argument("--num-tiles", type=int, default=None,
                        help="Optional override for logical S1 tile count (P/GU iterations).")
    args = parser.parse_args()

    rows = load_timeline(args.csv)
    vec_rows = [r for r in rows if r["core"] == "vector"]
    cube_rows = [r for r in rows if r["core"] == "cube"]
    mmads = sorted(
        [r for r in cube_rows if "MMAD" in r["opcode"]], key=lambda r: r["ts_start"]
    )
    stores = sorted(
        [r for r in cube_rows if "FIX_L0C_TO_DST" in r["opcode"]],
        key=lambda r: r["ts_start"],
    )

    # Classify MMADs
    mmad_type = []
    for i in range(len(mmads)):
        gap = stores[i]["ts_start"] - mmads[i]["ts_end"] if i < len(stores) else 0
        mmad_type.append("pv_or_preload" if gap <= 100 else "qk")
    preload = 0
    for t in mmad_type:
        if t == "pv_or_preload":
            preload += 1
        else:
            break
    for i in range(preload):
        mmad_type[i] = "qk_preload"
    for i in range(preload, len(mmad_type)):
        if mmad_type[i] == "pv_or_preload":
            mmad_type[i] = "pv"

    pv_count = sum(1 for t in mmad_type if t == "pv")
    qk_count = sum(1 for t in mmad_type if t in ("qk", "qk_preload"))
    if args.num_tiles is not None and args.num_tiles > 0:
        # For fixed-shape comparisons, MMAD gap heuristic may drift under different
        # scheduling/stall patterns. Use explicit logical tile count to keep P/GU
        # accounting consistent across variants.
        pv_count = args.num_tiles
        qk_count = args.num_tiles

    print("=" * 80)
    print("P (SOFTMAX) vs GU (GLOBAL UPDATE) — OPCODE-BASED ANALYSIS")
    print("=" * 80)
    print(f"QK tiles: {qk_count}, PV tiles: {pv_count}")
    if args.num_tiles is not None and args.num_tiles > 0:
        print(f"(Tile count overridden by --num-tiles={args.num_tiles})")
    print(f"P iterations: {pv_count} (one per tile)")
    print(f"GU iterations: {pv_count} (tile 0 = no-op/copy, tiles 1-{pv_count-2} = gu, tile {pv_count-1} = gu_last)")
    print()

    # =========================================================================
    # Count all Vec compute opcodes
    # =========================================================================
    vec_compute = [r for r in vec_rows if r["op_class"] == "compute"]
    total_vec_icyc = sum(r["duration"] for r in vec_compute)
    total_vec_ops = len(vec_compute)

    opcode_icyc = Counter()
    opcode_count = Counter()
    for r in vec_compute:
        opcode_icyc[r["opcode"]] += r["duration"]
        opcode_count[r["opcode"]] += 1

    # P-unique opcodes (conservative subset)
    p_unique_opcodes = {"RV_VCMAX", "RV_VCGMAX", "RV_VCADD", "RV_VCGADD",
                        "RV_VCVT_F2F", "RV_VSSTB"}
    # P-only opcodes from macro structure (strict extension)
    p_macro_only_opcodes = {"RV_VSUB", "RV_VEXP", "RV_VMAX"}
    # GU-unique opcodes
    gu_unique_opcodes = {"RV_VDIV"}
    # Shared heavy opcodes (used by both P and GU on large tiles)
    shared_heavy_opcodes = {"RV_VDUP", "RV_VMULS", "RV_VADD", "RV_VMUL"}
    # Load/store/predicate (overhead, roughly proportional)
    overhead_opcodes = {"RV_VLDI", "RV_VSTI", "RV_VLD", "RV_VST", "RV_VLDA",
                        "RV_VLDUI", "RV_PLT", "RV_VMOV"}
    # Scalar/control (minimal)
    scalar_opcodes = {"RV_SMOV", "RV_SMOVK", "RV_SMOVI", "RV_SSHLI", "RV_SADD",
                      "RV_SADDI", "RV_SZEROEXT", "RV_VLOOP", "RV_SEND"}

    p_unique_icyc = sum(opcode_icyc.get(op, 0) for op in p_unique_opcodes)
    p_unique_ops = sum(opcode_count.get(op, 0) for op in p_unique_opcodes)
    p_macro_only_icyc = sum(opcode_icyc.get(op, 0) for op in p_macro_only_opcodes)
    p_macro_only_ops = sum(opcode_count.get(op, 0) for op in p_macro_only_opcodes)
    gu_unique_icyc = sum(opcode_icyc.get(op, 0) for op in gu_unique_opcodes)
    gu_unique_ops = sum(opcode_count.get(op, 0) for op in gu_unique_opcodes)
    shared_heavy_icyc = sum(opcode_icyc.get(op, 0) for op in shared_heavy_opcodes)
    shared_heavy_ops = sum(opcode_count.get(op, 0) for op in shared_heavy_opcodes)
    overhead_icyc = sum(opcode_icyc.get(op, 0) for op in overhead_opcodes)
    overhead_ops = sum(opcode_count.get(op, 0) for op in overhead_opcodes)
    scalar_icyc = sum(opcode_icyc.get(op, 0) for op in scalar_opcodes)

    other_icyc = total_vec_icyc - p_unique_icyc - gu_unique_icyc - shared_heavy_icyc - overhead_icyc - scalar_icyc

    # =========================================================================
    # Print full opcode breakdown
    # =========================================================================
    print("FULL VEC OPCODE BREAKDOWN:")
    print(f"  {'Opcode':25s} {'Count':>7s} {'Instr-cyc':>10s} {'Category':>12s}")
    print("  " + "-" * 60)
    for op in sorted(opcode_icyc, key=lambda x: -opcode_icyc[x]):
        cat = "P-unique" if op in p_unique_opcodes else \
              "P-macro-only" if op in p_macro_only_opcodes else \
              "GU-unique" if op in gu_unique_opcodes else \
              "shared-heavy" if op in shared_heavy_opcodes else \
              "overhead" if op in overhead_opcodes else \
              "scalar" if op in scalar_opcodes else "other"
        print(f"  {op:25s} {opcode_count[op]:7d} {opcode_icyc[op]:10d}   {cat}")

    print()
    print(f"  Total Vec compute:     {total_vec_ops:7d} ops, {total_vec_icyc:10d} instruction-cycles")

    # =========================================================================
    # Estimate P vs GU split
    # =========================================================================
    print()
    print("=" * 80)
    print("PHASE CLASSIFICATION")
    print("=" * 80)
    print(f"  P-unique  (VCMAX, VCADD, VCVT_F2F, VSSTB): {p_unique_icyc:8d} icyc ({100*p_unique_icyc/total_vec_icyc:.1f}%)")
    print(f"  P-macro-only (VSUB, VEXP, VMAX):            {p_macro_only_icyc:8d} icyc ({100*p_macro_only_icyc/total_vec_icyc:.1f}%)")
    print(f"  GU-unique (VDIV):                            {gu_unique_icyc:8d} icyc ({100*gu_unique_icyc/total_vec_icyc:.1f}%)")
    print(f"  Shared heavy (VDUP,VMULS,VADD,VMUL):         {shared_heavy_icyc:8d} icyc ({100*shared_heavy_icyc/total_vec_icyc:.1f}%)")
    print(f"  Overhead (VLD*,VST*,PLT,VMOV):               {overhead_icyc:8d} icyc ({100*overhead_icyc/total_vec_icyc:.1f}%)")
    print(f"  Scalar/control:                              {scalar_icyc:8d} icyc ({100*scalar_icyc/total_vec_icyc:.1f}%)")
    print(f"  Other:                                       {other_icyc:8d} icyc")

    # =========================================================================
    # Estimate shared split based on macro structure
    #
    # Softmax (not_init) PTO ops on [32, 128] fp32 tile:
    #   1. TROWMAX(input_x, tmp)           → VCMAX reduction (P-unique)
    #   2. TMAX(local_max, global_max)     → VMAX on [32,1] (small)
    #   3. TSUB(exp_max)                   → VSUB on [32,1] (small)
    #   4. TMULS(global_max copy)          → VMULS on [32,1] (small)
    #   5. TMULS(exp_max * scale)          → VMULS on [32,1] (small)
    #   6. TEXP(exp_max)                   → VEXP on [32,1] (small)
    #   7. TROWEXPANDSUB(p, input, max)    → VDUP+VSUB on [32,128] (LARGE)
    #   8. TMULS(p * scale)                → VMULS on [32,128] (LARGE)
    #   9. TEXP(p)                         → VEXP on [32,128] (LARGE)
    #  10. TROWSUM(p, tmp)                 → VCADD reduction (P-unique)
    #  11. TCVT(x_exp, p)                  → VCVT_F2F (P-unique)
    #  12. TMUL(exp_max * global_sum)      → VMUL on [32,1] (small)
    #  13. TADD(global_sum + local_sum)    → VADD on [32,1] (small)
    #
    # Softmax large-tile shared ops: VDUP+VSUB[32,128], VMULS[32,128], VEXP[32,128]
    #
    # GU (not last) PTO ops on [32, 128] fp32 tile:
    #   1. TROWEXPANDMUL(O, O, exp_max)   → VDUP+VMULS on [32,128] (LARGE)
    #   2. TADD(O, O, pv_tile)            → VADD on [32,128] (LARGE)
    #
    # GU last (additional):
    #   3. TROWEXPANDDIV(O, O, sum)       → VDUP+VDIV on [32,128] (LARGE, GU-unique VDIV)
    #
    # Per-tile heavy shared instruction counts (32 rows, 128/SIMD cols):
    # Assuming SIMD=8 fp32, 16 iterations per row:
    #   P per tile: VDUP(32) + VSUB(32*16) + VMULS(32*16) + VEXP(32*16)
    #               = 32 + 512 + 512 + 512 = 1568 ops
    #   + small ops: VMAX(4) + VSUB(4) + VMULS(8) + VEXP(4) + VMUL(4) + VADD(4) ≈ 28 ops
    #   P_shared_total ≈ 1596 ops per tile
    #
    #   GU per non-last tile: VDUP(32) + VMULS(32*16) + VADD(32*16)
    #                         = 32 + 512 + 512 = 1056 ops
    #   GU last tile: + VDUP(32) + VDIV(32*16) = +32+512 = 544 extra
    #
    # Over 8 P tiles (1 init + 7 not-init, but init has similar ops):
    #   P_shared ≈ 8 * 1596 = 12768 ops
    # Over 7 non-last + 1 last GU tiles (tile 0 = copy only):
    #   GU_shared ≈ 7 * 1056 + 544 = 7936 ops (tile 0 has 0 shared compute)
    #
    # P:GU shared ratio ≈ 12768 : 7936 ≈ 1.61 : 1
    # P share of shared ≈ 61.7%, GU share ≈ 38.3%
    # =========================================================================

    # Compute theoretical per-tile op counts
    # S0_half, S1, HEAD from run config: S0=64 → S0_half=32, S1=128, HEAD=128
    # We detect from the MMAD count:
    # The analysis uses relative ratios, so exact dims don't matter much.

    # Use the op count ratio to split shared ops
    # P_init softmax has fewer ops (no TMAX, TSUB, etc.) but has TROWMAX, TROWSUM, TCVT, TEXP
    # Approximately same heavy ops.

    n_p_tiles = pv_count  # 8
    n_gu_nontrivial = pv_count - 1  # 7 (tile 0 is copy/noop)
    n_gu_last = 1

    # Heavy shared ops per tile (in relative units):
    p_heavy_per_tile = 3.0  # TROWEXPANDSUB + TMULS + TEXP on [32,128]
    gu_heavy_per_tile = 2.0  # TROWEXPANDMUL + TADD on [32,128]
    gu_last_extra = 1.0  # TROWEXPANDDIV (but VDIV is GU-unique)

    total_p_heavy_units = n_p_tiles * p_heavy_per_tile
    total_gu_heavy_units = (n_gu_nontrivial - n_gu_last) * gu_heavy_per_tile + n_gu_last * (gu_heavy_per_tile + 0)  # VDIV counted separately

    p_share_of_shared = total_p_heavy_units / (total_p_heavy_units + total_gu_heavy_units)
    gu_share_of_shared = 1.0 - p_share_of_shared

    # Split shared+overhead proportionally
    distributable = shared_heavy_icyc + overhead_icyc + other_icyc
    p_from_shared = distributable * p_share_of_shared
    gu_from_shared = distributable * gu_share_of_shared

    # Conservative estimate: only P-unique subset is fixed to P
    total_p_est_cons = p_unique_icyc + p_from_shared
    total_gu_est_cons = gu_unique_icyc + gu_from_shared
    grand_total_cons = total_p_est_cons + total_gu_est_cons

    # Macro-strict estimate: add VSUB/VEXP/VMAX fully to P
    total_p_est_strict = p_unique_icyc + p_macro_only_icyc + p_from_shared
    total_gu_est_strict = gu_unique_icyc + gu_from_shared
    grand_total_strict = total_p_est_strict + total_gu_est_strict

    print()
    print("=" * 80)
    print("ESTIMATED P vs GU TOTAL INSTRUCTION-CYCLES")
    print("=" * 80)
    print(f"  P heavy units:  {n_p_tiles} tiles × {p_heavy_per_tile:.0f} = {total_p_heavy_units:.0f}")
    print(f"  GU heavy units: {n_gu_nontrivial} tiles × {gu_heavy_per_tile:.0f} = {total_gu_heavy_units:.0f}")
    print(f"  P share of shared ops: {100*p_share_of_shared:.1f}%")
    print(f"  GU share of shared ops: {100*gu_share_of_shared:.1f}%")
    print()
    print("  Conservative (lower-bound P share):")
    print(f"    P  = P-unique ({p_unique_icyc:d}) + shared_portion ({p_from_shared:.0f})")
    print(f"       = {total_p_est_cons:.0f} icyc ({100*total_p_est_cons/grand_total_cons:.1f}%)")
    print(f"    GU = GU-unique ({gu_unique_icyc:d}) + shared_portion ({gu_from_shared:.0f})")
    print(f"       = {total_gu_est_cons:.0f} icyc ({100*total_gu_est_cons/grand_total_cons:.1f}%)")
    print()
    print("  Macro-strict (VSUB/VEXP/VMAX assigned to P):")
    print(f"    P  = P-unique ({p_unique_icyc:d}) + P-macro-only ({p_macro_only_icyc:d}) + shared_portion ({p_from_shared:.0f})")
    print(f"       = {total_p_est_strict:.0f} icyc ({100*total_p_est_strict/grand_total_strict:.1f}%)")
    print(f"    GU = GU-unique ({gu_unique_icyc:d}) + shared_portion ({gu_from_shared:.0f})")
    print(f"       = {total_gu_est_strict:.0f} icyc ({100*total_gu_est_strict/grand_total_strict:.1f}%)")
    print()
    print(f"  P / GU ratio (conservative): {total_p_est_cons/total_gu_est_cons:.2f}x")
    print(f"  P / GU ratio (macro-strict): {total_p_est_strict/total_gu_est_strict:.2f}x")

    if total_p_est_cons > total_gu_est_cons:
        print()
        print("  >>> CONCLUSION: P (softmax) is the heavier Vec phase <<<")
        print(f"  >>> P accounts for ~{100*total_p_est_cons/grand_total_cons:.0f}% (conservative) to ~{100*total_p_est_strict/grand_total_strict:.0f}% (macro-strict) of Vec compute <<<")
    else:
        print()
        print("  >>> CONCLUSION: GU (global update) is the heavier Vec phase <<<")
        print(f"  >>> GU accounts for ~{100*total_gu_est_cons/grand_total_cons:.0f}% of Vec compute (conservative) <<<")

    # =========================================================================
    # Cross-check: P-unique ops should be proportional to P tile count
    # =========================================================================
    print()
    print("=" * 80)
    print("CROSS-CHECK")
    print("=" * 80)

    # VCMAX: appears in TROWMAX (1 per P tile)
    # VCADD: appears in TROWSUM (1 per P tile)
    # VCVT_F2F: appears in TCVT (1 per P tile)
    # VSSTB: appears in NZ scatter (1 per P tile for L1 insert)
    for op in sorted(p_unique_opcodes):
        cnt = opcode_count.get(op, 0)
        icyc = opcode_icyc.get(op, 0)
        per_tile = cnt / n_p_tiles if n_p_tiles > 0 else 0
        print(f"  {op:15s}: {cnt:5d} total, {per_tile:6.1f}/tile, {icyc:7d} icyc")

    print("  P-macro-only ops (expected from softmax macro):")
    for op in sorted(p_macro_only_opcodes):
        cnt = opcode_count.get(op, 0)
        icyc = opcode_icyc.get(op, 0)
        per_tile = cnt / n_p_tiles if n_p_tiles > 0 else 0
        print(f"  {op:15s}: {cnt:5d} total, {per_tile:6.1f}/tile, {icyc:7d} icyc")

    for op in sorted(gu_unique_opcodes):
        cnt = opcode_count.get(op, 0)
        icyc = opcode_icyc.get(op, 0)
        print(f"  {op:15s}: {cnt:5d} total, {icyc:7d} icyc (only in GU last tile)")

    # Key shared ops
    print()
    print("  Key shared ops:")
    for op in ["RV_VDUP", "RV_VMULS", "RV_VADD", "RV_VMUL"]:
        cnt = opcode_count.get(op, 0)
        icyc = opcode_icyc.get(op, 0)
        print(f"    {op:15s}: {cnt:5d} total, {icyc:7d} icyc")

    print()
    print("Done.")


if __name__ == "__main__":
    main()
