#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate quant family case configuration. Mirrors
kernels/automode/a2a3/deepseekv4/HCA/Compressor/scripts/generate_cases.py.

Case format: M,N,BLOCK_SIZE,INPLACE
  M           leading dim (token count)
  N           last dim (channel count, blocked)
  BLOCK_SIZE  block width over the last axis (FP8 default 128, FP4 default 32)
  INPLACE     0/1; the deepseek model calls inplace=True (kernel.py:97, 195)

Output: <quant>/build/generated_cases.{h,json}

Refs:
- kernel.py:41-102  (act_quant_kernel, FP8)
- kernel.py:128-200 (fp4_quant_kernel)
- model.py:373 (compressor non-rope dims call act_quant with block=64)
"""
import argparse
import json
from pathlib import Path
from typing import List, Dict

# Tiny prototype default per the scaffolding spec.
DEFAULT_CASES = [
    (32, 128, 128, 1),
]


def _parse_case_entry(raw: str) -> Dict[str, int]:
    parts = [p.strip() for p in raw.split(',') if p.strip()]
    if len(parts) != 4:
        raise ValueError(f"Expected 4 comma-separated values "
                         f"(M,N,BLOCK_SIZE,INPLACE), got '{raw}'")
    m, n, blk, inplace = map(int, parts)
    if min(m, n, blk) <= 0:
        raise ValueError("M, N, BLOCK_SIZE must be positive")
    if inplace not in (0, 1):
        raise ValueError("INPLACE must be 0 or 1")
    if n % blk != 0:
        print(f"[WARN] N={n} not multiple of BLOCK_SIZE={blk}; tail handling required")
    return {"m": m, "n": n, "block_size": blk, "inplace": inplace}


def _default_cases() -> List[Dict[str, int]]:
    return [{"m": m, "n": n, "block_size": blk, "inplace": inplace}
            for (m, n, blk, inplace) in DEFAULT_CASES]


def _case_name(c: Dict[str, int]) -> str:
    return (f"case_M{c['m']}_N{c['n']}_B{c['block_size']}_I{c['inplace']}")


def _render_macro(cases: List[Dict[str, int]]) -> str:
    lines = ["#define QUANT_FOR_EACH_CASE(MACRO) \\"]
    for idx, c in enumerate(cases):
        suffix = " \\" if idx + 1 != len(cases) else ""
        line = (f"    MACRO({c['m']}, {c['n']}, "
                f"{c['block_size']}, {c['inplace']}){suffix}")
        lines.append(line)
    return "\n".join(lines)


def _render_header(cases: List[Dict[str, int]]) -> str:
    macro_block = _render_macro(cases)
    array_entries = []
    for c in cases:
        array_entries.append("    {" + ", ".join([
            str(c["m"]), str(c["n"]),
            str(c["block_size"]), str(c["inplace"]),
            f'"{_case_name(c)}"',
        ]) + "}")
    array_block = ",\n".join(array_entries)

    return f"""#pragma once
// Auto-generated by scripts/generate_cases.py. Do not edit manually.
// clang-format off
#include <cstddef>

{macro_block}

struct GeneratedQuantCase {{
    int m;
    int n;
    int block_size;
    int inplace;
    const char *name;
}};

static constexpr GeneratedQuantCase kGeneratedQuantCases[] = {{
{array_block}
}};
static constexpr std::size_t kGeneratedQuantCasesCount =
    sizeof(kGeneratedQuantCases) / sizeof(kGeneratedQuantCases[0]);

// Convenience aliases — leaf binaries compile against the first case.
static constexpr int kQuantM         = kGeneratedQuantCases[0].m;
static constexpr int kQuantN         = kGeneratedQuantCases[0].n;
static constexpr int kQuantBlockSize = kGeneratedQuantCases[0].block_size;
static constexpr int kQuantInplace   = kGeneratedQuantCases[0].inplace;
static constexpr const char *kQuantCaseName = kGeneratedQuantCases[0].name;

// clang-format on
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate quant family case header/JSON")
    parser.add_argument("--cases", action="append", default=None,
                        help="Case entry: M,N,BLOCK_SIZE,INPLACE")
    parser.add_argument("--output-header",
                        default=str((Path(__file__).resolve().parent.parent / "build" / "generated_cases.h")))
    parser.add_argument("--output-json",
                        default=str((Path(__file__).resolve().parent.parent / "build" / "generated_cases.json")))
    args = parser.parse_args()

    if args.cases:
        cases = [_parse_case_entry(entry) for entry in args.cases]
    else:
        cases = _default_cases()

    header_path = Path(args.output_header)
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(_render_header(cases))

    json_payload = [{"name": _case_name(c), **c} for c in cases]
    json_path = Path(args.output_json)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(json_payload, indent=2))

    print(f"[INFO] Wrote {header_path}")
    print(f"[INFO] Wrote {json_path}")
    for c in json_payload:
        print(f"  - {c['name']}")


if __name__ == "__main__":
    main()
