#!/usr/bin/env python3
# coding=utf-8
# --------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# --------------------------------------------------------------------------------
"""Generate formula_params_generated.hpp from formula_params.csv."""

from __future__ import annotations

import csv
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
CSV_PATH = SCRIPT_DIR / "formula_params.csv"
OUT_PATH = SCRIPT_DIR / "formula_params_generated.hpp"
EXPECTED_HEADER = ["op", "dtype", "cols", "slope", "bias"]

DTYPE_MAP = {
    "fp32": "FormulaParamDType::Fp32",
    "fp16": "FormulaParamDType::Fp16",
    "any": "FormulaParamDType::Any",
}


def _validate_csv_header(fieldnames: list[str] | None) -> None:
    if fieldnames == EXPECTED_HEADER:
        return
    msg = f"Invalid header in {CSV_PATH}: {fieldnames}, expected {EXPECTED_HEADER}"
    raise ValueError(msg)


def _parse_csv_row(row: dict[str, str]) -> tuple[str, str, str, str, str]:
    op = row["op"].strip()
    dtype = row["dtype"].strip().lower()
    cols = row["cols"].strip()
    slope = row["slope"].strip()
    bias = row["bias"].strip()
    if dtype not in DTYPE_MAP:
        raise ValueError(f"Unsupported dtype '{dtype}' in {CSV_PATH}")
    if cols != "*":
        _ = int(cols)
    _ = float(slope)
    _ = float(bias)
    return op, dtype, cols, slope, bias


def _load_formula_rows() -> list[tuple[str, str, str, str, str]]:
    rows: list[tuple[str, str, str, str, str]] = []
    with CSV_PATH.open("r", encoding="utf-8", newline="") as file_obj:
        reader = csv.DictReader(file_obj)
        _validate_csv_header(reader.fieldnames)
        for row in reader:
            rows.append(_parse_csv_row(row))
    return rows


def _fmt_float(s: str) -> str:
    x = float(s)
    text = f"{x:.10f}".rstrip("0").rstrip(".")
    if "." not in text:
        text += ".0"
    return text


def _build_header_prefix(rows_count: int) -> list[str]:
    lines = [
        "/**",
        "Copyright (c) 2026 Huawei Technologies Co., Ltd.",
        "This program is free software, you can redistribute it and/or modify it under the terms and conditions of",
        "CANN Open Software License Agreement Version 2.0 (the \"License\").",
        "Please refer to the License for details. You may not use this file except in compliance with the License.",
        "THIS SOFTWARE IS PROVIDED ON AN \"AS IS\" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,",
        "INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.",
        "See LICENSE in the root of the software repository for the full text of the License.",
        "*/",
        "",
        "// Auto-generated by include/pto/costmodel/a2a3/formula_costmodel/gen_formula_params_header.py from",
        "// formula_params.csv.",
        "// Do not edit this file manually.",
        "",
        "#ifndef PTO_MOCKER_FORMULA_PARAMS_GENERATED_HPP",
        "#define PTO_MOCKER_FORMULA_PARAMS_GENERATED_HPP",
        "",
        "#include <array>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace pto::mocker::fit {",
        "",
        "enum class FormulaParamDType : uint8_t {",
        "    Fp32,",
        "    Fp16,",
        "    Any,",
        "};",
        "",
        "struct FormulaParamEntry {",
        "    std::string_view op;",
        "    FormulaParamDType dtype;",
        "    uint16_t cols;",
        "    double slope;",
        "    double bias;",
        "};",
        "",
        "inline constexpr uint16_t kFormulaAnyCols = 0;",
        "",
        "// NOLINTBEGIN(readability-magic-numbers)",
        f"inline constexpr std::array<FormulaParamEntry, {rows_count}> kFormulaParamTable = {{{{",
    ]
    return lines


def _append_table_entries(lines: list[str], rows: list[tuple[str, str, str, str, str]]) -> None:
    for op, dtype, cols, slope, bias in rows:
        cols_expr = "kFormulaAnyCols" if cols == "*" else cols
        slope_expr = _fmt_float(slope)
        bias_expr = _fmt_float(bias)
        lines.append(
            f'    FormulaParamEntry{{"{op}", {DTYPE_MAP[dtype]}, {cols_expr}, {slope_expr}, {bias_expr}}},'
        )


def _build_header_suffix() -> list[str]:
    return [
        "}};",
        "// NOLINTEND(readability-magic-numbers)",
        "",
        "} // namespace pto::mocker::fit",
        "",
        "#endif",
        "",
    ]


def _render_generated_header(rows: list[tuple[str, str, str, str, str]]) -> str:
    lines = _build_header_prefix(len(rows))
    _append_table_entries(lines, rows)
    lines.extend(_build_header_suffix())
    return "\n".join(lines)


def main() -> None:
    rows = _load_formula_rows()
    content = _render_generated_header(rows)
    OUT_PATH.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
