#!/usr/bin/env python3
"""Generate formula_params_generated.hpp from formula_params.csv."""

from __future__ import annotations

import csv
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
CSV_PATH = SCRIPT_DIR / "formula_params.csv"
OUT_PATH = SCRIPT_DIR / "formula_params_generated.hpp"

DTYPE_MAP = {
    "fp32": "FormulaParamDType::Fp32",
    "fp16": "FormulaParamDType::Fp16",
    "any": "FormulaParamDType::Any",
}


def _fmt_float(s: str) -> str:
    x = float(s)
    text = f"{x:.10f}".rstrip("0").rstrip(".")
    if "." not in text:
        text += ".0"
    return text


def main() -> None:
    rows: list[tuple[str, str, str, str, str]] = []
    with CSV_PATH.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        expected = ["op", "dtype", "cols", "slope", "bias"]
        if reader.fieldnames != expected:
            raise ValueError(f"Invalid header in {CSV_PATH}: {reader.fieldnames}, expected {expected}")
        for row in reader:
            op = row["op"].strip()
            dtype = row["dtype"].strip().lower()
            cols = row["cols"].strip()
            slope = row["slope"].strip()
            bias = row["bias"].strip()
            if dtype not in DTYPE_MAP:
                raise ValueError(f"Unsupported dtype '{dtype}' in {CSV_PATH}")
            if cols != "*":
                _ = int(cols)
            _ = float(slope)
            _ = float(bias)
            rows.append((op, dtype, cols, slope, bias))

    lines: list[str] = []
    lines.append("/**")
    lines.append("Copyright (c) 2026 Huawei Technologies Co., Ltd.")
    lines.append("This program is free software, you can redistribute it and/or modify it under the terms and conditions of")
    lines.append("CANN Open Software License Agreement Version 2.0 (the \"License\").")
    lines.append("Please refer to the License for details. You may not use this file except in compliance with the License.")
    lines.append("THIS SOFTWARE IS PROVIDED ON AN \"AS IS\" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,")
    lines.append("INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.")
    lines.append("See LICENSE in the root of the software repository for the full text of the License.")
    lines.append("*/")
    lines.append("")
    lines.append("// Auto-generated by include/pto/costmodel/a2a3/formula_costmodel/gen_formula_params_header.py from")
    lines.append("// formula_params.csv.")
    lines.append("// Do not edit this file manually.")
    lines.append("")
    lines.append("#ifndef PTO_MOCKER_FORMULA_PARAMS_GENERATED_HPP")
    lines.append("#define PTO_MOCKER_FORMULA_PARAMS_GENERATED_HPP")
    lines.append("")
    lines.append("#include <array>")
    lines.append("#include <cstdint>")
    lines.append("#include <string_view>")
    lines.append("")
    lines.append("namespace pto::mocker::fit {")
    lines.append("")
    lines.append("enum class FormulaParamDType : uint8_t {")
    lines.append("    Fp32,")
    lines.append("    Fp16,")
    lines.append("    Any,")
    lines.append("};")
    lines.append("")
    lines.append("struct FormulaParamEntry {")
    lines.append("    std::string_view op;")
    lines.append("    FormulaParamDType dtype;")
    lines.append("    uint16_t cols;")
    lines.append("    double slope;")
    lines.append("    double bias;")
    lines.append("};")
    lines.append("")
    lines.append("inline constexpr uint16_t kFormulaAnyCols = 0;")
    lines.append("")
    lines.append("// NOLINTBEGIN(readability-magic-numbers)")
    lines.append(f"inline constexpr std::array<FormulaParamEntry, {len(rows)}> kFormulaParamTable = {{{{")
    for op, dtype, cols, slope, bias in rows:
        cols_expr = "kFormulaAnyCols" if cols == "*" else cols
        slope_expr = _fmt_float(slope)
        bias_expr = _fmt_float(bias)
        lines.append(
            f'    FormulaParamEntry{{"{op}", {DTYPE_MAP[dtype]}, {cols_expr}, {slope_expr}, {bias_expr}}},'
        )
    lines.append("}};")
    lines.append("// NOLINTEND(readability-magic-numbers)")
    lines.append("")
    lines.append("} // namespace pto::mocker::fit")
    lines.append("")
    lines.append("#endif")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
