#!/usr/bin/env python3
# coding=utf-8

import argparse
import json
from pathlib import Path

DEFAULT_CASE = {
    "m": 6144,
    "k": 6144,
    "n": 6144,
    "single_core_m": 1536,
    "single_core_k": 6144,
    "single_core_n": 1024,
    "block_dim": 24,
    "base_m": 128,
    "base_k": 64,
    "base_n": 128,
    "step_m": 1,
    "step_ka": 4,
    "step_kb": 4,
    "step_n": 1,
}

FIELD_ORDER = [
    "m",
    "k",
    "n",
    "single_core_m",
    "single_core_k",
    "single_core_n",
    "block_dim",
    "base_m",
    "base_k",
    "base_n",
    "step_m",
    "step_ka",
    "step_kb",
    "step_n",
]


def parse_case(raw: str) -> dict:
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    if len(parts) not in (3, len(FIELD_ORDER)):
        raise ValueError(
            "Expected M,K,N or full "
            "M,K,N,SINGLE_CORE_M,SINGLE_CORE_K,SINGLE_CORE_N,BLOCK_DIM,BASE_M,BASE_K,BASE_N,STEP_M,STEP_KA,STEP_KB,STEP_N"
        )
    case = dict(DEFAULT_CASE)
    values = map(int, parts)
    for key, value in zip(FIELD_ORDER, values):
        case[key] = value
    if min(case.values()) <= 0:
        raise ValueError("All gemm case values must be positive")
    return case


def case_name(case: dict) -> str:
    return f"case_M{case['m']}_K{case['k']}_N{case['n']}"


def render_header(case: dict) -> str:
    return f"""#pragma once
// Auto-generated by scripts/generate_cases.py. Do not edit manually.
// clang-format off

static constexpr unsigned kGemmM = {case["m"]};
static constexpr unsigned kGemmK = {case["k"]};
static constexpr unsigned kGemmN = {case["n"]};
static constexpr unsigned kGemmSingleCoreM = {case["single_core_m"]};
static constexpr unsigned kGemmSingleCoreK = {case["single_core_k"]};
static constexpr unsigned kGemmSingleCoreN = {case["single_core_n"]};
static constexpr unsigned kGemmBlockDim = {case["block_dim"]};
static constexpr unsigned kGemmBaseM = {case["base_m"]};
static constexpr unsigned kGemmBaseK = {case["base_k"]};
static constexpr unsigned kGemmBaseN = {case["base_n"]};
static constexpr unsigned kGemmStepM = {case["step_m"]};
static constexpr unsigned kGemmStepKa = {case["step_ka"]};
static constexpr unsigned kGemmStepKb = {case["step_kb"]};
static constexpr unsigned kGemmStepN = {case["step_n"]};
static constexpr const char *kGemmCaseName = "{case_name(case)}";

// clang-format on
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate gemm case header/JSON")
    parser.add_argument("--cases", default=None, help="Single case: M,K,N or the full compile-time tuple")
    parser.add_argument(
        "--output-header",
        default=str(Path(__file__).resolve().parent.parent / "build" / "generated_cases.h"),
    )
    parser.add_argument(
        "--output-json",
        default=str(Path(__file__).resolve().parent.parent / "build" / "generated_cases.json"),
    )
    args = parser.parse_args()

    case = parse_case(args.cases) if args.cases else dict(DEFAULT_CASE)
    payload = {"name": case_name(case), **case}

    header_path = Path(args.output_header)
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(render_header(case))

    json_path = Path(args.output_json)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps([payload], indent=2))

    print(f"[INFO] Wrote {header_path}")
    print(f"[INFO] Wrote {json_path}")
    print(f"[INFO] Case: {payload}")


if __name__ == "__main__":
    main()
