/**
Copyright (c) 2025 Huawei Technologies Co., Ltd.
This program is free software, you can redistribute it and/or modify it under the terms and conditions of
CANN Open Software License Agreement Version 2.0 (the "License").
Please refer to the License for details. You may not use this file except in compliance with the License.
THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
See LICENSE in the root of the software repository for the full text of the License.
*/

#ifndef PTO_COSTMODEL_INSTR_BASIC_IMPL_HPP
#define PTO_COSTMODEL_INSTR_BASIC_IMPL_HPP

#include <utility>

namespace pto {

#define PTO_COSTMODEL_DEFINE_SIMPLE(API)                                  \
    template <typename... Args>                                           \
    PTO_INTERNAL void API##_IMPL(Args &&...args)                          \
    {                                                                     \
        ::pto::mocker::RecordPtoInstr(#API, std::forward<Args>(args)...); \
    }

#define PTO_COSTMODEL_DEFINE_A2A3(API)                                             \
    template <typename... Args>                                                    \
    PTO_INTERNAL void API##_IMPL(Args &&...args)                                   \
    {                                                                              \
        ::pto::mocker::PtoInstrScope scope(#API);                                  \
        PTO_COSTMODEL_A2A3_##API##_IMPL(std::forward<Args>(args)...);              \
        ::pto::mocker::RecordCompletedPtoInstr(#API, std::forward<Args>(args)...); \
    }

template <typename TileDataDst, typename TileDataSrc0, typename TileDataSrc1>
PTO_INTERNAL void TADD_IMPL(TileDataDst &dst, TileDataSrc0 &src0, TileDataSrc1 &src1)
{
    ::pto::mocker::PtoInstrScope scope("TADD");
    PTO_COSTMODEL_A2A3_TADD_IMPL(dst, src0, src1);
    ::pto::mocker::InjectTileCycles(dst);
    ::pto::mocker::RecordInstr("TADD", dst, src0, src1);
}

PTO_COSTMODEL_DEFINE_SIMPLE(TPAIRREDUCESUM)
PTO_COSTMODEL_DEFINE_SIMPLE(TSUBRELUCONV)
PTO_COSTMODEL_DEFINE_SIMPLE(TADDRELUCONV)
PTO_COSTMODEL_DEFINE_A2A3(TABS)
PTO_COSTMODEL_DEFINE_A2A3(TAND)
PTO_COSTMODEL_DEFINE_A2A3(TOR)
PTO_COSTMODEL_DEFINE_A2A3(TSUB)
PTO_COSTMODEL_DEFINE_A2A3(TSUBVIEW)
PTO_COSTMODEL_DEFINE_A2A3(TMUL)
PTO_COSTMODEL_DEFINE_A2A3(TMIN)
PTO_COSTMODEL_DEFINE_A2A3(TMAX)
PTO_COSTMODEL_DEFINE_A2A3(TEXPANDS)
PTO_COSTMODEL_DEFINE_A2A3(TLOAD)
PTO_COSTMODEL_DEFINE_A2A3(TPREFETCH)
PTO_COSTMODEL_DEFINE_A2A3(TCMPS)
PTO_COSTMODEL_DEFINE_A2A3(TCMP)
PTO_COSTMODEL_DEFINE_A2A3(TCONCAT)
PTO_COSTMODEL_DEFINE_A2A3(TDIV)
PTO_COSTMODEL_DEFINE_A2A3(TSHL)
PTO_COSTMODEL_DEFINE_A2A3(TSHR)
PTO_COSTMODEL_DEFINE_A2A3(TXOR)
PTO_COSTMODEL_DEFINE_A2A3(TLOG)
PTO_COSTMODEL_DEFINE_A2A3(TDIVS)
PTO_COSTMODEL_DEFINE_A2A3(TPRELU)
PTO_COSTMODEL_DEFINE_A2A3(TADDC)
PTO_COSTMODEL_DEFINE_A2A3(TSUBC)
PTO_COSTMODEL_DEFINE_SIMPLE(TGEMV_MX)
PTO_COSTMODEL_DEFINE_SIMPLE(TMATMUL_MX)
PTO_COSTMODEL_DEFINE_A2A3(TMATMUL)
PTO_COSTMODEL_DEFINE_A2A3(TMATMUL_ACC)
PTO_COSTMODEL_DEFINE_A2A3(TMATMUL_BIAS)
PTO_COSTMODEL_DEFINE_A2A3(TGEMV)
PTO_COSTMODEL_DEFINE_A2A3(TGEMV_ACC)
PTO_COSTMODEL_DEFINE_A2A3(TGEMV_BIAS)
PTO_COSTMODEL_DEFINE_A2A3(TMRGSORT)
PTO_COSTMODEL_DEFINE_A2A3(TEXTRACT)
PTO_COSTMODEL_DEFINE_A2A3(TIMG2COL)
PTO_COSTMODEL_DEFINE_A2A3(SETFMATRIX)
PTO_COSTMODEL_DEFINE_A2A3(SET_IMG2COL_RPT)
PTO_COSTMODEL_DEFINE_A2A3(SET_IMG2COL_PADDING)
PTO_COSTMODEL_DEFINE_A2A3(TINSERT)
PTO_COSTMODEL_DEFINE_SIMPLE(TFILLPAD_INPLACE)
PTO_COSTMODEL_DEFINE_SIMPLE(TFILLPAD_EXPAND)
PTO_COSTMODEL_DEFINE_A2A3(TSORT32)
PTO_COSTMODEL_DEFINE_A2A3(TGATHER)
PTO_COSTMODEL_DEFINE_A2A3(TCI)
PTO_COSTMODEL_DEFINE_A2A3(TTRI)
PTO_COSTMODEL_DEFINE_SIMPLE(TPARTADD)
PTO_COSTMODEL_DEFINE_SIMPLE(TPARTMUL)
PTO_COSTMODEL_DEFINE_SIMPLE(TPARTMAX)
PTO_COSTMODEL_DEFINE_SIMPLE(TPARTMIN)
PTO_COSTMODEL_DEFINE_SIMPLE(TPARTARGMAX)
PTO_COSTMODEL_DEFINE_SIMPLE(TPARTARGMIN)
PTO_COSTMODEL_DEFINE_SIMPLE(TFUSEDMULADD)
PTO_COSTMODEL_DEFINE_SIMPLE(TMULADDDST)
PTO_COSTMODEL_DEFINE_SIMPLE(TSUBRELU)
PTO_COSTMODEL_DEFINE_SIMPLE(TFUSEDMULADDRELU)
PTO_COSTMODEL_DEFINE_A2A3(TCVT)
PTO_COSTMODEL_DEFINE_A2A3(TMOV)
PTO_COSTMODEL_DEFINE_A2A3(TROWSUM)
PTO_COSTMODEL_DEFINE_SIMPLE(TROWPROD)
PTO_COSTMODEL_DEFINE_A2A3(TCOLSUM)
PTO_COSTMODEL_DEFINE_SIMPLE(TCOLPROD)
PTO_COSTMODEL_DEFINE_A2A3(TCOLMAX)
PTO_COSTMODEL_DEFINE_SIMPLE(TCOLARGMAX)
PTO_COSTMODEL_DEFINE_SIMPLE(TCOLARGMIN)
PTO_COSTMODEL_DEFINE_A2A3(TROWMAX)
PTO_COSTMODEL_DEFINE_SIMPLE(TROWARGMAX)
PTO_COSTMODEL_DEFINE_SIMPLE(TRESHAPE)
PTO_COSTMODEL_DEFINE_A2A3(TROWMIN)
PTO_COSTMODEL_DEFINE_SIMPLE(TROWARGMIN)
PTO_COSTMODEL_DEFINE_A2A3(TSELS)
PTO_COSTMODEL_DEFINE_A2A3(TSEL)
PTO_COSTMODEL_DEFINE_A2A3(TTRANS)
PTO_COSTMODEL_DEFINE_A2A3(TMINS)
PTO_COSTMODEL_DEFINE_A2A3(TROWEXPAND)
PTO_COSTMODEL_DEFINE_A2A3(TROWEXPANDDIV)
PTO_COSTMODEL_DEFINE_A2A3(TROWEXPANDMUL)
PTO_COSTMODEL_DEFINE_A2A3(TROWEXPANDSUB)
PTO_COSTMODEL_DEFINE_A2A3(TROWEXPANDADD)
PTO_COSTMODEL_DEFINE_A2A3(TROWEXPANDMAX)
PTO_COSTMODEL_DEFINE_A2A3(TROWEXPANDMIN)
PTO_COSTMODEL_DEFINE_A2A3(TROWEXPANDEXPDIF)
PTO_COSTMODEL_DEFINE_A2A3(TRSQRT)
PTO_COSTMODEL_DEFINE_A2A3(TSQRT)
PTO_COSTMODEL_DEFINE_A2A3(TEXP)
PTO_COSTMODEL_DEFINE_SIMPLE(TPOW)
PTO_COSTMODEL_DEFINE_SIMPLE(TPOWS)
PTO_COSTMODEL_DEFINE_A2A3(TNOT)
PTO_COSTMODEL_DEFINE_A2A3(TRELU)
PTO_COSTMODEL_DEFINE_A2A3(TGATHERB)
PTO_COSTMODEL_DEFINE_A2A3(TADDS)
PTO_COSTMODEL_DEFINE_A2A3(TAXPY)
PTO_COSTMODEL_DEFINE_A2A3(TSUBS)
PTO_COSTMODEL_DEFINE_A2A3(TMULS)
PTO_COSTMODEL_DEFINE_SIMPLE(TFMODS)
PTO_COSTMODEL_DEFINE_SIMPLE(TREMS)
PTO_COSTMODEL_DEFINE_A2A3(TMAXS)
PTO_COSTMODEL_DEFINE_SIMPLE(TANDS)
PTO_COSTMODEL_DEFINE_SIMPLE(TORS)
PTO_COSTMODEL_DEFINE_SIMPLE(TSHLS)
PTO_COSTMODEL_DEFINE_SIMPLE(TSHRS)
PTO_COSTMODEL_DEFINE_SIMPLE(TXORS)
PTO_COSTMODEL_DEFINE_A2A3(TLRELU)
PTO_COSTMODEL_DEFINE_SIMPLE(TADDSC)
PTO_COSTMODEL_DEFINE_SIMPLE(TSUBSC)
PTO_COSTMODEL_DEFINE_A2A3(TCOLMIN)
PTO_COSTMODEL_DEFINE_A2A3(TSCATTER)
PTO_COSTMODEL_DEFINE_A2A3(TCOLEXPAND)
PTO_COSTMODEL_DEFINE_SIMPLE(MGATHER)
PTO_COSTMODEL_DEFINE_SIMPLE(MSCATTER)
PTO_COSTMODEL_DEFINE_A2A3(TNEG)
PTO_COSTMODEL_DEFINE_A2A3(TCOLEXPANDDIV)
PTO_COSTMODEL_DEFINE_A2A3(TCOLEXPANDMUL)
PTO_COSTMODEL_DEFINE_A2A3(TCOLEXPANDADD)
PTO_COSTMODEL_DEFINE_A2A3(TCOLEXPANDMAX)
PTO_COSTMODEL_DEFINE_A2A3(TCOLEXPANDMIN)
PTO_COSTMODEL_DEFINE_A2A3(TCOLEXPANDSUB)
PTO_COSTMODEL_DEFINE_A2A3(TCOLEXPANDEXPDIF)
PTO_COSTMODEL_DEFINE_A2A3(TDEQUANT)
PTO_COSTMODEL_DEFINE_A2A3(TREM)
PTO_COSTMODEL_DEFINE_A2A3(TFMOD)
PTO_COSTMODEL_DEFINE_SIMPLE(THISTOGRAM)
PTO_COSTMODEL_DEFINE_SIMPLE(TQUANT)
PTO_COSTMODEL_DEFINE_SIMPLE(TINTERLEAVE)
PTO_COSTMODEL_DEFINE_SIMPLE(TDEINTERLEAVE)
PTO_COSTMODEL_DEFINE_SIMPLE(TGET_SCALE_ADDR)

#undef PTO_COSTMODEL_DEFINE_SIMPLE

#undef PTO_COSTMODEL_DEFINE_A2A3

} // namespace pto

#endif // PTO_COSTMODEL_INSTR_BASIC_IMPL_HPP
