#!/usr/bin/env python3
# coding=utf-8
# --------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# --------------------------------------------------------------------------------
"""Generate A5 VF formula_params_generated.hpp from formula_params.csv."""

from __future__ import annotations

import csv
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
CSV_PATH = SCRIPT_DIR / "formula_params.csv"
OUT_PATH = SCRIPT_DIR / "formula_params_generated.hpp"
EXPECTED_HEADER = [
    "op",
    "src_dtype",
    "dst_dtype",
    "shape_path",
    "vf_impl_kind",
    "tail_kind",
    "op_params",
    "formula_kind",
    "param0",
    "param1",
    "param2",
    "param3",
]

SHAPE_PATH_MAP = {
    "1d": "ShapePath::Path1D",
    "2d": "ShapePath::Path2D",
}

TAIL_KIND_MAP = {
    "full": "TailKind::Full",
    "tail": "TailKind::Tail",
}

FORMULA_KIND_MAP = {
    "linear": "FormulaKind::Linear",
    "linear_rows": "FormulaKind::LinearRows",
    "linear_tail": "FormulaKind::LinearTail",
    "nested_loop": "FormulaKind::NestedLoop",
}


def _validate_csv_header(fieldnames: list[str] | None) -> None:
    if fieldnames == EXPECTED_HEADER:
        return
    raise ValueError(f"Invalid header in {CSV_PATH}: {fieldnames}, expected {EXPECTED_HEADER}")


def _fmt_float(text: str) -> str:
    value = float(text)
    out = f"{value:.10f}".rstrip("0").rstrip(".")
    if "." not in out:
        out += ".0"
    return out


def _escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def _parse_row(row: dict[str, str]) -> tuple[str, str, str, str, str, str, str, str, str, str, str, str]:
    op = row["op"].strip()
    src_dtype = row["src_dtype"].strip()
    dst_dtype = row["dst_dtype"].strip()
    shape_path = row["shape_path"].strip().lower()
    vf_impl_kind = row["vf_impl_kind"].strip()
    tail_kind = row["tail_kind"].strip().lower()
    op_params = row["op_params"].strip()
    formula_kind = row["formula_kind"].strip().lower()
    if shape_path not in SHAPE_PATH_MAP:
        raise ValueError(f"Unsupported shape_path '{shape_path}' in {CSV_PATH}")
    if tail_kind not in TAIL_KIND_MAP:
        raise ValueError(f"Unsupported tail_kind '{tail_kind}' in {CSV_PATH}")
    if formula_kind not in FORMULA_KIND_MAP:
        raise ValueError(f"Unsupported formula_kind '{formula_kind}' in {CSV_PATH}")
    params = tuple(_fmt_float(row[f"param{i}"].strip()) for i in range(4))
    return (op, src_dtype, dst_dtype, shape_path, vf_impl_kind, tail_kind, op_params, formula_kind, *params)


def _load_rows() -> list[tuple[str, str, str, str, str, str, str, str, str, str, str, str]]:
    with CSV_PATH.open("r", encoding="utf-8", newline="") as file_obj:
        reader = csv.DictReader(file_obj)
        _validate_csv_header(reader.fieldnames)
        return [_parse_row(row) for row in reader]


def _render(rows: list[tuple[str, str, str, str, str, str, str, str, str, str, str, str]]) -> str:
    lines = [
        "/**",
        "Copyright (c) 2026 Huawei Technologies Co., Ltd.",
        "This program is free software, you can redistribute it and/or modify it under the terms and conditions of",
        "CANN Open Software License Agreement Version 2.0 (the \"License\").",
        "Please refer to the License for details. You may not use this file except in compliance with the License.",
        "THIS SOFTWARE IS PROVIDED ON AN \"AS IS\" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,",
        "INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.",
        "See LICENSE in the root of the software repository for the full text of the License.",
        "*/",
        "",
        "// Auto-generated by include/pto/costmodel/a5/formula_costmodel/gen_formula_params_header.py from",
        "// formula_params.csv.",
        "// Do not edit this file manually.",
        "",
        "#ifndef PTO_MOCKER_A5_FORMULA_PARAMS_GENERATED_HPP",
        "#define PTO_MOCKER_A5_FORMULA_PARAMS_GENERATED_HPP",
        "",
        "#include <array>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace pto::mocker::lightweight::a5::fit {",
        "",
        "enum class ShapePath : uint8_t",
        "{",
        "    Path1D,",
        "    Path2D,",
        "};",
        "",
        "enum class TailKind : uint8_t",
        "{",
        "    Full,",
        "    Tail,",
        "};",
        "",
        "enum class FormulaKind : uint8_t",
        "{",
        "    Linear,",
        "    LinearRows,",
        "    LinearTail,",
        "    NestedLoop,",
        "};",
        "",
        "struct VfFormulaParam {",
        "    std::string_view op;",
        "    std::string_view src_dtype;",
        "    std::string_view dst_dtype;",
        "    ShapePath shape_path;",
        "    std::string_view vf_impl_kind;",
        "    TailKind tail_kind;",
        "    std::string_view op_params;",
        "    FormulaKind formula_kind;",
        "    double param0;",
        "    double param1;",
        "    double param2;",
        "    double param3;",
        "};",
        "",
        "// NOLINTBEGIN(readability-magic-numbers)",
        f"inline constexpr std::array<VfFormulaParam, {len(rows)}> kVfFormulaParamTable = {{{{",
    ]
    for op, src_dtype, dst_dtype, shape, impl, tail, op_params, formula, p0, p1, p2, p3 in rows:
        lines.append(
            f'    {{"{_escape(op)}", "{_escape(src_dtype)}", "{_escape(dst_dtype)}", {SHAPE_PATH_MAP[shape]}, '
            f'"{_escape(impl)}", {TAIL_KIND_MAP[tail]}, "{_escape(op_params)}", '
            f'{FORMULA_KIND_MAP[formula]}, {p0}, {p1}, {p2}, {p3}}},'
        )
    lines.extend(
        [
            "}};",
            "// NOLINTEND(readability-magic-numbers)",
            "",
            "} // namespace pto::mocker::lightweight::a5::fit",
            "",
            "#endif",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    OUT_PATH.write_text(_render(_load_rows()), encoding="utf-8")


if __name__ == "__main__":
    main()
