#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate Indexer family case configuration. Mirrors
kernels/automode/a2a3/deepseekv4/HCA/Compressor/scripts/generate_cases.py.

Case format: B,S,T,DIM,Q_LORA_RANK,N_HEADS,HEAD_DIM,INDEX_TOPK
  B               batch size                  (ModelArgs.max_batch_size default 4)
  S               query sequence length       (ModelArgs.max_seq_len default 4096)
  T               kv-cache length             (varies at decode; tiny default 32)
  DIM             model hidden dim            (ModelArgs.dim default 4096)
  Q_LORA_RANK     query low-rank dim          (ModelArgs.q_lora_rank default 1024)
  N_HEADS         index n_heads               (ModelArgs.index_n_heads default 64)
  HEAD_DIM        index head dim              (ModelArgs.index_head_dim default 128)
  INDEX_TOPK      index topk                  (ModelArgs.index_topk default 512)

Output: <Indexer>/build/generated_cases.{h,json}

Refs:
- model.py:381-434 (Indexer module)
- model.py:412 (q = qr @ Wq_b.T)
- model.py:419 (weights = X @ W_wproj.T scaled)
- model.py:421-422 (index_score einsum + reduce)
"""
import argparse
import json
from pathlib import Path
from typing import List, Dict

# Tiny prototype default per the scaffolding spec. Realistic shape would be
# (1, 128, 128, 4096, 1024, 64, 128, 512) which is much larger.
DEFAULT_CASES = [
    (1, 64, 32, 128, 128, 8, 64, 16),
]


def _parse_case_entry(raw: str) -> Dict[str, int]:
    parts = [p.strip() for p in raw.split(',') if p.strip()]
    if len(parts) != 8:
        raise ValueError(f"Expected 8 comma-separated values "
                         f"(B,S,T,DIM,Q_LORA_RANK,N_HEADS,HEAD_DIM,INDEX_TOPK), "
                         f"got '{raw}'")
    b, s, t, dim, qlr, nh, hd, topk = map(int, parts)
    if min(b, s, t, dim, qlr, nh, hd, topk) <= 0:
        raise ValueError("All Indexer case dims must be positive")
    if topk > t:
        # Not fatal — allowed for diagnostic runs, but flag it.
        print(f"[WARN] INDEX_TOPK={topk} > T={t} (clamp expected at runtime)")
    return {"b": b, "s": s, "t": t, "dim": dim,
            "q_lora_rank": qlr, "n_heads": nh,
            "head_dim": hd, "index_topk": topk}


def _default_cases() -> List[Dict[str, int]]:
    return [{"b": b, "s": s, "t": t, "dim": dim,
             "q_lora_rank": qlr, "n_heads": nh,
             "head_dim": hd, "index_topk": topk}
            for (b, s, t, dim, qlr, nh, hd, topk) in DEFAULT_CASES]


def _case_name(c: Dict[str, int]) -> str:
    return (f"case_B{c['b']}_S{c['s']}_T{c['t']}_D{c['dim']}"
            f"_QLR{c['q_lora_rank']}_H{c['n_heads']}"
            f"_HD{c['head_dim']}_K{c['index_topk']}")


def _render_macro(cases: List[Dict[str, int]]) -> str:
    lines = ["#define INDEXER_FOR_EACH_CASE(MACRO) \\"]
    for idx, c in enumerate(cases):
        suffix = " \\" if idx + 1 != len(cases) else ""
        line = (f"    MACRO({c['b']}, {c['s']}, {c['t']}, {c['dim']}, "
                f"{c['q_lora_rank']}, {c['n_heads']}, "
                f"{c['head_dim']}, {c['index_topk']}){suffix}")
        lines.append(line)
    return "\n".join(lines)


def _render_header(cases: List[Dict[str, int]]) -> str:
    macro_block = _render_macro(cases)
    array_entries = []
    for c in cases:
        array_entries.append("    {" + ", ".join([
            str(c["b"]), str(c["s"]), str(c["t"]), str(c["dim"]),
            str(c["q_lora_rank"]), str(c["n_heads"]),
            str(c["head_dim"]), str(c["index_topk"]),
            f'"{_case_name(c)}"',
        ]) + "}")
    array_block = ",\n".join(array_entries)

    return f"""#pragma once
// Auto-generated by scripts/generate_cases.py. Do not edit manually.
// clang-format off
#include <cstddef>

{macro_block}

struct GeneratedIndexerCase {{
    int b;
    int s;
    int t;
    int dim;
    int q_lora_rank;
    int n_heads;
    int head_dim;
    int index_topk;
    const char *name;
}};

static constexpr GeneratedIndexerCase kGeneratedIndexerCases[] = {{
{array_block}
}};
static constexpr std::size_t kGeneratedIndexerCasesCount =
    sizeof(kGeneratedIndexerCases) / sizeof(kGeneratedIndexerCases[0]);

// Convenience aliases — leaf binaries compile against the first case.
static constexpr int kIdxB          = kGeneratedIndexerCases[0].b;
static constexpr int kIdxS          = kGeneratedIndexerCases[0].s;
static constexpr int kIdxT          = kGeneratedIndexerCases[0].t;
static constexpr int kIdxDim        = kGeneratedIndexerCases[0].dim;
static constexpr int kIdxQLoraRank  = kGeneratedIndexerCases[0].q_lora_rank;
static constexpr int kIdxNHeads     = kGeneratedIndexerCases[0].n_heads;
static constexpr int kIdxHeadDim    = kGeneratedIndexerCases[0].head_dim;
static constexpr int kIdxTopK       = kGeneratedIndexerCases[0].index_topk;
static constexpr const char *kIdxCaseName = kGeneratedIndexerCases[0].name;

// clang-format on
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Indexer family case header/JSON")
    parser.add_argument("--cases", action="append", default=None,
                        help="Case entry: B,S,T,DIM,Q_LORA_RANK,N_HEADS,HEAD_DIM,INDEX_TOPK")
    parser.add_argument("--output-header",
                        default=str((Path(__file__).resolve().parent.parent / "build" / "generated_cases.h")))
    parser.add_argument("--output-json",
                        default=str((Path(__file__).resolve().parent.parent / "build" / "generated_cases.json")))
    args = parser.parse_args()

    if args.cases:
        cases = [_parse_case_entry(entry) for entry in args.cases]
    else:
        cases = _default_cases()

    header_path = Path(args.output_header)
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(_render_header(cases))

    json_payload = [{"name": _case_name(c), **c} for c in cases]
    json_path = Path(args.output_json)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(json_payload, indent=2))

    print(f"[INFO] Wrote {header_path}")
    print(f"[INFO] Wrote {json_path}")
    for c in json_payload:
        print(f"  - {c['name']}")


if __name__ == "__main__":
    main()
