#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# --------------------------------------------------------------------------------
# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# --------------------------------------------------------------------------------

"""Generate the detailed TLOAD, TINSERT and TEXTRACT memory-layout diagrams.

Run from the repository root:
    python3 docs/tools/gen_memory_layout_svgs.py
    python3 docs/tools/gen_memory_layout_svgs.py --check
"""

from __future__ import annotations

import argparse
from html import escape
from pathlib import Path
from typing import Optional

from gen_isa_svg_core import CANVAS_W, DEFAULT_OUTPUT_DIR

PURPLE = "#6A47C4"
TEAL = "#087F8C"
BLOCK_COLORS = ["#EDE7FF", "#DDF4F2", "#FFF0DD", "#E8EDFF", "#F5E3F0"]


class MemoryLayoutFigure:
    def __init__(self, name: str, title: str, subtitle: str, height: int, description: str):
        self.name = name
        self.parts = [
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{CANVAS_W}" height="{height}" '
            f'viewBox="0 0 {CANVAS_W} {height}" role="img" aria-labelledby="title desc">',
            "<!-- Generated by docs/tools/gen_memory_layout_svgs.py. -->",
            f'<title id="title">{escape(title)}</title>',
            f'<desc id="desc">{escape(description)}</desc>',
            '<defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" '
            'orient="auto-start-reverse"><path d="M0,0 L8,4 L0,8 Z" fill="#64748b"/></marker></defs>',
            "<style>text { font-family: Arial, Helvetica, sans-serif; fill: #0f172a; } "
            ".title { font-size: 30px; font-weight: 700; } "
            ".heading { font-size: 21px; font-weight: 700; } .body { font-size: 18px; } "
            ".small { font-size: 16px; fill: #334155; } "
            ".mono { font-family: monospace; font-size: 18px; }</style>",
        ]
        self.add_rect(0, 0, CANVAS_W, height, "#FFFFFF", "none", 0)
        self.add_text(36, 46, title, "title")
        self.add_text(36, 80, subtitle)

    def add_rect(
        self,
        x: float,
        y: float,
        width: float,
        height: float,
        fill: str = "#F8FAFC",
        stroke: str = "#CBD5E1",
        radius: int = 10,
    ) -> None:
        self.parts.append(
            f'<rect x="{x}" y="{y}" width="{width}" height="{height}" rx="{radius}" '
            f'fill="{fill}" stroke="{stroke}" stroke-width="1.5"/>'
        )

    def add_text(self, x: float, y: float, text: str, css_class: str = "body", anchor: str = "start") -> None:
        self.parts.append(f'<text x="{x}" y="{y}" class="{css_class}" text-anchor="{anchor}">{escape(text)}</text>')

    def add_line(
        self,
        x1: float,
        y1: float,
        x2: float,
        y2: float,
        arrow_end: bool = False,
        arrow_start: bool = False,
        color: str = "#64748b",
        dash: Optional[str] = None,
    ) -> None:
        attributes = ' marker-end="url(#arrow)"' if arrow_end else ""
        if arrow_start:
            attributes += ' marker-start="url(#arrow)"'
        if dash:
            attributes += f' stroke-dasharray="{dash}"'
        self.parts.append(
            f'<path d="M{x1},{y1} L{x2},{y2}" fill="none" stroke="{color}" stroke-width="2"{attributes}/>'
        )

    def render(self) -> str:
        return "\n".join([*self.parts, "</svg>"]) + "\n"


def _render_tload_stride_fallback() -> MemoryLayoutFigure:
    figure = MemoryLayoutFigure(
        "TLOAD_STRIDE_FALLBACK",
        "TLOAD: gap, stride and per-burst fallback",
        "Shared register DMA helper: A5/A6 and Kirin9030/KirinDev0000 callers. Addresses are in bytes.",
        760,
        "Stride measures start to start; gap measures end to next start. The register helper uses one "
        "multi-burst DMA up to 2^40 minus 1 bytes, and one DMA per burst above that boundary. All address "
        "offsets retain 64-bit precision.",
    )
    figure.add_rect(36, 108, 1128, 236)
    figure.add_text(58, 142, "1. Source addresses (schematic, not to scale)", "heading")
    for i, x in enumerate([100, 450, 800]):
        figure.add_rect(x, 208, 180, 50, BLOCK_COLORS[i], PURPLE, 3)
        figure.add_text(x + 90, 240, f"burst {i}: L bytes", anchor="middle")
        figure.add_text(x, 283, ["src", "src + S", "src + 2S"][i], "mono")
    figure.add_line(100, 183, 450, 183, True, True)
    figure.add_text(275, 172, "stride S", anchor="middle")
    figure.add_line(280, 230, 450, 230, True, True)
    figure.add_text(365, 215, "gap G", "small", "middle")
    figure.add_text(58, 322, "S = L + G      |      src(i) = src + i × S      |      dst(i) = dst + i × D", "mono")
    figure.add_rect(36, 366, 548, 316, "#F0EDFF")
    figure.add_rect(608, 366, 556, 316, "#F0FAF8")
    figure.add_text(58, 402, "2a. S ≤ 2^40 − 1 bytes", "heading")
    figure.add_text(630, 402, "2b. S ≥ 2^40 bytes", "heading")
    figure.add_text(58, 441, "One native multi-burst DMA")
    figure.add_text(58, 478, "nBurst = N; length = L", "mono")
    figure.add_text(58, 511, "encoded strides = S, D", "mono")
    figure.add_text(58, 560, "Hardware advances to each burst.")
    figure.add_text(58, 594, "The helper returns directly.")
    figure.add_text(58, 647, "The boundary value still uses this path.", "small")
    figure.add_text(630, 441, "N single-burst DMA operations")
    figure.add_text(630, 478, "for i = 0 .. N − 1:", "mono")
    figure.add_text(652, 511, "copy src + i×S → dst + i×D", "mono")
    figure.add_text(652, 544, "nBurst = 1; length = L", "mono")
    figure.add_text(652, 577, "encoded strides = 0, 0", "mono")
    figure.add_text(630, 616, "Software retains the full address offsets.")
    figure.add_text(630, 647, "64-bit arithmetic; no stride truncation.", "small")
    figure.add_text(36, 718, "A5 only: compiler-known N ≤ 8 uses bounded unrolling; dynamic/larger N keeps the loop.")
    figure.add_text(
        36, 746, "D = destination start-to-start stride. Other encoded fields must still fit their own limits.", "small"
    )
    return figure


def _render_tinsert_nz_split() -> MemoryLayoutFigure:
    figure = MemoryLayoutFigure(
        "TINSERT_NZ_SPLIT",
        "TINSERT: NZ column blocks and SPLIT2 / SPLIT4",
        "A5 example: half, valid = 17 × 65, source Rows = 32, destination Rows = 48, offset = (0, 0).",
        860,
        "Five 16-column NZ blocks are copied in order. SPLIT2 groups them as two then three blocks; SPLIT4 "
        "groups them as one, one, one, then two. Each burst copies 32 aligned rows including tails. Source "
        "block pitch is 1024 bytes and destination block pitch is 1536 bytes for CompactMode Null.",
    )
    figure.add_rect(36, 108, 544, 310)
    figure.add_text(58, 144, "Logical matrix → 5 NZ column blocks", "heading")
    figure.add_text(58, 171, "half: C0 = 16 elements = 32 bytes per row", "small")
    for i in range(5):
        x = 70 + i * 95
        figure.add_rect(x, 208, 95, 132, "#E2E8F0", "#94A3B8", 0)
        figure.add_rect(x, 208, 95 if i < 4 else 95 / 16, 70, BLOCK_COLORS[i], "none", 0)
        figure.add_text(x + 47.5, 198, f"B{i}", anchor="middle")
        figure.add_text(x + 47.5, 365, f"{i * 16}–{i * 16 + 15}", "small", "middle")
    figure.add_line(70, 278, 545, 278, False, color=PURPLE, dash="5 4")
    figure.add_text(58, 391, "Dashed line: 17 valid rows; physical copy: 32 rows.", "small")
    figure.add_rect(604, 108, 560, 310)
    figure.add_text(626, 144, "Source storage: one block after another", "heading")
    for i in range(5):
        x = 626 + i * 101
        figure.add_rect(x, 208, 96, 64, BLOCK_COLORS[i], PURPLE, 3)
        figure.add_text(x + 48, 236, f"B{i}", anchor="middle")
        figure.add_text(x + 48, 258, "32 × 16", "small", "middle")
    figure.add_text(626, 306, "Inside each block: r0[16], r1[16], …, r31[16]", "small")
    figure.add_text(626, 340, "Each B = 1024 bytes; block order is preserved.")
    figure.add_text(626, 378, "Gray tails in the matrix are copied from source.", "small")
    figure.add_rect(36, 440, 1128, 248)
    figure.add_text(58, 476, "Split groups of consecutive blocks → one destination tile", "heading")
    for y, label, counts in [(509, "SPLIT2", [2, 3]), (596, "SPLIT4", [1, 1, 1, 2])]:
        figure.add_text(58, y + 30, label, "heading")
        start = 0
        for group, count in enumerate(counts):
            x = 205 + start * 174
            figure.add_rect(x, y, count * 174 - 8, 49, BLOCK_COLORS[group], PURPLE, 5)
            figure.add_text(
                x + (count * 174 - 8) / 2,
                y + 31,
                "  ".join(f"B{i}" for i in range(start, start + count)),
                anchor="middle",
            )
            figure.add_text(
                x + (count * 174 - 8) / 2,
                y + 70,
                f"DMA {group}: {count} block" + ("s" if count > 1 else ""),
                "small",
                "middle",
            )
            start += count
    figure.add_rect(36, 710, 1128, 126)
    figure.add_text(58, 745, "CompactMode::Null: source pitch = 32 × 32 B; destination pitch = 48 × 32 B.", "mono")
    figure.add_text(58, 779, "Each burst writes 32 rows; the next 16 destination rows in that block remain unchanged.")
    figure.add_text(
        58, 813, "Copied tails: rows 17–31 and columns 65–79. Allocate storage for the full copied extent.", "small"
    )
    return figure


def _render_textract_nd2nz_windows() -> MemoryLayoutFigure:
    figure = MemoryLayoutFigure(
        "TEXTRACT_ND2NZ_WINDOWS",
        "TEXTRACT: two ND windows → two NZ tiles",
        "A5 half example: source = 8 × 64; each destination has valid = 4 × 32 and physical Rows = 16.",
        800,
        "Two independently positioned source windows, at row zero column zero and row four column thirty-two, "
        "are extracted into separate NZ destinations. Each destination contains two 16-column blocks. The "
        "diagram shows the 16-row block pitch and the 17-row pitch used by RowPlusOne.",
    )
    figure.add_rect(36, 108, 536, 454)
    figure.add_text(58, 146, "Source ND: consecutive elements in each row", "heading")
    figure.add_text(58, 178, "TEXTRACT(dst0, dst1, src, 0, 0, 4, 32)", "small")
    for c in range(4):
        figure.add_text(125 + c * 118, 220, f"{c * 16}–{c * 16 + 15}", "small", "middle")
    for r in range(8):
        figure.add_text(52, 254 + r * 32, str(r), "small")
        for c in range(4):
            active0 = r < 4 and c < 2
            active1 = r >= 4 and c >= 2
            figure.add_rect(
                66 + c * 118,
                233 + r * 32,
                118,
                32,
                BLOCK_COLORS[0] if active0 else BLOCK_COLORS[1] if active1 else "#F1F5F9",
                "#94A3B8",
                0,
            )
            if active0 or active1:
                figure.add_text(125 + c * 118, 254 + r * 32, ("A" if active0 else "B") + str(c % 2), "small", "middle")
    figure.add_text(58, 530, "A: origin (0, 0)   |   B: origin (4, 32)")
    figure.add_line(573, 258, 603, 258, True)
    figure.add_line(573, 436, 603, 436, True)
    figure.add_rect(604, 108, 560, 454)
    figure.add_text(626, 146, "Destination NZ: 16-column blocks", "heading")
    for y, label, color, prefix in [(190, "dst0", BLOCK_COLORS[0], "A"), (368, "dst1", BLOCK_COLORS[1], "B")]:
        figure.add_text(626, y + 20, label, "heading")
        for c in range(2):
            x = 716 + c * 202
            figure.add_rect(x, y, 180, 120, "#E2E8F0", "#94A3B8", 0)
            figure.add_rect(x, y, 180, 42, color, "#94A3B8", 0)
            figure.add_text(x + 90, y + 28, f"{prefix}{c}: 4 × 16", "body", "middle")
            figure.add_text(x + 90, y + 77, "12 rows", "small", "middle")
            figure.add_text(x + 90, y + 99, "unchanged", "small", "middle")
        figure.add_text(806, y + 148, "offset 0 B", "small", "middle")
        figure.add_text(1008, y + 148, "offset 512 B", "small", "middle")
    figure.add_rect(36, 584, 1128, 190)
    figure.add_text(58, 621, "Element mapping (offsets in half elements)", "heading")
    figure.add_text(58, 656, "dst_k[ floor(c/16) × P × 16 + r × 16 + c%16 ]", "mono")
    figure.add_text(58, 688, "    = src[ (indexRow_k + r) × 64 + indexCol_k + c ]", "mono")
    figure.add_text(58, 726, "0 ≤ r < 4; 0 ≤ c < 32. Plain NZ: P = ceil16(4) = 16 → 512 B block pitch.", "small")
    figure.add_text(
        58, 754, "RowPlusOne: P = 17 → 544 B block pitch; the extra row between blocks is not written.", "small"
    )
    return figure


def _render_textract_acc_nz_groups() -> MemoryLayoutFigure:
    figure = MemoryLayoutFigure(
        "TEXTRACT_ACC_NZ_GROUPS",
        "TEXTRACT: A5 Acc → Mat NZ groups",
        "Source Acc uses 16-column groups. Destination grouping depends on dtype and fractal size.",
        740,
        "For float to half or bfloat16 NZ1024, each destination group has 32 columns. A 48-column window "
        "becomes one full group and one half-filled group, with Partial then Final flags for an outer Final "
        "phase. Int32 NZ512 channel splitting instead maps a 16-column source group to two 8-column destination "
        "groups with bits unchanged.",
    )
    figure.add_rect(36, 108, 1128, 344)
    figure.add_text(
        58, 145, "float → half / bfloat16, NZ1024: example valid = 8 × 48; destination Rows = 16", "heading"
    )
    figure.add_text(58, 179, "L0C source groups", "small")
    for i in range(3):
        x = 58 + i * 164
        figure.add_rect(x, 198, 156, 78, BLOCK_COLORS[i], PURPLE, 3)
        figure.add_text(x + 78, 229, f"cols {16 * i}–{16 * i + 15}", anchor="middle")
        figure.add_text(x + 78, 257, "16 columns", "small", "middle")
    figure.add_line(555, 237, 620, 237, True)
    figure.add_text(662, 179, "L1 destination groups", "small")
    figure.add_rect(656, 198, 230, 78, BLOCK_COLORS[0], PURPLE, 3)
    figure.add_text(771, 229, "cols 0–31", anchor="middle")
    figure.add_text(771, 257, "row stride: 32", "small", "middle")
    figure.add_rect(906, 198, 230, 78, "#E2E8F0", "#94A3B8", 3)
    figure.add_rect(906, 198, 115, 78, BLOCK_COLORS[2], PURPLE, 0)
    figure.add_text(963.5, 229, "32–47", "small", "middle")
    figure.add_text(1078.5, 229, "48–63", "small", "middle")
    figure.add_text(963.5, 257, "written", "small", "middle")
    figure.add_text(1078.5, 257, "unchanged", "small", "middle")
    figure.add_text(771, 310, "offset 0 elements", "small", "middle")
    figure.add_text(1021, 310, "offset 512 elements", "small", "middle")
    figure.add_text(58, 344, "Group starts = group × Rows × 32 elements; each group reserves 32 columns.")
    figure.add_text(
        58, 379, "Only 8 valid rows are written. A final 16-column group keeps its other 16 columns unchanged."
    )
    figure.add_text(58, 421, "Outer STPhase::Final → first group: Partial; last group: Final.", "mono")
    figure.add_rect(36, 476, 1128, 226)
    figure.add_text(58, 514, "int32 → int32, NZ512: channel split preserves bits", "heading")
    figure.add_rect(58, 549, 326, 67, BLOCK_COLORS[1], TEAL, 3)
    figure.add_text(221, 578, "one source group: cols 0–15", anchor="middle")
    figure.add_text(221, 603, "16 columns", "small", "middle")
    figure.add_line(405, 583, 608, 583, True)
    figure.add_text(506, 557, "one instruction", "small", "middle")
    for i in range(2):
        x = 650 + i * 250
        figure.add_rect(x, 549, 230, 67, BLOCK_COLORS[i], TEAL, 3)
        figure.add_text(x + 115, 578, f"cols {8 * i}–{8 * i + 7}", anchor="middle")
        figure.add_text(x + 115, 603, "8 columns", "small", "middle")
    figure.add_text(58, 652, "Destination group pitch = Rows × 8 int32 elements; row stride = 8 elements.", "mono")
    figure.add_text(
        58, 683, "NoQuant + NoRelu; valid columns round up to 8. Outer phase is forwarded unchanged.", "small"
    )
    return figure


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate detailed memory-layout SVG diagrams")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--check", action="store_true", help="Check that generated SVGs match the tracked files")
    args = parser.parse_args()
    figures = [
        _render_tload_stride_fallback(),
        _render_tinsert_nz_split(),
        _render_textract_nd2nz_windows(),
        _render_textract_acc_nz_groups(),
    ]
    if not args.check:
        args.output_dir.mkdir(parents=True, exist_ok=True)
    errors = []
    for figure in figures:
        path = args.output_dir / f"{figure.name}.svg"
        expected = figure.render()
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                errors.append(f"missing or out-of-date SVG: {path}")
        else:
            path.write_text(expected, encoding="utf-8")
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1
    print(f"OK: {len(figures)} memory-layout SVGs {'match their source' if args.check else 'generated'}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
