#!/usr/bin/env python3
# coding=utf-8

import argparse
import json
from pathlib import Path

DEFAULT_CASE = {
    "batch": 1,
    "seq_len": 128,
    "hidden": 4096,
    "num_heads": 32,
    "head_dim": 128,
    "latent": 64,
    "rope_dim": 64,
}

FIELD_ORDER = ["batch", "seq_len", "hidden", "num_heads", "head_dim", "latent", "rope_dim"]


def parse_case(raw: str) -> dict:
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    if len(parts) != len(FIELD_ORDER):
        raise ValueError("Expected BATCH,SEQ_LEN,HIDDEN,NUM_HEADS,HEAD_DIM,LATENT,ROPE_DIM")
    case = {key: int(value) for key, value in zip(FIELD_ORDER, parts)}
    if min(case.values()) <= 0:
        raise ValueError("All MLA case values must be positive")
    if case["num_heads"] * case["head_dim"] != case["hidden"]:
        raise ValueError("MLA v1 requires NUM_HEADS * HEAD_DIM == HIDDEN")
    if case["rope_dim"] % 2 != 0:
        raise ValueError("ROPE_DIM must be even")
    if case["seq_len"] != 128 or case["latent"] != 64 or case["rope_dim"] != 64:
        raise ValueError("MLA v1 currently keeps SEQ_LEN=128, LATENT=64, and ROPE_DIM=64 fixed")
    return case


def case_name(case: dict) -> str:
    return (
        f"case_B{case['batch']}_S{case['seq_len']}_H{case['hidden']}"
        f"_NH{case['num_heads']}_HD{case['head_dim']}_L{case['latent']}_RD{case['rope_dim']}"
    )


def render_header(case: dict) -> str:
    return f"""#pragma once
// Auto-generated by scripts/generate_cases.py. Do not edit manually.
// clang-format off

static constexpr unsigned kMlaBatch = {case["batch"]};
static constexpr unsigned kMlaSeqLen = {case["seq_len"]};
static constexpr unsigned kMlaHidden = {case["hidden"]};
static constexpr unsigned kMlaNumHeads = {case["num_heads"]};
static constexpr unsigned kMlaHeadDim = {case["head_dim"]};
static constexpr unsigned kMlaLatent = {case["latent"]};
static constexpr unsigned kMlaRopeDim = {case["rope_dim"]};
static constexpr unsigned kMlaRopeHalf = kMlaRopeDim / 2;
static constexpr unsigned kMlaQKVHidden = kMlaNumHeads * kMlaHeadDim;
static constexpr unsigned kMlaQRopeWidth = kMlaNumHeads * kMlaRopeDim;
static constexpr unsigned kMlaHeadDimTotal = kMlaHeadDim + kMlaRopeDim;
static constexpr const char *kMlaCaseName = "{case_name(case)}";

// clang-format on
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate MLA case header/JSON")
    parser.add_argument("--cases", default=None, help="Single case: BATCH,SEQ_LEN,HIDDEN,NUM_HEADS,HEAD_DIM,LATENT,ROPE_DIM")
    parser.add_argument(
        "--output-header",
        default=str(Path(__file__).resolve().parent.parent / "build" / "generated_cases.h"),
    )
    parser.add_argument(
        "--output-json",
        default=str(Path(__file__).resolve().parent.parent / "build" / "generated_cases.json"),
    )
    args = parser.parse_args()

    case = parse_case(args.cases) if args.cases else dict(DEFAULT_CASE)
    payload = {"name": case_name(case), **case}

    header_path = Path(args.output_header)
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(render_header(case))

    json_path = Path(args.output_json)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps([payload], indent=2))

    print(f"[INFO] Wrote {header_path}")
    print(f"[INFO] Wrote {json_path}")
    print(f"[INFO] Case: {payload}")


if __name__ == "__main__":
    main()
