#!/usr/bin/env python3
# coding=utf-8
# --------------------------------------------------------------------------------
# HCA Compressor - generate_cases.py
#
# Generates build/generated_cases.h and build/generated_cases.json for the
# HCA (Heavily Compressed Attention) Compressor kernel harness.
#
# Model: DeepSeek-V4-Flash only (d=4096, c=512).
# Compress ratio is FIXED at 128 (m'=128); seq_len must be a multiple of 128.
#
# Usage:
#   python3 scripts/generate_cases.py                   # default case
#   python3 scripts/generate_cases.py --cases 1,256     # BATCH,SEQ_LEN
# --------------------------------------------------------------------------------

import argparse
import json
from pathlib import Path

# DeepSeek-V4-Flash model dimensions (fixed)
_HIDDEN_DIM     = 4096
_COMPRESS_DIM   = 512
_COMPRESS_RATIO = 128

DEFAULT_CASE = {
    "batch":          1,
    "seq_len":        128,
    "hidden_dim":     _HIDDEN_DIM,
    "compress_dim":   _COMPRESS_DIM,
    "compress_ratio": _COMPRESS_RATIO,
}


def parse_case(raw: str) -> dict:
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    if len(parts) != 2:
        raise ValueError(f"Expected BATCH,SEQ_LEN, got '{raw}'")
    batch, seq_len = int(parts[0]), int(parts[1])
    if batch <= 0 or seq_len <= 0:
        raise ValueError("BATCH and SEQ_LEN must be positive")
    if seq_len % _COMPRESS_RATIO != 0:
        raise ValueError(
            f"SEQ_LEN must be a multiple of COMPRESS_RATIO={_COMPRESS_RATIO}; "
            f"got SEQ_LEN={seq_len}"
        )
    return {
        "batch":          batch,
        "seq_len":        seq_len,
        "hidden_dim":     _HIDDEN_DIM,
        "compress_dim":   _COMPRESS_DIM,
        "compress_ratio": _COMPRESS_RATIO,
    }


def case_name(case: dict) -> str:
    return (
        f"dsv4flash_B{case['batch']}_S{case['seq_len']}"
        f"_d{case['hidden_dim']}_c{case['compress_dim']}_r{case['compress_ratio']}"
    )


def render_header(case: dict) -> str:
    return f"""#pragma once
// Auto-generated by scripts/generate_cases.py. Do not edit manually.
// clang-format off

// DeepSeek-V4-Flash HCA Compressor test case.
// compress_ratio is always 128; hidden_dim and compress_dim are model-fixed.

static constexpr int kHcaBatch          = {case["batch"]};
static constexpr int kHcaSeqLen         = {case["seq_len"]};
static constexpr int kHcaHiddenDim      = {case["hidden_dim"]};
static constexpr int kHcaCompressDim    = {case["compress_dim"]};
static constexpr int kHcaCompressRatio  = {case["compress_ratio"]};
static constexpr int kHcaNumBlocks      = kHcaSeqLen / kHcaCompressRatio;
static constexpr const char *kHcaCaseName = "{case_name(case)}";

// clang-format on
"""


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate HCA Compressor case header/JSON (DeepSeek-V4-Flash config)"
    )
    parser.add_argument(
        "--cases",
        default=None,
        help="Single case: BATCH,SEQ_LEN  (SEQ_LEN must be a multiple of 128)",
    )
    parser.add_argument(
        "--output-header",
        default=str(
            Path(__file__).resolve().parent.parent / "build" / "generated_cases.h"
        ),
    )
    parser.add_argument(
        "--output-json",
        default=str(
            Path(__file__).resolve().parent.parent / "build" / "generated_cases.json"
        ),
    )
    args = parser.parse_args()

    case = parse_case(args.cases) if args.cases else dict(DEFAULT_CASE)
    payload = {"name": case_name(case), **case}

    header_path = Path(args.output_header)
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(render_header(case), encoding="utf-8")

    json_path = Path(args.output_json)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps([payload], indent=2), encoding="utf-8")

    print(f"[INFO] Wrote {header_path}")
    print(f"[INFO] Wrote {json_path}")
    print(f"[INFO] Case: {payload}")


if __name__ == "__main__":
    main()
