#!/usr/bin/env python3
# coding=utf-8

import argparse
import json
from pathlib import Path

DEFAULT_CASE = {
    "num_tiles": 4,
    "tile_rows": 64,
    "tile_cols": 64,
}


def parse_case(raw: str) -> dict:
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    if len(parts) != 3:
        raise ValueError(f"Expected NUM_TILES,TILE_ROWS,TILE_COLS, got '{raw}'")
    num_tiles, tile_rows, tile_cols = map(int, parts)
    if min(num_tiles, tile_rows, tile_cols) <= 0:
        raise ValueError("All add_tile_array case values must be positive")
    return {"num_tiles": num_tiles, "tile_rows": tile_rows, "tile_cols": tile_cols}


def case_name(case: dict) -> str:
    return f"case_N{case['num_tiles']}_R{case['tile_rows']}_C{case['tile_cols']}"


def render_header(case: dict) -> str:
    return f"""#pragma once
// Auto-generated by scripts/generate_cases.py. Do not edit manually.
// clang-format off

static constexpr int kAddTileArrayNumTiles = {case["num_tiles"]};
static constexpr int kAddTileArrayTileRows = {case["tile_rows"]};
static constexpr int kAddTileArrayTileCols = {case["tile_cols"]};
static constexpr int kAddTileArrayTotalRows = kAddTileArrayNumTiles * kAddTileArrayTileRows;
static constexpr const char *kAddTileArrayCaseName = "{case_name(case)}";

// clang-format on
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate add_tile_array case header/JSON")
    parser.add_argument("--cases", default=None, help="Single case: NUM_TILES,TILE_ROWS,TILE_COLS")
    parser.add_argument(
        "--output-header",
        default=str(Path(__file__).resolve().parent.parent / "build" / "generated_cases.h"),
    )
    parser.add_argument(
        "--output-json",
        default=str(Path(__file__).resolve().parent.parent / "build" / "generated_cases.json"),
    )
    args = parser.parse_args()

    case = parse_case(args.cases) if args.cases else dict(DEFAULT_CASE)
    payload = {"name": case_name(case), **case}

    header_path = Path(args.output_header)
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(render_header(case))

    json_path = Path(args.output_json)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps([payload], indent=2))

    print(f"[INFO] Wrote {header_path}")
    print(f"[INFO] Wrote {json_path}")
    print(f"[INFO] Case: {payload}")


if __name__ == "__main__":
    main()
