#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# --------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# --------------------------------------------------------------------------------

import argparse
import json
from pathlib import Path
from typing import Dict, List


DEFAULT_CASES = [
    (256, 64, 64, 32, 1),
]


def _parse_case_entry(raw: str) -> Dict[str, int]:
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    if len(parts) != 5:
        raise ValueError(f"Expected 5 comma-separated values (kT,kH,kF,kE,kTopK), got '{raw}'")
    t, h, f, e, topk = map(int, parts)
    if min(t, h, f, e, topk) <= 0:
        raise ValueError("All MoEv2 case values must be positive")
    if topk > e:
        raise ValueError("kTopK cannot exceed kE")
    return {"t": t, "h": h, "f": f, "e": e, "topk": topk}


def _default_cases() -> List[Dict[str, int]]:
    return [{"t": t, "h": h, "f": f, "e": e, "topk": k} for (t, h, f, e, k) in DEFAULT_CASES]


def _case_name(case: Dict[str, int]) -> str:
    return f"case_T{case['t']}_H{case['h']}_F{case['f']}_E{case['e']}_K{case['topk']}"


def _render_macro(cases: List[Dict[str, int]]) -> str:
    lines = ["#define MOE_FOR_EACH_CASE(MACRO) \\"]
    for idx, case in enumerate(cases):
        suffix = " \\" if idx + 1 != len(cases) else ""
        lines.append(f"    MACRO({case['t']}, {case['h']}, {case['f']}, {case['e']}, {case['topk']}){suffix}")
    return "\n".join(lines)


def _render_header(cases: List[Dict[str, int]]) -> str:
    macro_block = _render_macro(cases)
    array_block = ",\n".join(
        "    {" + ", ".join([
            str(case["t"]),
            str(case["h"]),
            str(case["f"]),
            str(case["e"]),
            str(case["topk"]),
            f'"{_case_name(case)}"',
        ]) + "}"
        for case in cases
    )

    return f"""#pragma once
// Auto-generated by scripts/generate_cases.py. Do not edit manually.
// clang-format off
#include <cstddef>

{macro_block}

struct GeneratedMoeCase {{
    int t;
    int h;
    int f;
    int e;
    int topk;
    const char *name;
}};

static constexpr GeneratedMoeCase kGeneratedMoeCases[] = {{
{array_block}
}};
static constexpr std::size_t kGeneratedMoeCasesCount = sizeof(kGeneratedMoeCases) / sizeof(kGeneratedMoeCases[0]);

static constexpr int kMoeT    = kGeneratedMoeCases[0].t;
static constexpr int kMoeH    = kGeneratedMoeCases[0].h;
static constexpr int kMoeF    = kGeneratedMoeCases[0].f;
static constexpr int kMoeE    = kGeneratedMoeCases[0].e;
static constexpr int kMoeTopK = kGeneratedMoeCases[0].topk;
static constexpr const char *kMoeCaseName = kGeneratedMoeCases[0].name;

// clang-format on
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate MoEv2 family case header/JSON")
    parser.add_argument("--cases", action="append", default=None, help="Case entry in the format kT,kH,kF,kE,kTopK")
    parser.add_argument(
        "--output-header",
        default=str(Path(__file__).resolve().parent.parent / "build" / "generated_cases.h"),
    )
    parser.add_argument(
        "--output-json",
        default=str(Path(__file__).resolve().parent.parent / "build" / "generated_cases.json"),
    )
    args = parser.parse_args()

    cases = [_parse_case_entry(entry) for entry in args.cases] if args.cases else _default_cases()

    header_path = Path(args.output_header)
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(_render_header(cases))

    json_payload = [{"name": _case_name(case), **case} for case in cases]
    json_path = Path(args.output_json)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(json_payload, indent=2))

    print(f"[INFO] Wrote {header_path}")
    print(f"[INFO] Wrote {json_path}")
    for case in json_payload:
        print(f"  - {case['name']} (kT={case['t']}, kH={case['h']}, kF={case['f']}, "
              f"kE={case['e']}, kTopK={case['topk']})")


if __name__ == "__main__":
    main()
