#!/usr/bin/env python3
# coding=utf-8

import argparse
import json
from pathlib import Path

DEFAULT_CASE = {
    "b": 1,
    "m": 6,
    "n": 6,
    "h": 16,
    "d": 256,
    "topk": 6,
}


def parse_case(raw: str) -> dict:
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    if len(parts) != 6:
        raise ValueError("Expected B,M,N,H,D,TOPK")
    b, m, n, h, d, topk = map(int, parts)
    case = {"b": b, "m": m, "n": n, "h": h, "d": d, "topk": topk}
    if min(case.values()) <= 0:
        raise ValueError("All sparse_flash_attn case values must be positive")
    if topk > n:
        raise ValueError("TOPK cannot exceed N for the conservative default path")
    if h != 16 or d != 256:
        raise ValueError("sparse_flash_attn currently instantiates only H=16,D=256")
    return case


def case_name(case: dict) -> str:
    return f"case_B{case['b']}_M{case['m']}_N{case['n']}_H{case['h']}_D{case['d']}_K{case['topk']}"


def render_header(case: dict) -> str:
    return f"""#pragma once
// Auto-generated by generate_cases.py. Do not edit manually.
// clang-format off

static constexpr long long kSparseFaB = {case["b"]};
static constexpr long long kSparseFaM = {case["m"]};
static constexpr long long kSparseFaN = {case["n"]};
static constexpr int kSparseFaH = {case["h"]};
static constexpr int kSparseFaD = {case["d"]};
static constexpr long long kSparseFaTopK = {case["topk"]};
static constexpr int kSparseFaBlock = 64;
static constexpr const char *kSparseFaCaseName = "{case_name(case)}";

// clang-format on
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate sparse_flash_attn case header/JSON")
    parser.add_argument("--cases", default=None, help="Single case: B,M,N,H,D,TOPK")
    parser.add_argument("--output-header", default=str(Path(__file__).resolve().parent / "build" / "generated_cases.h"))
    parser.add_argument("--output-json", default=str(Path(__file__).resolve().parent / "build" / "generated_cases.json"))
    args = parser.parse_args()

    case = parse_case(args.cases) if args.cases else dict(DEFAULT_CASE)
    payload = {"name": case_name(case), **case}

    header_path = Path(args.output_header)
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(render_header(case))

    json_path = Path(args.output_json)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps([payload], indent=2))

    print(f"[INFO] Wrote {header_path}")
    print(f"[INFO] Wrote {json_path}")
    print(f"[INFO] Case: {payload}")


if __name__ == "__main__":
    main()
