/**
Copyright (c) 2025 Huawei Technologies Co., Ltd.
This program is free software, you can redistribute it and/or modify it under the terms and conditions of
CANN Open Software License Agreement Version 2.0 (the "License").
Please refer to the License for details. You may not use this file except in compliance with the License.
THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
See LICENSE in the root of the software repository for the full text of the License.
*/

// ============================================================================
// Kernel-side headers (compiled for AICore under -xcce)
// ============================================================================
#include <cstddef>
#include <cstdint>
#include <iostream>

#include <pto/pto-inst.hpp>
#include "../common.hpp"

using namespace pto;

// ============================================================================
// Device kernel 鈥?generated by PTOAS from D:\cann\async_comm-pto.cpp
// Tests TPUT_ASYNC + TGET_ASYNC via the SDMA DMA engine.
//
// Parameters:
//   v1  鈥?first float buffer  (128 elements, __gm__)
//   v2  鈥?second float buffer (128 elements, __gm__)
//   v3  鈥?SDMA workspace      (int8_t*, __gm__)
//
// The kernel issues two async DMA operations through a single AsyncSession:
//   TPUT_ASYNC(dst=v1, src=v2, session)  鈥?DMA copy: v2 鈫?v1
//   TGET_ASYNC(src=v2, dst=v1, session)  鈥?DMA copy: v2 鈫?v1 (reads same session)
// Both are fire-and-forget; completion is guaranteed by stream synchronization on
// the host side (aclrtSynchronizeStream).
// ============================================================================

enum class PTOAutoSyncTailMode : int {
    kBarrierAll = 0,
    kSetWaitMte3ToSEvent0 = 1,
};

static AICORE inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll)
{
    switch (mode) {
    case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
        set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        break;
    case PTOAutoSyncTailMode::kBarrierAll:
    default:
        pipe_barrier(PIPE_ALL);
        break;
    }
}

__global__ AICORE void async_comm_kernel(__gm__ float *v1, __gm__ float *v2, __gm__ int8_t *v3)
{
    uint32_t v4 = UINT32_MAX;
    uint32_t v5 = 0u;
    int64_t v6 = 0;
    int32_t v7 = 256;
    int32_t v8 = 1;
    using T = float;
    Tile<TileType::Vec, int8_t, 1, 256, BLayout::RowMajor, 1, 256, SLayout::NoneBox, 512, PadValue::Null> v9;
    TASSIGN(v9, v6);
    __gm__ uint8_t *v10 = (__gm__ uint8_t *)v3;
    pto::comm::AsyncSession v11;
    pto::comm::sdma::SdmaBaseConfig v12 = {32768ULL, 0ULL, 1u};
    pto::comm::BuildAsyncSession<pto::comm::DmaEngine::SDMA>(v9, v10, v11, v5, v12, v4);
    pto::Shape<1, 1, 1, 1, 128> v13 = pto::Shape<1, 1, 1, 1, 128>();
    pto::Stride<128, 128, 128, 128, 1> v14 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v15 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v1, v13, v14);
    pto::Shape<1, 1, 1, 1, 128> v16 = pto::Shape<1, 1, 1, 1, 128>();
    pto::Stride<128, 128, 128, 128, 1> v17 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v18 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v2, v16, v17);
    pto::comm::AsyncEvent v19 = pto::comm::TPUT_ASYNC<pto::comm::DmaEngine::SDMA>(v15, v18, v11);
    pto::Shape<1, 1, 1, 1, 128> v20 = pto::Shape<1, 1, 1, 1, 128>();
    pto::Stride<128, 128, 128, 128, 1> v21 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v22 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v2, v20, v21);
    pto::Shape<1, 1, 1, 1, 128> v23 = pto::Shape<1, 1, 1, 1, 128>();
    pto::Stride<128, 128, 128, 128, 1> v24 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v25 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v1, v23, v24);
    pto::comm::AsyncEvent v26 = pto::comm::TGET_ASYNC<pto::comm::DmaEngine::SDMA>(v22, v25, v11);
    return;
}

// ============================================================================
// Host runner
// Allocates device memory, launches the kernel, and verifies the stream sync.
//
// The kernel issues:
//   TPUT_ASYNC(dst=v1, src=v2): DMA v2 鈫?v1
//   TGET_ASYNC(src=v2, dst=v1): DMA v2 鈫?v1
//
// After stream sync, v1 is expected to contain the original contents of v2
// (both async ops write v2 into v1).
// ============================================================================
static constexpr size_t kElemCount = 128; // matches Shape<1,1,1,1,128>

bool RunAsyncCommTest(int /*n_ranks*/, int /*n_devices*/, int /*first_rank_id*/, int first_device_id)
{
    // ACL init
    constexpr int32_t kAclRepeatInit = 100002;
    aclError aRet = aclInit(nullptr);
    if (aRet != ACL_SUCCESS && static_cast<int>(aRet) != kAclRepeatInit) {
        std::cerr << "[ERROR] aclInit failed: " << static_cast<int>(aRet) << std::endl;
        return false;
    }

    aRet = aclrtSetDevice(first_device_id);
    if (aRet != ACL_SUCCESS) {
        std::cerr << "[ERROR] aclrtSetDevice(" << first_device_id
                  << ") failed: " << static_cast<int>(aRet) << std::endl;
        return false;
    }

    rtStream_t stream = nullptr;
    int32_t rtRet = rtStreamCreate(&stream, RT_STREAM_PRIORITY_DEFAULT);
    if (rtRet != 0) {
        std::cerr << "[ERROR] rtStreamCreate failed: " << rtRet << std::endl;
        aclrtResetDevice(first_device_id);
        aclFinalize();
        return false;
    }

    // Allocate device buffers for v1 and v2
    float *v1_dev = nullptr;
    float *v2_dev = nullptr;
    aRet = aclrtMalloc(reinterpret_cast<void **>(&v1_dev), kElemCount * sizeof(float),
                       ACL_MEM_MALLOC_HUGE_FIRST);
    if (aRet != ACL_SUCCESS) {
        std::cerr << "[ERROR] aclrtMalloc v1 failed: " << static_cast<int>(aRet) << std::endl;
        rtStreamDestroy(stream);
        aclrtResetDevice(first_device_id);
        aclFinalize();
        return false;
    }
    aRet = aclrtMalloc(reinterpret_cast<void **>(&v2_dev), kElemCount * sizeof(float),
                       ACL_MEM_MALLOC_HUGE_FIRST);
    if (aRet != ACL_SUCCESS) {
        std::cerr << "[ERROR] aclrtMalloc v2 failed: " << static_cast<int>(aRet) << std::endl;
        aclrtFree(v1_dev);
        rtStreamDestroy(stream);
        aclrtResetDevice(first_device_id);
        aclFinalize();
        return false;
    }

    // Fill v1 with 0..127, v2 with 1000..1127
    float v1_host[kElemCount];
    float v2_host[kElemCount];
    for (size_t i = 0; i < kElemCount; ++i) {
        v1_host[i] = static_cast<float>(i);
        v2_host[i] = static_cast<float>(i + 1000);
    }
    aclrtMemcpy(v1_dev, kElemCount * sizeof(float), v1_host, kElemCount * sizeof(float),
                ACL_MEMCPY_HOST_TO_DEVICE);
    aclrtMemcpy(v2_dev, kElemCount * sizeof(float), v2_host, kElemCount * sizeof(float),
                ACL_MEMCPY_HOST_TO_DEVICE);

    // Allocate SDMA workspace
    SdmaWorkspaceManager sdmaMgr;
    if (!sdmaMgr.Init()) {
        std::cerr << "[ERROR] SdmaWorkspaceManager::Init failed" << std::endl;
        aclrtFree(v1_dev);
        aclrtFree(v2_dev);
        rtStreamDestroy(stream);
        aclrtResetDevice(first_device_id);
        aclFinalize();
        return false;
    }
    int8_t *v3_dev = reinterpret_cast<int8_t *>(sdmaMgr.GetWorkspaceAddr());

    // Launch kernel (1 AICore block)
    async_comm_kernel<<<1, nullptr, stream>>>(v1_dev, v2_dev, v3_dev);
    aclError syncStatus = aclrtSynchronizeStream(stream);

    // Read back results
    float result_v1[kElemCount];
    aclrtMemcpy(result_v1, kElemCount * sizeof(float), v1_dev, kElemCount * sizeof(float),
                ACL_MEMCPY_DEVICE_TO_HOST);

    bool is_ok = (syncStatus == ACL_SUCCESS);
    if (!is_ok) {
        std::cerr << "[ERROR] aclrtSynchronizeStream failed: " << static_cast<int>(syncStatus)
                  << std::endl;
    } else {
        // The kernel issues TPUT_ASYNC(dst=v1, src=v2) then TGET_ASYNC(src=v2, dst=v1),
        // both of which DMA v2's content into v1. Verify v1 == original v2 (i+1000).
        for (size_t i = 0; i < kElemCount; ++i) {
            if (result_v1[i] != v2_host[i]) {
                std::cerr << "[FAIL] v1[" << i << "] = " << result_v1[i]
                          << ", expected " << v2_host[i] << std::endl;
                is_ok = false;
                break;
            }
        }
        if (is_ok) {
            std::cout << "\n================================================================" << std::endl;
            std::cout << "[PASS] async_comm_kernel: TPUT_ASYNC + TGET_ASYNC OK" << std::endl;
            std::cout << "  v1[0..4] after kernel: [ ";
            for (size_t i = 0; i < 5; ++i)
                std::cout << result_v1[i] << " ";
            std::cout << "... ]" << std::endl;
            std::cout << "================================================================\n" << std::endl;
        }
    }

    // Cleanup
    sdmaMgr.Finalize();
    aclrtFree(v1_dev);
    aclrtFree(v2_dev);
    rtStreamDestroy(stream);
    aclrtResetDevice(first_device_id);
    aclFinalize();

    return is_ok;
}

// ============================================================================
// Shared setup/teardown helpers for the runners below
// ============================================================================

struct AsyncCommCtx {
    rtStream_t       stream  = nullptr;
    float           *v1_dev  = nullptr;
    float           *v2_dev  = nullptr;
    SdmaWorkspaceManager sdmaMgr;
    int8_t          *ws_dev  = nullptr;
    int              dev_id  = 0;
    bool             valid   = false;
};

static bool AsyncCommCtxInit(AsyncCommCtx &ctx, int device_id,
                             const float *v1_host, const float *v2_host, size_t n)
{
    ctx.dev_id = device_id;
    constexpr int32_t kAclRepeatInit = 100002;
    aclError aRet = aclInit(nullptr);
    if (aRet != ACL_SUCCESS && static_cast<int>(aRet) != kAclRepeatInit) {
        std::cerr << "[ERROR] aclInit: " << static_cast<int>(aRet) << std::endl;
        return false;
    }
    if (aclrtSetDevice(device_id) != ACL_SUCCESS) {
        std::cerr << "[ERROR] aclrtSetDevice" << std::endl;
        return false;
    }
    if (rtStreamCreate(&ctx.stream, RT_STREAM_PRIORITY_DEFAULT) != 0) {
        std::cerr << "[ERROR] rtStreamCreate" << std::endl;
        aclrtResetDevice(device_id); aclFinalize();
        return false;
    }
    const size_t bytes = n * sizeof(float);
    if (aclrtMalloc(reinterpret_cast<void **>(&ctx.v1_dev), bytes, ACL_MEM_MALLOC_HUGE_FIRST) != ACL_SUCCESS ||
        aclrtMalloc(reinterpret_cast<void **>(&ctx.v2_dev), bytes, ACL_MEM_MALLOC_HUGE_FIRST) != ACL_SUCCESS) {
        std::cerr << "[ERROR] aclrtMalloc" << std::endl;
        return false;
    }
    aclrtMemcpy(ctx.v1_dev, bytes, v1_host, bytes, ACL_MEMCPY_HOST_TO_DEVICE);
    aclrtMemcpy(ctx.v2_dev, bytes, v2_host, bytes, ACL_MEMCPY_HOST_TO_DEVICE);
    if (!ctx.sdmaMgr.Init()) {
        std::cerr << "[ERROR] SdmaWorkspaceManager::Init" << std::endl;
        return false;
    }
    ctx.ws_dev = reinterpret_cast<int8_t *>(ctx.sdmaMgr.GetWorkspaceAddr());
    ctx.valid  = true;
    return true;
}

static void AsyncCommCtxDestroy(AsyncCommCtx &ctx)
{
    ctx.sdmaMgr.Finalize();
    if (ctx.v1_dev) aclrtFree(ctx.v1_dev);
    if (ctx.v2_dev) aclrtFree(ctx.v2_dev);
    rtStreamDestroy(ctx.stream);
    aclrtResetDevice(ctx.dev_id);
    aclFinalize();
}

// ============================================================================
// Runner 2: RunZeroDataTest
//
// v1 = [1..128]  (non-zero initial)
// v2 = [0..0]    (all zeros)
//
// Kernel: TPUT_ASYNC(dst=v1, src=v2) + TGET_ASYNC(src=v2, dst=v1)
//         both overwrite v1 with v2's zeros.
// Verify: v1 == 0 after sync.
//
// Rationale: confirms the DMA correctly overwrites non-zero destination data
// with all-zero source data 鈥?catches a class of "stale data" bugs where
// a buffer is never actually written.
// ============================================================================
bool RunZeroDataTest(int first_device_id)
{
    constexpr size_t kN = 128;
    float v1_host[kN], v2_host[kN];
    for (size_t i = 0; i < kN; ++i) {
        v1_host[i] = static_cast<float>(i + 1); // 1..128
        v2_host[i] = 0.0f;
    }

    AsyncCommCtx ctx;
    if (!AsyncCommCtxInit(ctx, first_device_id, v1_host, v2_host, kN)) return false;

    async_comm_kernel<<<1, nullptr, ctx.stream>>>(ctx.v1_dev, ctx.v2_dev, ctx.ws_dev);
    bool is_ok = (aclrtSynchronizeStream(ctx.stream) == ACL_SUCCESS);

    float result[kN];
    aclrtMemcpy(result, kN * sizeof(float), ctx.v1_dev, kN * sizeof(float), ACL_MEMCPY_DEVICE_TO_HOST);

    if (is_ok) {
        for (size_t i = 0; i < kN; ++i) {
            if (result[i] != 0.0f) {
                std::cerr << "[FAIL] v1[" << i << "] = " << result[i] << ", expected 0" << std::endl;
                is_ok = false;
                break;
            }
        }
        if (is_ok)
            std::cout << "\n[PASS] ZeroData: v1 overwritten with zeros OK\n";
    }

    AsyncCommCtxDestroy(ctx);
    return is_ok;
}

// ============================================================================
// Runner 3: RunNegativeDataTest
//
// v1 = [0..127]          (positive initial)
// v2 = [-1..-128]        (negative floats)
//
// Kernel overwrites v1 with v2's negative values.
// Verify: v1[i] == -(i+1)
//
// Rationale: confirms the DMA correctly transfers negative float values,
// ruling out sign-bit truncation or unsigned-only transfer bugs.
// ============================================================================
bool RunNegativeDataTest(int first_device_id)
{
    constexpr size_t kN = 128;
    float v1_host[kN], v2_host[kN];
    for (size_t i = 0; i < kN; ++i) {
        v1_host[i] = static_cast<float>(i);
        v2_host[i] = -static_cast<float>(i + 1); // -1..-128
    }

    AsyncCommCtx ctx;
    if (!AsyncCommCtxInit(ctx, first_device_id, v1_host, v2_host, kN)) return false;

    async_comm_kernel<<<1, nullptr, ctx.stream>>>(ctx.v1_dev, ctx.v2_dev, ctx.ws_dev);
    bool is_ok = (aclrtSynchronizeStream(ctx.stream) == ACL_SUCCESS);

    float result[kN];
    aclrtMemcpy(result, kN * sizeof(float), ctx.v1_dev, kN * sizeof(float), ACL_MEMCPY_DEVICE_TO_HOST);

    if (is_ok) {
        for (size_t i = 0; i < kN; ++i) {
            if (result[i] != v2_host[i]) {
                std::cerr << "[FAIL] v1[" << i << "] = " << result[i]
                          << ", expected " << v2_host[i] << std::endl;
                is_ok = false;
                break;
            }
        }
        if (is_ok)
            std::cout << "\n[PASS] NegativeData: v1 = [-1..-128] OK\n";
    }

    AsyncCommCtxDestroy(ctx);
    return is_ok;
}

// ============================================================================
// Runner 4: RunMultiLaunchTest
//
// Launches async_comm_kernel 3 times on the same device, each time with
// a different v2 value (round 0: +5000, round 1: +6000, round 2: +7000).
// After each launch, v1 is read back and verified against v2.
//
// Rationale: confirms that the SDMA session state (channelInfo->sq_tail,
// completion flag slots) is correctly re-initialized on each kernel launch,
// i.e., no state leaks between successive runs.
// ============================================================================
bool RunMultiLaunchTest(int first_device_id)
{
    constexpr size_t kN = 128;
    constexpr int32_t kAclRepeatInit = 100002;

    aclError aRet = aclInit(nullptr);
    if (aRet != ACL_SUCCESS && static_cast<int>(aRet) != kAclRepeatInit) {
        std::cerr << "[ERROR] aclInit: " << static_cast<int>(aRet) << std::endl;
        return false;
    }
    if (aclrtSetDevice(first_device_id) != ACL_SUCCESS) return false;

    rtStream_t stream = nullptr;
    if (rtStreamCreate(&stream, RT_STREAM_PRIORITY_DEFAULT) != 0) {
        aclrtResetDevice(first_device_id); aclFinalize();
        return false;
    }

    float *v1_dev = nullptr, *v2_dev = nullptr;
    const size_t bytes = kN * sizeof(float);
    aclrtMalloc(reinterpret_cast<void **>(&v1_dev), bytes, ACL_MEM_MALLOC_HUGE_FIRST);
    aclrtMalloc(reinterpret_cast<void **>(&v2_dev), bytes, ACL_MEM_MALLOC_HUGE_FIRST);

    bool is_ok = true;
    for (int round = 0; round < 3 && is_ok; ++round) {
        // Each round gets a fresh SdmaWorkspaceManager so that the completion
        // flag slots and sq_tail in the workspace are reset to zero.  Without
        // this, the slots written as "done" (flag != 0) by a previous kernel
        // launch are reused by the next BuildAsyncSession; Wait() returns
        // immediately on those stale slots and the actual DMA is never issued.
        SdmaWorkspaceManager sdmaMgr;
        if (!sdmaMgr.Init()) {
            std::cerr << "[ERROR] round " << round << ": SdmaWorkspaceManager::Init" << std::endl;
            is_ok = false;
            break;
        }
        int8_t *ws_dev = reinterpret_cast<int8_t *>(sdmaMgr.GetWorkspaceAddr());

        float v2_host[kN];
        for (size_t i = 0; i < kN; ++i)
            v2_host[i] = static_cast<float>(i + 5000 + round * 1000); // 5000, 6000, 7000

        aclrtMemcpy(v2_dev, bytes, v2_host, bytes, ACL_MEMCPY_HOST_TO_DEVICE);

        async_comm_kernel<<<1, nullptr, stream>>>(v1_dev, v2_dev, ws_dev);
        if (aclrtSynchronizeStream(stream) != ACL_SUCCESS) {
            std::cerr << "[ERROR] round " << round << ": aclrtSynchronizeStream failed" << std::endl;
            sdmaMgr.Finalize();
            is_ok = false;
            break;
        }

        float result[kN];
        aclrtMemcpy(result, bytes, v1_dev, bytes, ACL_MEMCPY_DEVICE_TO_HOST);

        for (size_t i = 0; i < kN; ++i) {
            if (result[i] != v2_host[i]) {
                std::cerr << "[FAIL] round=" << round << " v1[" << i << "]="
                          << result[i] << " expected=" << v2_host[i] << std::endl;
                is_ok = false;
                break;
            }
        }
        if (is_ok)
            std::cout << "[PASS] MultiLaunch round " << round
                      << ": v1[0]=" << result[0] << " OK\n";

        sdmaMgr.Finalize();
    }

    aclrtFree(v1_dev); aclrtFree(v2_dev);
    rtStreamDestroy(stream); aclrtResetDevice(first_device_id); aclFinalize();
    return is_ok;
}

// ============================================================================
// Runner 5: RunCrossRankTest
//
// 2-rank SDMA cross-device RDMA test using the original kernel unchanged.
//
// Both ranks allocate sendBuf (offset=0) and recvBuf (offset=kBytes) at
// identical offsets within their HCCL-registered window.  This lets rank 0
// compute rank 1's recvBuf address without any kernel modification:
//
//   remoteRecvBuf = windowsIn[1] + kBytes   (device 6's view of device 7's recvBuf)
//
// Rank 0 calls:
//   async_comm_kernel(v1=remoteRecvBuf, v2=sendBuf, v3=ws)
//   → TPUT_ASYNC(dst=rank1_recvBuf, src=rank0_sendBuf)  via SDMA RDMA
//
// Rank 1 verifies its recvBuf == rank 0's sendBuf after the second barrier.
//
// Note: the original kernel has no Wait() calls, so SDMA DMA may still be
// in-flight when aclrtSynchronizeStream returns.  The second HcclHostBarrier
// (a collective network operation) adds enough latency that 512-byte SDMA
// completes well before rank 1 reads recvBuf.
// ============================================================================
static bool RunCrossRankKernel(int rankId, int nRanks, int nDevices, int firstDeviceId,
                               const HcclRootInfo *rootInfo)
{
    constexpr size_t kN     = 128;
    constexpr size_t kBytes = kN * sizeof(float);

    TestContext ctx;
    if (!ctx.Init(rankId, nRanks, nDevices, firstDeviceId, rootInfo))
        return false;

    // Local HCCL rank index (0 or 1) and the peer's index
    const int myRank    = static_cast<int>(ctx.hostCtx.rankId);
    const int otherRank = 1 - myRank;

    // Allocate sendBuf and recvBuf at identical offsets in every rank's window.
    //   sendBuf: windowsIn[rank] + 0
    //   recvBuf: windowsIn[rank] + kBytes
    size_t winOffset = 0;
    auto *sendBuf = reinterpret_cast<float *>(WindowAlloc(ctx.hostCtx.windowsIn[myRank], winOffset, kBytes));
    auto *recvBuf = reinterpret_cast<float *>(WindowAlloc(ctx.hostCtx.windowsIn[myRank], winOffset, kBytes));

    // Remote recvBuf: same byte-offset within the other rank's HCCL window.
    // SDMA hardware will route writes to this address over NVLink/PCIe.
    auto *remoteRecvBuf = reinterpret_cast<float *>(ctx.hostCtx.windowsIn[otherRank] + kBytes);

    // Fill buffers on device
    float sendHost[kN], zeroHost[kN];
    for (size_t i = 0; i < kN; ++i) {
        sendHost[i] = static_cast<float>(i + myRank * 1000); // rank0: 0..127, rank1: 1000..1127
        zeroHost[i] = 0.0f;
    }
    aclrtMemcpy(sendBuf, kBytes, sendHost, kBytes, ACL_MEMCPY_HOST_TO_DEVICE);
    aclrtMemcpy(recvBuf, kBytes, zeroHost, kBytes, ACL_MEMCPY_HOST_TO_DEVICE);

    // Barrier 1: both ranks have initialised their buffers before any cross-rank DMA
    HcclHostBarrier(ctx.comm, ctx.stream);

    bool is_ok = true;

    if (myRank == 0) {
        // Rank 0 (device firstDeviceId): send sendBuf → rank 1's recvBuf via SDMA RDMA
        // Do NOT return early here: always fall through to Barrier 2 to prevent deadlock
        // with rank 1 which is blocked waiting on it.
        SdmaWorkspaceManager sdmaMgr;
        if (!sdmaMgr.Init()) {
            std::cerr << "[ERROR] Rank 0: SdmaWorkspaceManager::Init failed\n";
            is_ok = false;
        } else {
            // Original kernel signature: async_comm_kernel(v1=dst, v2=src, v3=workspace)
            // TPUT_ASYNC(dst=remoteRecvBuf, src=sendBuf) copies rank0's data to rank1
            async_comm_kernel<<<1, nullptr, ctx.stream>>>(
                remoteRecvBuf,
                sendBuf,
                reinterpret_cast<int8_t *>(sdmaMgr.GetWorkspaceAddr())
            );
            if (aclrtSynchronizeStream(ctx.stream) != ACL_SUCCESS) {
                std::cerr << "[ERROR] Rank 0: aclrtSynchronizeStream failed\n";
                is_ok = false;
            }
            sdmaMgr.Finalize();
        }
    }

    // Barrier 2: ALWAYS reached by both ranks to prevent deadlock.
    // rank 0 signals "DMA submitted"; rank 1 waits before reading recvBuf.
    // HcclHostBarrier's collective latency far exceeds the 512-byte SDMA transfer,
    // so rank 1's recvBuf is populated by the time it reads.
    HcclHostBarrier(ctx.comm, ctx.stream);

    // Rank 1 verifies that its recvBuf now contains rank 0's sendBuf data (0..127)
    if (myRank == 1) {
        float result[kN];
        aclrtMemcpy(result, kBytes, recvBuf, kBytes, ACL_MEMCPY_DEVICE_TO_HOST);

        for (size_t i = 0; i < kN; ++i) {
            const float expected = static_cast<float>(i); // rank 0's sendBuf: 0 + 0*1000, 1 + 0*1000, ...
            if (result[i] != expected) {
                std::cerr << "[FAIL] CrossRank: recvBuf[" << i << "]=" << result[i]
                          << " expected=" << expected << "\n";
                is_ok = false;
                break;
            }
        }
        if (is_ok) {
            std::cout << "\n================================================================\n"
                      << "[PASS] CrossRank: rank0 (dev" << firstDeviceId
                      << ") → rank1 (dev" << (firstDeviceId + 1) << ") TPUT_ASYNC OK\n"
                      << "  recvBuf[0..4]: [ ";
            for (size_t i = 0; i < 5; ++i) std::cout << result[i] << " ";
            std::cout << "... ]\n================================================================\n";
        }
    }

    return ctx.Finalize() && is_ok;
}

bool RunCrossRankTest(int n_ranks, int n_devices, int first_rank_id, int first_device_id)
{
    return ForkAndRunWithHcclRootInfo(n_ranks, first_rank_id, first_device_id,
        [&](int rankId, const HcclRootInfo *rootInfo) {
            return RunCrossRankKernel(rankId, n_ranks, n_devices, first_device_id, rootInfo);
        });
}

// ============================================================================
// Runner 6: RunRootPut4RanksTest
//
// 4-rank root-broadcast test: rank 0 (root) launches async_comm_kernel once
// per non-root rank (3 sequential launches), each with a fresh workspace.
//
// Each kernel call internally issues BOTH TPUT_ASYNC and TGET_ASYNC (the
// original kernel always calls both):
//   TPUT_ASYNC(v1=target_recvBuf, v2=root_sendBuf, ...)  → push root→target
//   TGET_ASYNC(v1=target_recvBuf, v2=root_sendBuf, ...)  → same src/dst, same direction
//
// Buffer layout in each rank's HCCL window (same offsets for all ranks):
//   sendBuf: windowsIn[rank] + 0
//   recvBuf: windowsIn[rank] + kBytes
//
// Root call per target:
//   async_comm_kernel(v1=windowsIn[target]+kBytes, v2=sendBuf, v3=ws)
//
// Each non-root rank verifies recvBuf == root's sendBuf (i.e., [0..127]).
//
// A fresh SdmaWorkspaceManager is created for each kernel launch to avoid
// completion flag slot pollution across consecutive calls (same issue as Test 4).
// ============================================================================
static bool RunRootPut4RanksKernel(int rankId, int nRanks, int nDevices, int firstDeviceId,
                                   const HcclRootInfo *rootInfo)
{
    constexpr size_t kN     = 128;
    constexpr size_t kBytes = kN * sizeof(float);
    constexpr int    kRoot  = 0;

    TestContext ctx;
    if (!ctx.Init(rankId, nRanks, nDevices, firstDeviceId, rootInfo))
        return false;

    const int myRank = static_cast<int>(ctx.hostCtx.rankId); // 0..3

    // Allocate sendBuf and recvBuf at identical offsets in every rank's window
    size_t winOffset = 0;
    auto *sendBuf = reinterpret_cast<float *>(WindowAlloc(ctx.hostCtx.windowsIn[myRank], winOffset, kBytes));
    auto *recvBuf = reinterpret_cast<float *>(WindowAlloc(ctx.hostCtx.windowsIn[myRank], winOffset, kBytes));

    // Fill: sendBuf = [rank*1000 + 0 .. rank*1000 + 127], recvBuf = 0
    float sendHost[kN], zeroHost[kN];
    for (size_t i = 0; i < kN; ++i) {
        sendHost[i] = static_cast<float>(i + myRank * 1000);
        zeroHost[i] = 0.0f;
    }
    aclrtMemcpy(sendBuf, kBytes, sendHost, kBytes, ACL_MEMCPY_HOST_TO_DEVICE);
    aclrtMemcpy(recvBuf, kBytes, zeroHost, kBytes, ACL_MEMCPY_HOST_TO_DEVICE);

    // Barrier 1: all ranks have written their initial buffers
    HcclHostBarrier(ctx.comm, ctx.stream);

    bool is_ok = true;

    if (myRank == kRoot) {
        // Root sends its sendBuf to each non-root rank's recvBuf sequentially.
        // Each send uses a fresh SdmaWorkspaceManager to avoid stale completion
        // flag slots from the previous kernel launch (same root cause as Test 4).
        for (int target = 0; target < nRanks && is_ok; ++target) {
            if (target == kRoot) continue;

            auto *remoteRecvBuf =
                reinterpret_cast<float *>(ctx.hostCtx.windowsIn[target] + kBytes);

            SdmaWorkspaceManager sdmaMgr;
            if (!sdmaMgr.Init()) {
                std::cerr << "[ERROR] Root: SdmaWorkspaceManager::Init failed"
                          << " (target=" << target << ")\n";
                is_ok = false;
                break;
            }

            // async_comm_kernel(v1=dst, v2=src, v3=workspace)
            // kernel internally calls:
            //   TPUT_ASYNC(v1=remoteRecvBuf, v2=sendBuf) → root data → target recvBuf
            //   TGET_ASYNC(v1=remoteRecvBuf, v2=sendBuf) → same src/dst, same direction
            async_comm_kernel<<<1, nullptr, ctx.stream>>>(
                remoteRecvBuf,
                sendBuf,
                reinterpret_cast<int8_t *>(sdmaMgr.GetWorkspaceAddr())
            );

            if (aclrtSynchronizeStream(ctx.stream) != ACL_SUCCESS) {
                std::cerr << "[ERROR] Root: aclrtSynchronizeStream failed"
                          << " (target=" << target << ")\n";
                sdmaMgr.Finalize();
                is_ok = false;
                break;
            }
            sdmaMgr.Finalize();
            std::cout << "[Root dev" << firstDeviceId << "] → rank" << target
                      << " (dev" << (firstDeviceId + target) << ") send OK\n";
        }
    }

    // Barrier 2: root must reach here even on error to prevent deadlock;
    // non-root ranks wait here before reading recvBuf.
    HcclHostBarrier(ctx.comm, ctx.stream);

    // Non-root ranks verify recvBuf == root's sendBuf data ([0..127])
    if (myRank != kRoot) {
        float result[kN];
        aclrtMemcpy(result, kBytes, recvBuf, kBytes, ACL_MEMCPY_DEVICE_TO_HOST);

        for (size_t i = 0; i < kN; ++i) {
            const float expected = static_cast<float>(i); // root sendBuf: i + kRoot*1000 = i
            if (result[i] != expected) {
                std::cerr << "[FAIL] Rank " << myRank << ": recvBuf[" << i << "]="
                          << result[i] << " expected=" << expected << "\n";
                is_ok = false;
                break;
            }
        }
        if (is_ok) {
            std::cout << "\n================================================================\n"
                      << "[PASS] Rank " << myRank << " (dev" << (firstDeviceId + myRank)
                      << "): root-put received OK\n"
                      << "  recvBuf[0..4]: [ ";
            for (size_t i = 0; i < 5; ++i) std::cout << result[i] << " ";
            std::cout << "... ]\n================================================================\n";
        }
    }

    return ctx.Finalize() && is_ok;
}

bool RunRootPut4RanksTest(int n_ranks, int n_devices, int first_rank_id, int first_device_id)
{
    return ForkAndRunWithHcclRootInfo(n_ranks, first_rank_id, first_device_id,
        [&](int rankId, const HcclRootInfo *rootInfo) {
            return RunRootPut4RanksKernel(rankId, n_ranks, n_devices, first_device_id, rootInfo);
        });
}
