#include <pto/pto-inst.hpp>
#include "test_common.h"
#include <gtest/gtest.h>
#include <fstream>

using namespace std;
using namespace PtoTestCommon;

template <int32_t testKey>
void launchTLOAD(uint8_t *out, uint8_t *src, uint64_t *gLog, void *stream);

class TLoadConvTest : public testing::Test {
protected:
    void SetUp() override
    {}
    void TearDown() override
    {}
};

inline size_t GetFileSize(const std::string& filename) {

    std::ifstream in(filename, std::ios::binary | std::ios::ate);

    return in.is_open() ? static_cast<size_t>(in.tellg()) : 0;

}

std::string GetGoldenDir()
{
    const testing::TestInfo *testInfo = testing::UnitTest::GetInstance()->current_test_info();
    const std::string caseName = testInfo->name();
    std::string suiteName = testInfo->test_suite_name();
    std::string fullPath = "../" + suiteName + "." + caseName;
    return fullPath;
}

#define LOGSIZE 128
#define PRINTLOG 4
#define MAXBLOCK 64

template <int32_t testKey, typename T>
void tload_test() {
    aclInit(nullptr);
    aclrtSetDevice(0);
    aclrtStream stream;
    aclrtCreateStream(&stream);

    // 1. Resolve paths and get file sizes
    string path = GetGoldenDir();
    size_t in_byteSize = GetFileSize(path + "/input.bin");
    size_t gold_byteSize = GetFileSize(path + "/golden.bin");

    // 2. Prepare Host and Device Memory
    T *srcHost, *goldHost, *dstHost;
    void *srcDevice, *dstDevice, *logDevice = nullptr;

    aclrtMallocHost((void**)&srcHost, in_byteSize);
    aclrtMallocHost((void**)&goldHost, gold_byteSize);
    aclrtMallocHost((void**)&dstHost, gold_byteSize);
    aclrtMalloc((void**)&srcDevice, in_byteSize, ACL_MEM_MALLOC_HUGE_FIRST);
    aclrtMalloc((void**)&dstDevice, gold_byteSize, ACL_MEM_MALLOC_HUGE_FIRST);

    // 3. Load input/golden binaries generated by Python
    ReadFile(path + "/input.bin", in_byteSize, srcHost, in_byteSize);
    ReadFile(path + "/golden.bin", gold_byteSize, goldHost, gold_byteSize);
    memset(dstHost, 0, gold_byteSize);

    // 4. Copy to Device and Launch
    aclrtMemcpy(srcDevice, in_byteSize, srcHost, in_byteSize, ACL_MEMCPY_HOST_TO_DEVICE);
    aclrtMemcpy(dstDevice, gold_byteSize, dstHost, gold_byteSize, ACL_MEMCPY_HOST_TO_DEVICE);

#ifdef DEBUGLOG
    aclrtMalloc((void**)&logDevice, MAXBLOCK * LOGSIZE * 8, ACL_MEM_MALLOC_HUGE_FIRST);
#endif

    launchTLOAD<testKey>((uint8_t*)dstDevice, (uint8_t*)srcDevice, (uint64_t*)logDevice, stream);
    aclrtSynchronizeStream(stream);

    // 5. Pull Result and Compare
    aclrtMemcpy(dstHost, gold_byteSize, dstDevice, gold_byteSize, ACL_MEMCPY_DEVICE_TO_HOST);

    int elements = gold_byteSize / sizeof(T);
    bool ret = ResultCmp(vector<T>(goldHost, goldHost + elements), 
                         vector<T>(dstHost, dstHost + elements), 0);

    // 6. Cleanup
    aclrtFreeHost(srcHost); aclrtFreeHost(goldHost); aclrtFreeHost(dstHost);
    aclrtFree(srcDevice); aclrtFree(dstDevice);
    if(logDevice) aclrtFree(logDevice);
    aclrtDestroyStream(stream);
    aclrtResetDevice(0);
    aclFinalize();

    EXPECT_TRUE(ret);
}

// --- Updated GTest Cases matching Python folder names ---

TEST_F(TLoadConvTest, case_5HD_fused_fp16) { 
    tload_test<1, half>(); 
}

TEST_F(TLoadConvTest, case_5HD_cropped_fp32) { 
    tload_test<2, float>(); 
}

TEST_F(TLoadConvTest, case_FracZ_4D_fp16) { 
    tload_test<3, half>(); 
}

TEST_F(TLoadConvTest, case_FracZ_5D_small_int8) { 
    tload_test<4, int8_t>(); 
}