#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate CSA (Compressed-Sparse-Attention / sparse_attn) family case
configuration. Mirrors the Compressor family generator
(kernels/automode/a2a3/deepseekv4/HCA/Compressor/scripts/generate_cases.py).

Case format: H,D,S,BLOCK
  H      number of heads     (padded to 16 if <16; see kernel.py:359)
  D      head dim            (ModelArgs.index_head_dim default 128)
  S      topk length         (selected KV positions per query, default 512)
  BLOCK  inner pipeline block along S (kernel.py:290 default 64)

Defaults (per kernel.py + model.py defaults):
  Realistic: H=16, D=128, S=512, BLOCK=64
  Tiny:      H=4,  D=32,  S=64,  BLOCK=32   <- DEFAULT for fast prototype

Output: <CSA>/build/generated_cases.{h,json}
"""
import argparse
import json
from pathlib import Path
from typing import List, Dict

# Tiny default — keeps the per-binary prototype small. Use --cases to opt in to
# realistic shapes (1 head=16, D=128, S=512, BLOCK=64).
DEFAULT_CASES = [
    (4, 32, 64, 32),
]


def _parse_case_entry(raw: str) -> Dict[str, int]:
    parts = [p.strip() for p in raw.split(',') if p.strip()]
    if len(parts) != 4:
        raise ValueError(f"Expected 4 comma-separated values (H,D,S,BLOCK), got '{raw}'")
    h, d, s, block = map(int, parts)
    if min(h, d, s, block) <= 0:
        raise ValueError("H, D, S, BLOCK must be positive")
    if s % block != 0:
        # Tail handling is not in this prototype; warn but allow.
        print(f"[WARN] S={s} not a multiple of BLOCK={block} — tail handling deferred")
    if h < 16:
        # Kernel.py pads heads to 16; we record the raw H but expose the
        # padded value for the kernel binaries.
        print(f"[INFO] H={h} < 16; kernel-side will pad to 16 (kernel.py:359)")
    return {"h": h, "d": d, "s": s, "block": block}


def _default_cases() -> List[Dict[str, int]]:
    return [{"h": h, "d": d, "s": s, "block": block}
            for (h, d, s, block) in DEFAULT_CASES]


def _case_name(c: Dict[str, int]) -> str:
    return f"case_H{c['h']}_D{c['d']}_S{c['s']}_B{c['block']}"


def _num_blocks(c: Dict[str, int]) -> int:
    # Mirrors tilelang.cdiv(topk, block) at kernel.py:291.
    return (c["s"] + c["block"] - 1) // c["block"]


def _render_macro(cases: List[Dict[str, int]]) -> str:
    lines = ["#define CSA_FOR_EACH_CASE(MACRO) \\"]
    for idx, c in enumerate(cases):
        suffix = " \\" if idx + 1 != len(cases) else ""
        line = (f"    MACRO({c['h']}, {c['d']}, {c['s']}, {c['block']}, "
                f"{_num_blocks(c)}){suffix}")
        lines.append(line)
    return "\n".join(lines)


def _render_header(cases: List[Dict[str, int]]) -> str:
    macro_block = _render_macro(cases)
    array_entries = []
    for c in cases:
        array_entries.append("    {" + ", ".join([
            str(c["h"]), str(c["d"]), str(c["s"]), str(c["block"]),
            str(_num_blocks(c)), f'"{_case_name(c)}"',
        ]) + "}")
    array_block = ",\n".join(array_entries)

    return f"""#pragma once
// Auto-generated by scripts/generate_cases.py. Do not edit manually.
// clang-format off
#include <cstddef>

{macro_block}

struct GeneratedCsaCase {{
    int h;
    int d;
    int s;
    int block;
    int num_blocks;
    const char *name;
}};

static constexpr GeneratedCsaCase kGeneratedCsaCases[] = {{
{array_block}
}};
static constexpr std::size_t kGeneratedCsaCasesCount =
    sizeof(kGeneratedCsaCases) / sizeof(kGeneratedCsaCases[0]);

// Convenience aliases — leaf binaries compile against the first case.
static constexpr int kCsaH         = kGeneratedCsaCases[0].h;
static constexpr int kCsaD         = kGeneratedCsaCases[0].d;
static constexpr int kCsaS         = kGeneratedCsaCases[0].s;
static constexpr int kCsaBlock     = kGeneratedCsaCases[0].block;
static constexpr int kCsaNumBlocks = kGeneratedCsaCases[0].num_blocks;
static constexpr const char *kCsaCaseName = kGeneratedCsaCases[0].name;

// clang-format on
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate CSA family case header/JSON")
    parser.add_argument("--cases", action="append", default=None,
                        help="Case entry: H,D,S,BLOCK")
    parser.add_argument("--output-header",
                        default=str((Path(__file__).resolve().parent.parent / "build" / "generated_cases.h")))
    parser.add_argument("--output-json",
                        default=str((Path(__file__).resolve().parent.parent / "build" / "generated_cases.json")))
    args = parser.parse_args()

    if args.cases:
        cases = [_parse_case_entry(entry) for entry in args.cases]
    else:
        cases = _default_cases()

    header_path = Path(args.output_header)
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(_render_header(cases))

    json_payload = [{"name": _case_name(c), **c, "num_blocks": _num_blocks(c)}
                    for c in cases]
    json_path = Path(args.output_json)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(json_payload, indent=2))

    print(f"[INFO] Wrote {header_path}")
    print(f"[INFO] Wrote {json_path}")
    for c in json_payload:
        print(f"  - {c['name']}")


if __name__ == "__main__":
    main()
