#!/usr/bin/env python3
# coding=utf-8

import argparse
import json
from pathlib import Path

DEFAULT_CASE = {
    "g_shape3": 4800,
    "g_shape4": 1024,
    "g_whole_shape3": 4800,
    "g_whole_shape4": 1280,
    "topk": 1000,
}


def parse_case(raw: str) -> dict:
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    if len(parts) != 5:
        raise ValueError("Expected G_SHAPE3,G_SHAPE4,G_WHOLE_SHAPE3,G_WHOLE_SHAPE4,TOPK")
    g_shape3, g_shape4, g_whole_shape3, g_whole_shape4, topk = map(int, parts)
    case = {
        "g_shape3": g_shape3,
        "g_shape4": g_shape4,
        "g_whole_shape3": g_whole_shape3,
        "g_whole_shape4": g_whole_shape4,
        "topk": topk,
    }
    if min(case.values()) <= 0:
        raise ValueError("All topkv2 case values must be positive")
    if g_shape3 > g_whole_shape3 or g_shape4 > g_whole_shape4:
        raise ValueError("Valid shape cannot exceed whole shape")
    if topk > g_shape4:
        raise ValueError("TOPK cannot exceed G_SHAPE4")
    return case


def case_name(case: dict) -> str:
    return (
        f"case_R{case['g_shape3']}_C{case['g_shape4']}"
        f"_WR{case['g_whole_shape3']}_WC{case['g_whole_shape4']}_K{case['topk']}"
    )


def render_header(case: dict) -> str:
    return f"""#pragma once
// Auto-generated by scripts/generate_cases.py. Do not edit manually.
// clang-format off

static constexpr int kTopkv2GShape3 = {case["g_shape3"]};
static constexpr int kTopkv2GShape4 = {case["g_shape4"]};
static constexpr int kTopkv2GWholeShape3 = {case["g_whole_shape3"]};
static constexpr int kTopkv2GWholeShape4 = {case["g_whole_shape4"]};
static constexpr int kTopkv2TopK = {case["topk"]};
static constexpr int kTopkv2BlockDim = 48;
static constexpr const char *kTopkv2CaseName = "{case_name(case)}";

// clang-format on
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate topkv2 case header/JSON")
    parser.add_argument("--cases", default=None, help="Single case: G_SHAPE3,G_SHAPE4,G_WHOLE_SHAPE3,G_WHOLE_SHAPE4,TOPK")
    parser.add_argument(
        "--output-header",
        default=str(Path(__file__).resolve().parent.parent / "build" / "generated_cases.h"),
    )
    parser.add_argument(
        "--output-json",
        default=str(Path(__file__).resolve().parent.parent / "build" / "generated_cases.json"),
    )
    args = parser.parse_args()

    case = parse_case(args.cases) if args.cases else dict(DEFAULT_CASE)
    payload = {"name": case_name(case), **case}

    header_path = Path(args.output_header)
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(render_header(case))

    json_path = Path(args.output_json)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps([payload], indent=2))

    print(f"[INFO] Wrote {header_path}")
    print(f"[INFO] Wrote {json_path}")
    print(f"[INFO] Case: {payload}")


if __name__ == "__main__":
    main()
