#!/usr/bin/env python3
# coding=utf-8

import argparse
import json
from pathlib import Path

DEFAULT_CASE = {
    "rows": 4,
    "cols": 1280,
    "topk": 512,
}


def parse_case(raw: str) -> dict:
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    if len(parts) != 3:
        raise ValueError(f"Expected ROWS,COLS,TOPK, got '{raw}'")
    rows, cols, topk = map(int, parts)
    if min(rows, cols, topk) <= 0:
        raise ValueError("All topk case values must be positive")
    if topk > cols:
        raise ValueError("TOPK cannot exceed COLS")
    return {"rows": rows, "cols": cols, "topk": topk}


def case_name(case: dict) -> str:
    return f"case_R{case['rows']}_C{case['cols']}_K{case['topk']}"


def render_header(case: dict) -> str:
    return f"""#pragma once
// Auto-generated by scripts/generate_cases.py. Do not edit manually.
// clang-format off

static constexpr int kTopkRows = {case["rows"]};
static constexpr int kTopkCols = {case["cols"]};
static constexpr int kTopkTopK = {case["topk"]};
static constexpr const char *kTopkCaseName = "{case_name(case)}";

// clang-format on
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate topk case header/JSON")
    parser.add_argument("--cases", default=None, help="Single case: ROWS,COLS,TOPK")
    parser.add_argument(
        "--output-header",
        default=str(Path(__file__).resolve().parent.parent / "build" / "generated_cases.h"),
    )
    parser.add_argument(
        "--output-json",
        default=str(Path(__file__).resolve().parent.parent / "build" / "generated_cases.json"),
    )
    args = parser.parse_args()

    case = parse_case(args.cases) if args.cases else dict(DEFAULT_CASE)
    payload = {"name": case_name(case), **case}

    header_path = Path(args.output_header)
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(render_header(case))

    json_path = Path(args.output_json)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps([payload], indent=2))

    print(f"[INFO] Wrote {header_path}")
    print(f"[INFO] Wrote {json_path}")
    print(f"[INFO] Case: {payload}")


if __name__ == "__main__":
    main()
