/**
Copyright (c) 2026 Huawei Technologies Co., Ltd.
This program is free software, you can redistribute it and/or modify it under the terms and conditions of
CANN Open Software License Agreement Version 2.0 (the "License").
Please refer to the License for details. You may not use this file except in compliance with the License.
THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
See LICENSE in the root of the software repository for the full text of the License.
*/

#ifndef CONST_ARGS_HPP
#define CONST_ARGS_HPP

#include <cstdint>

#include "pto/common/buffer_limits.hpp"

constexpr static uint64_t MB_SIZE = 1024 * 1024UL;
constexpr static int32_t UB_ALIGN = 32;
constexpr uint16_t CROSS_CORE_FLAG_MAX_SET_COUNT = 15;
constexpr uint16_t MEGA_MOE_D2C_HARD_FLAG_BASE = 0;
constexpr uint16_t MEGA_MOE_D2C_HARD_FLAG_COUNT = 3;
constexpr uint16_t MEGA_MOE_D2C_HARD_FLAG_LAST = MEGA_MOE_D2C_HARD_FLAG_BASE + MEGA_MOE_D2C_HARD_FLAG_COUNT - 1;
constexpr uint16_t MEGA_MOE_C2V_HARD_FLAG_BASE = 3;
constexpr uint16_t MEGA_MOE_V2C_HARD_FLAG_BASE = 4;
constexpr uint16_t MEGA_MOE_GMM2_COMBINE_CV_HARD_FLAG_BASE = 5;
constexpr uint16_t MEGA_MOE_GMM2_COMBINE_CV_READY_HARD_FLAG = MEGA_MOE_GMM2_COMBINE_CV_HARD_FLAG_BASE;
constexpr uint16_t MEGA_MOE_GMM2_COMBINE_CV_FREE_HARD_FLAG = MEGA_MOE_GMM2_COMBINE_CV_HARD_FLAG_BASE + 1;
constexpr uint16_t MEGA_MOE_MAX_BUSINESS_HARD_FLAG_ID = MEGA_MOE_GMM2_COMBINE_CV_FREE_HARD_FLAG;
constexpr uint8_t MEGA_MOE_GMM2_COMBINE_CV_MAX_AIV_PER_AIC = 2;
constexpr uint8_t MEGA_MOE_GMM2_COMBINE_CV_DEFAULT_FIFO_DEPTH = 1;
constexpr uint32_t MEGA_MOE_GMM2_COMBINE_CV_TILE_M = 128;
constexpr uint32_t MEGA_MOE_GMM2_COMBINE_CV_TILE_N = 256;
constexpr uint32_t MEGA_MOE_GMM2_COMBINE_CV_ELEMENT_BYTES = 2;
constexpr uint32_t MEGA_MOE_GMM2_COMBINE_CV_SLOT_BYTES =
    MEGA_MOE_GMM2_COMBINE_CV_TILE_M * MEGA_MOE_GMM2_COMBINE_CV_TILE_N * MEGA_MOE_GMM2_COMBINE_CV_ELEMENT_BYTES;
constexpr uint32_t MEGA_MOE_GMM2_COMBINE_CV_SMALL_MAX_ELEMS = 8192;
constexpr uint32_t MEGA_MOE_GMM2_COMBINE_CV_SMALL_SCALE_ELEMS = 32;
constexpr uint32_t MEGA_MOE_GMM2_COMBINE_CV_SMALL_BUFFER_BYTES =
    MEGA_MOE_GMM2_COMBINE_CV_SMALL_MAX_ELEMS * MEGA_MOE_GMM2_COMBINE_CV_ELEMENT_BYTES +
    MEGA_MOE_GMM2_COMBINE_CV_SMALL_MAX_ELEMS * MEGA_MOE_GMM2_COMBINE_CV_ELEMENT_BYTES +
    MEGA_MOE_GMM2_COMBINE_CV_SMALL_MAX_ELEMS * sizeof(float) +
    MEGA_MOE_GMM2_COMBINE_CV_SMALL_SCALE_ELEMS * sizeof(float);
constexpr uint32_t MEGA_MOE_GMM2_COMBINE_CV_SLOT_OFFSET = 2 * MEGA_MOE_GMM2_COMBINE_CV_SMALL_BUFFER_BYTES;
constexpr uint32_t MEGA_MOE_GMM2_COMBINE_CV_TILE_SCALE_OFFSET =
    MEGA_MOE_GMM2_COMBINE_CV_SLOT_OFFSET + MEGA_MOE_GMM2_COMBINE_CV_SLOT_BYTES;
constexpr uint32_t MEGA_MOE_GMM2_COMBINE_CV_SCALE_CACHE_ELEMS = 4096;
constexpr uint32_t MEGA_MOE_GMM2_COMBINE_CV_TILE_SCALE_BYTES =
    MEGA_MOE_GMM2_COMBINE_CV_SCALE_CACHE_ELEMS * sizeof(float);
constexpr uint32_t MEGA_MOE_GMM2_COMBINE_CV_REQUIRED_UB_BYTES =
    MEGA_MOE_GMM2_COMBINE_CV_TILE_SCALE_OFFSET + MEGA_MOE_GMM2_COMBINE_CV_TILE_SCALE_BYTES;
constexpr uint32_t MEGA_MOE_D2C_MAX_LOGICAL_GROUP_EVENTS = MEGA_MOE_D2C_HARD_FLAG_COUNT * CROSS_CORE_FLAG_MAX_SET_COUNT;
static_assert(MEGA_MOE_D2C_HARD_FLAG_BASE == 0U);
static_assert(MEGA_MOE_D2C_HARD_FLAG_COUNT == 3U);
static_assert(MEGA_MOE_D2C_HARD_FLAG_LAST == 2U);
static_assert(MEGA_MOE_C2V_HARD_FLAG_BASE == 3U);
static_assert(MEGA_MOE_V2C_HARD_FLAG_BASE == 4U);
static_assert(MEGA_MOE_D2C_HARD_FLAG_LAST < MEGA_MOE_C2V_HARD_FLAG_BASE);
static_assert(MEGA_MOE_C2V_HARD_FLAG_BASE < MEGA_MOE_V2C_HARD_FLAG_BASE);
static_assert(MEGA_MOE_V2C_HARD_FLAG_BASE < MEGA_MOE_GMM2_COMBINE_CV_READY_HARD_FLAG);
static_assert(MEGA_MOE_GMM2_COMBINE_CV_READY_HARD_FLAG == 5U);
static_assert(MEGA_MOE_GMM2_COMBINE_CV_FREE_HARD_FLAG == 6U);
static_assert(MEGA_MOE_GMM2_COMBINE_CV_READY_HARD_FLAG + 1U == MEGA_MOE_GMM2_COMBINE_CV_FREE_HARD_FLAG);
static_assert(MEGA_MOE_MAX_BUSINESS_HARD_FLAG_ID < 11U);
static_assert(MEGA_MOE_MAX_BUSINESS_HARD_FLAG_ID <= 15U);
static_assert(MEGA_MOE_GMM2_COMBINE_CV_MAX_AIV_PER_AIC == 2U);
static_assert(MEGA_MOE_GMM2_COMBINE_CV_DEFAULT_FIFO_DEPTH == 1U);
static_assert(MEGA_MOE_GMM2_COMBINE_CV_SLOT_BYTES == 65536U);
static_assert(MEGA_MOE_GMM2_COMBINE_CV_SLOT_OFFSET == 131328U);

struct AtlasA5 {
    static constexpr uint32_t FIXBUF_SIZE = PTO_FBUF_SIZE_BYTES;
    static constexpr uint32_t UB_SIZE = PTO_UBUF_SIZE_BYTES;
    static constexpr uint32_t L1_SIZE = PTO_CBUF_SIZE_BYTES;
    static constexpr uint32_t L0A_SIZE = PTO_L0A_SIZE_BYTES;
    static constexpr uint32_t L0B_SIZE = PTO_L0B_SIZE_BYTES;
    static constexpr uint32_t L0C_SIZE = PTO_L0C_SIZE_BYTES;
};
static_assert(MEGA_MOE_GMM2_COMBINE_CV_REQUIRED_UB_BYTES <= AtlasA5::UB_SIZE);

#include "moe_swiglu_segment.hpp"

#endif // CONST_ARGS_HPP
