/**
Copyright (c) 2026 Huawei Technologies Co., Ltd.
This program is free software, you can redistribute it and/or modify it under the terms and conditions of
CANN Open Software License Agreement Version 2.0 (the "License").
Please refer to the License for details. You may not use this file except in compliance with the License.
THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
See LICENSE in the root of the software repository for the full text of the License.
*/

// Auto-generated by gen_cce_cycle_profiles_header.py from cce_cycle_profiles.csv.
// Do not edit this file manually.

#pragma once

#include <pto/costmodel/a2a3/cce_costmodel/cce_costmodel_core.hpp>

namespace cce_cycle_profiles {

// clang-format off
// NOLINTBEGIN(readability-magic-numbers)
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcmpvGeProfile{10.0, 2.0, 10.0, 2.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcmpvGtProfile{3.0, 1.0, 3.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcmpvLeProfile{10.0, 2.0, 10.0, 2.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcmpvLtIntegerProfile{5.016293, 1.000911, 5.016293, 1.000911};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcmpvLtFloatingProfile{3.0, 1.0, 3.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcmpvNeProfile{10.0, 2.0, 10.0, 2.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcmpvsEqProfile{3.0, 1.0, 3.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcmpvsGeProfile{12.0, 1.0, 12.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcmpvsGtProfile{12.0, 1.0, 12.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcmpvsLeProfile{12.0, 1.0, 12.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcmpvsLtProfile{12.0, 1.0, 12.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcmpvsNeProfile{12.0, 1.0, 12.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kScatterVnchwconvB16Profile{9.025814, 24.001344, 9.025814, 24.001344};
inline constexpr cce_costmodel_detail::LinearCycleProfile kScatterVnchwconvB32Profile{9.025814, 24.001344, 9.025814, 24.001344};
inline constexpr cce_costmodel_detail::LinearCycleProfile kScatterVnchwconvB8ReuseProfile{11.034115, 46.000395, 11.034115, 46.000395};
inline constexpr cce_costmodel_detail::LinearCycleProfile kScatterVnchwconvB8StridedProfile{18.388306, 40.003055, 18.388306, 40.003055};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVabsProfile{4.0, 1.0, 4.0, 1.0};
inline constexpr cce_costmodel_detail::IntegerLinearCycleProfile kVaddProfile{5.934212, 2.065788, 5.933726, 2.066274, 4.985765, 2.000853};
inline constexpr cce_costmodel_detail::IntegerLinearCycleProfile kVaddsProfile{6.0, 1.0, 6.0, 1.0, 5.010874, 1.000947};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVandProfile{2.059771, 1.999717, 2.059771, 1.999717};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVaxpyProfile{18.0, 2.0, 18.0, 2.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVbitsortProfile{8.0, 4.0, 8.0, 4.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVbrcbProfile{1.0, 1.0, 1.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcaddProfile{23.0, 7.0, 20.0, 7.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcgaddProfile{15.0, 7.0, 12.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcgmaxProfile{6.0, 7.0, 5.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcgminProfile{6.0, 7.0, 5.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcmaxProfile{9.0, 7.0, 8.0, 7.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcminProfile{9.0, 7.0, 8.0, 7.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcopyProfile{13.0, 1.0, 0.936906, 1.063094};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVdivProfile{13.0, 8.0, 13.0, 4.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVectorDupProfile{1.0, 1.0, 1.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVexpProfile{12.011812, 3.988188, 12.0, 2.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVgatherProfile{6.635214, 24.008236, 4.965026, 12.000331};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVlnProfile{13.985971, 4.014029, 14.0, 2.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVlreluProfile{7.0, 1.0, 7.0, 1.0};
inline constexpr cce_costmodel_detail::IntegerLinearCycleProfile kVmaxProfile{4.0, 2.0, 4.0, 2.0, 4.985765, 2.000853};
inline constexpr cce_costmodel_detail::IntegerLinearCycleProfile kVmaxsProfile{4.0, 1.0, 4.0, 1.0, 5.010874, 1.000947};
inline constexpr cce_costmodel_detail::IntegerLinearCycleProfile kVminProfile{4.0, 2.0, 4.0, 2.0, 4.985765, 2.000853};
inline constexpr cce_costmodel_detail::IntegerLinearCycleProfile kVminsProfile{4.0, 1.0, 4.0, 1.0, 5.010874, 1.000947};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVmrgsort4Profile{8.0, 6.0, 8.0, 6.0};
inline constexpr cce_costmodel_detail::IntegerLinearCycleProfile kVmulProfile{6.865515, 2.134485, 6.868098, 2.131902, 6.106646, 1.999717};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVmaddProfile{11.021485, 6.000879, 11.021485, 6.000879};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVmlaAccumulatorAliasProfile{11.100439, 3.999784, 11.100439, 3.999784};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVmlaSeparateOperandsProfile{11.017372, 6.000241, 11.017372, 6.000241};
inline constexpr cce_costmodel_detail::IntegerLinearCycleProfile kVmulsProfile{7.0, 1.0, 7.0, 1.0, 6.045203, 0.999906};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVnotProfile{2.088006, 0.999735, 2.088006, 0.999735};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVorProfile{2.059771, 1.999717, 2.059771, 1.999717};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVreducev2Profile{-2.0, 14.0, -2.0, 14.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVreluProfile{4.0, 1.0, 4.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVrsqrtProfile{4.791896, 1.064811, 4.791896, 1.064811};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcmpGeProfile{10.0, 2.0, 10.0, 2.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVcmpLeProfile{11.0, 2.0, 11.0, 2.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVselTensorScalarProfile{1.905969, 1.063258, 1.903226, 1.029961};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVselCmpMaskProfile{5.0, 2.0, 5.0, 2.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVshlProfile{6.045203, 0.999906, 6.045203, 0.999906};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVshrProfile{6.045203, 0.999906, 6.045203, 0.999906};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVsqrtProfile{13.0, 4.0, 13.0, 2.0};
inline constexpr cce_costmodel_detail::IntegerLinearCycleProfile kVsubProfile{5.934157, 2.065843, 5.935091, 2.064909, 4.985765, 2.000853};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVconvBf162f32Profile{6.0, 2.0, 6.0, 2.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVconvDeqProfile{7.0, 1.0, 7.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVconvF162f32Profile{5.0, 2.0, 6.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVconvF162s32aProfile{5.010874, 1.000947, 5.010874, 1.000947};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVconvF162s32cProfile{5.010874, 1.000947, 5.010874, 1.000947};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVconvF162s32fProfile{5.010874, 1.000947, 5.010874, 1.000947};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVconvF162s32rProfile{5.010874, 1.000947, 5.010874, 1.000947};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVconvF162s32zProfile{5.010874, 1.000947, 5.010874, 1.000947};
inline constexpr cce_costmodel_detail::ExpFillCycleProfile kVconvF162s8rProfile{26.75, 1.5139, 6.55, 4.76, 128, false};
inline constexpr cce_costmodel_detail::ExpFillCycleProfile kVconvF322bf16aProfile{3.18969629639, 1.5323996238, 7.29569981045, 7.84302159992, 0, false};
inline constexpr cce_costmodel_detail::ExpFillCycleProfile kVconvF322bf16cProfile{3.03019185592, 1.53319991498, 7.34550694743, 8.27164169992, 0, false};
inline constexpr cce_costmodel_detail::ExpFillCycleProfile kVconvF322bf16fProfile{3.03019185592, 1.53319991498, 7.34550694743, 8.27164169992, 0, false};
inline constexpr cce_costmodel_detail::ExpFillCycleProfile kVconvF322bf16rProfile{3.03019185592, 1.53319991498, 7.34550694743, 8.27164169992, 0, false};
inline constexpr cce_costmodel_detail::ExpFillCycleProfile kVconvF322bf16zProfile{3.03019185592, 1.53319991498, 7.34550694743, 8.27164169992, 0, false};
inline constexpr cce_costmodel_detail::ExpFillCycleProfile kVconvF322f16Profile{-9.83278980605, 1.0, 14.3148137545, 20.7763498993, 0, true};
inline constexpr cce_costmodel_detail::ExpFillCycleProfile kVconvF322f16aProfile{-10.04731634734, 1.0, 14.5320682728, 20.9559502406, 0, true};
inline constexpr cce_costmodel_detail::ExpFillCycleProfile kVconvF322f16cProfile{-9.83278980605, 1.0, 14.3148137545, 20.7763498993, 0, true};
inline constexpr cce_costmodel_detail::ExpFillCycleProfile kVconvF322f16fProfile{-9.83278980605, 1.0, 14.3148137545, 20.7763498993, 0, true};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVconvF322f16oProfile{4.0, 1.0, 4.0, 1.0};
inline constexpr cce_costmodel_detail::ExpFillCycleProfile kVconvF322f16rProfile{-9.83278980605, 1.0, 14.3148137545, 20.7763498993, 0, true};
inline constexpr cce_costmodel_detail::ExpFillCycleProfile kVconvF322f16zProfile{-9.83278980605, 1.0, 14.3148137545, 20.7763498993, 0, true};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVconvF322s32rProfile{6.0, 1.0, 6.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVconvS322f32Profile{9.0, 1.0, 9.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVconvS322f32aProfile{9.0, 1.0, 9.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVconvS322f32cProfile{9.0, 1.0, 9.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVconvS322f32fProfile{9.0, 1.0, 9.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVconvS322f32rProfile{9.0, 1.0, 9.0, 1.0};
inline constexpr cce_costmodel_detail::LinearCycleProfile kVconvS322f32zProfile{9.0, 1.0, 9.0, 1.0};
// NOLINTEND(readability-magic-numbers)
// clang-format on

} // namespace cce_cycle_profiles
